ALTER TABLE assets ADD COLUMN IF NOT EXISTS bmc_ip VARCHAR(45);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bmc_type VARCHAR(20);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bmc_firmware VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_assets_bmc_ip ON assets(bmc_ip) WHERE bmc_ip IS NOT NULL;
