// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AlertEvent defines model for AlertEvent.
type AlertEvent struct {
	CiId         openapi_types.UUID `json:"ci_id"`
	FiredAt      time.Time          `json:"fired_at"`
	Id           openapi_types.UUID `json:"id"`
	Message      string             `json:"message"`
	ResolvedAt   *time.Time         `json:"resolved_at,omitempty"`
	RuleId       openapi_types.UUID `json:"rule_id"`
	Severity     string             `json:"severity"`
	Status       string             `json:"status"`
	TriggerValue float32            `json:"trigger_value"`
}

// Asset defines model for Asset.
type Asset struct {
	AssetTag       string                 `json:"asset_tag"`
	Attributes     map[string]interface{} `json:"attributes"`
	BiaLevel       string                 `json:"bia_level"`
	ControlNumber  *string                `json:"control_number,omitempty"`
	CreatedAt      time.Time              `json:"created_at"`
	Id             openapi_types.UUID     `json:"id"`
	Model          string                 `json:"model"`
	Name           string                 `json:"name"`
	PropertyNumber *string                `json:"property_number,omitempty"`
	RackId         *openapi_types.UUID    `json:"rack_id,omitempty"`
	SerialNumber   string                 `json:"serial_number"`
	Status         string                 `json:"status"`
	SubType        string                 `json:"sub_type"`
	Tags           []string               `json:"tags"`
	Type           string                 `json:"type"`
	UpdatedAt      time.Time              `json:"updated_at"`
	Vendor         string                 `json:"vendor"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string                 `json:"action"`
	CreatedAt  time.Time              `json:"created_at"`
	Diff       map[string]interface{} `json:"diff"`
	Id         openapi_types.UUID     `json:"id"`
	Module     string                 `json:"module"`
	OperatorId openapi_types.UUID     `json:"operator_id"`
	TargetId   openapi_types.UUID     `json:"target_id"`
	TargetType string                 `json:"target_type"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	DisplayName string              `json:"display_name"`
	Email       string              `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Permissions map[string][]string `json:"permissions"`
	Username    string              `json:"username"`
}

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	ActiveOrders   int `json:"active_orders"`
	CriticalAlerts int `json:"critical_alerts"`
	TotalAssets    int `json:"total_assets"`
	TotalRacks     int `json:"total_racks"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
	Meta  Meta      `json:"meta"`
}

// InventoryItem defines model for InventoryItem.
type InventoryItem struct {
	Actual    *map[string]interface{} `json:"actual,omitempty"`
	AssetId   *openapi_types.UUID     `json:"asset_id,omitempty"`
	Expected  map[string]interface{}  `json:"expected"`
	Id        openapi_types.UUID      `json:"id"`
	RackId    *openapi_types.UUID     `json:"rack_id,omitempty"`
	ScannedAt *time.Time              `json:"scanned_at,omitempty"`
	ScannedBy *openapi_types.UUID     `json:"scanned_by,omitempty"`
	Status    string                  `json:"status"`
	TaskId    openapi_types.UUID      `json:"task_id"`
}

// InventoryTask defines model for InventoryTask.
type InventoryTask struct {
	AssignedTo      openapi_types.UUID `json:"assigned_to"`
	Code            string             `json:"code"`
	CompletedDate   *string            `json:"completed_date,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	Method          string             `json:"method"`
	Name            string             `json:"name"`
	PlannedDate     string             `json:"planned_date"`
	ScopeLocationId openapi_types.UUID `json:"scope_location_id"`
	Status          string             `json:"status"`
}

// Location defines model for Location.
type Location struct {
	CreatedAt time.Time              `json:"created_at"`
	Id        openapi_types.UUID     `json:"id"`
	Level     string                 `json:"level"`
	Metadata  map[string]interface{} `json:"metadata"`
	Name      string                 `json:"name"`
	NameEn    string                 `json:"name_en"`
	ParentId  *openapi_types.UUID    `json:"parent_id,omitempty"`
	Path      string                 `json:"path"`
	Slug      string                 `json:"slug"`
	SortOrder int                    `json:"sort_order"`
	Status    string                 `json:"status"`
	UpdatedAt time.Time              `json:"updated_at"`
}

// LocationStats defines model for LocationStats.
type LocationStats struct {
	AvgOccupancy   float32 `json:"avg_occupancy"`
	CriticalAlerts int     `json:"critical_alerts"`
	TotalAssets    int     `json:"total_assets"`
	TotalRacks     int     `json:"total_racks"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Meta defines model for Meta.
type Meta struct {
	RequestId string `json:"request_id"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page       int `json:"page"`
	PageSize   int `json:"page_size"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// PredictionModel defines model for PredictionModel.
type PredictionModel struct {
	Config   map[string]interface{} `json:"config"`
	Enabled  bool                   `json:"enabled"`
	Id       openapi_types.UUID     `json:"id"`
	Name     string                 `json:"name"`
	Provider string                 `json:"provider"`
	Type     string                 `json:"type"`
}

// PredictionResult defines model for PredictionResult.
type PredictionResult struct {
	CiId              openapi_types.UUID     `json:"ci_id"`
	CreatedAt         time.Time              `json:"created_at"`
	ExpiresAt         time.Time              `json:"expires_at"`
	Id                openapi_types.UUID     `json:"id"`
	ModelId           openapi_types.UUID     `json:"model_id"`
	PredictionType    string                 `json:"prediction_type"`
	RecommendedAction string                 `json:"recommended_action"`
	Result            map[string]interface{} `json:"result"`
	Severity          string                 `json:"severity"`
}

// RCAAnalysis defines model for RCAAnalysis.
type RCAAnalysis struct {
	ConclusionCiId *openapi_types.UUID    `json:"conclusion_ci_id,omitempty"`
	Confidence     float32                `json:"confidence"`
	HumanVerified  bool                   `json:"human_verified"`
	Id             openapi_types.UUID     `json:"id"`
	IncidentId     openapi_types.UUID     `json:"incident_id"`
	Reasoning      map[string]interface{} `json:"reasoning"`
}

// Rack defines model for Rack.
type Rack struct {
	CreatedAt       time.Time          `json:"created_at"`
	Id              openapi_types.UUID `json:"id"`
	LocationId      openapi_types.UUID `json:"location_id"`
	Name            string             `json:"name"`
	PowerCapacityKw float32            `json:"power_capacity_kw"`
	PowerCurrentKw  float32            `json:"power_current_kw"`
	RowLabel        string             `json:"row_label"`
	Status          string             `json:"status"`
	Tags            []string           `json:"tags"`
	TotalU          int                `json:"total_u"`
	UsedU           int                `json:"used_u"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// Role defines model for Role.
type Role struct {
	Description string              `json:"description"`
	Id          openapi_types.UUID  `json:"id"`
	IsSystem    bool                `json:"is_system"`
	Name        string              `json:"name"`
	Permissions map[string][]string `json:"permissions"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  string `json:"access_token"`
	ExpiresIn    int    `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time          `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
	Phone       string             `json:"phone"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	Username    string             `json:"username"`
}

// WorkOrder defines model for WorkOrder.
type WorkOrder struct {
	ActualEnd      *time.Time          `json:"actual_end,omitempty"`
	ActualStart    *time.Time          `json:"actual_start,omitempty"`
	AssigneeId     *openapi_types.UUID `json:"assignee_id,omitempty"`
	Code           string              `json:"code"`
	CreatedAt      time.Time           `json:"created_at"`
	Description    string              `json:"description"`
	Id             openapi_types.UUID  `json:"id"`
	LocationId     openapi_types.UUID  `json:"location_id"`
	Priority       string              `json:"priority"`
	ScheduledEnd   time.Time           `json:"scheduled_end"`
	ScheduledStart time.Time           `json:"scheduled_start"`
	Status         string              `json:"status"`
	Title          string              `json:"title"`
	Type           string              `json:"type"`
}

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	Page         *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize     *PageSize           `form:"page_size,omitempty" json:"page_size,omitempty"`
	Type         *string             `form:"type,omitempty" json:"type,omitempty"`
	Status       *string             `form:"status,omitempty" json:"status,omitempty"`
	LocationId   *openapi_types.UUID `form:"location_id,omitempty" json:"location_id,omitempty"`
	RackId       *openapi_types.UUID `form:"rack_id,omitempty" json:"rack_id,omitempty"`
	SerialNumber *string             `form:"serial_number,omitempty" json:"serial_number,omitempty"`
}

// QueryAuditEventsParams defines parameters for QueryAuditEvents.
type QueryAuditEventsParams struct {
	Page       *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *PageSize           `form:"page_size,omitempty" json:"page_size,omitempty"`
	Module     *string             `form:"module,omitempty" json:"module,omitempty"`
	TargetType *string             `form:"target_type,omitempty" json:"target_type,omitempty"`
	TargetId   *openapi_types.UUID `form:"target_id,omitempty" json:"target_id,omitempty"`
}

// GetDashboardStatsParams defines parameters for GetDashboardStats.
type GetDashboardStatsParams struct {
	IdcId *openapi_types.UUID `form:"idc_id,omitempty" json:"idc_id,omitempty"`
}

// ListInventoryTasksParams defines parameters for ListInventoryTasks.
type ListInventoryTasksParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListLocationsParams defines parameters for ListLocations.
type ListLocationsParams struct {
	Slug  *string `form:"slug,omitempty" json:"slug,omitempty"`
	Level *string `form:"level,omitempty" json:"level,omitempty"`
}

// ListWorkOrdersParams defines parameters for ListWorkOrders.
type ListWorkOrdersParams struct {
	Page     *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize           `form:"page_size,omitempty" json:"page_size,omitempty"`
	Status   *string             `form:"status,omitempty" json:"status,omitempty"`
	AssetId  *openapi_types.UUID `form:"asset_id,omitempty" json:"asset_id,omitempty"`
}

// CreateWorkOrderJSONBody defines parameters for CreateWorkOrder.
type CreateWorkOrderJSONBody struct {
	AssigneeId     *openapi_types.UUID `json:"assignee_id,omitempty"`
	Description    *string             `json:"description,omitempty"`
	LocationId     *openapi_types.UUID `json:"location_id,omitempty"`
	Priority       *string             `json:"priority,omitempty"`
	ScheduledEnd   *time.Time          `json:"scheduled_end,omitempty"`
	ScheduledStart *time.Time          `json:"scheduled_start,omitempty"`
	Title          string              `json:"title"`
	Type           string              `json:"type"`
}

// TransitionWorkOrderJSONBody defines parameters for TransitionWorkOrder.
type TransitionWorkOrderJSONBody struct {
	Comment *string `json:"comment,omitempty"`
	Status  string  `json:"status"`
}

// ListAlertsParams defines parameters for ListAlerts.
type ListAlertsParams struct {
	Page     *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize           `form:"page_size,omitempty" json:"page_size,omitempty"`
	Status   *string             `form:"status,omitempty" json:"status,omitempty"`
	Severity *string             `form:"severity,omitempty" json:"severity,omitempty"`
	AssetId  *openapi_types.UUID `form:"asset_id,omitempty" json:"asset_id,omitempty"`
}

// CreateRCAJSONBody defines parameters for CreateRCA.
type CreateRCAJSONBody struct {
	Context    *map[string]interface{} `json:"context,omitempty"`
	IncidentId openapi_types.UUID      `json:"incident_id"`
	ModelName  *string                 `json:"model_name,omitempty"`
}

// VerifyRCAJSONBody defines parameters for VerifyRCA.
type VerifyRCAJSONBody struct {
	VerifiedBy openapi_types.UUID `json:"verified_by"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateAssetJSONRequestBody defines body for CreateAsset for application/json ContentType.
type CreateAssetJSONRequestBody = Asset

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// CreateWorkOrderJSONRequestBody defines body for CreateWorkOrder for application/json ContentType.
type CreateWorkOrderJSONRequestBody CreateWorkOrderJSONBody

// TransitionWorkOrderJSONRequestBody defines body for TransitionWorkOrder for application/json ContentType.
type TransitionWorkOrderJSONRequestBody TransitionWorkOrderJSONBody

// CreateRCAJSONRequestBody defines body for CreateRCA for application/json ContentType.
type CreateRCAJSONRequestBody CreateRCAJSONBody

// VerifyRCAJSONRequestBody defines body for VerifyRCA for application/json ContentType.
type VerifyRCAJSONRequestBody VerifyRCAJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List assets with pagination and filters
	// (GET /assets)
	ListAssets(c *gin.Context, params ListAssetsParams)
	// Create a new asset
	// (POST /assets)
	CreateAsset(c *gin.Context)
	// Get an asset by ID
	// (GET /assets/{id})
	GetAsset(c *gin.Context, id IdPath)
	// Query audit events
	// (GET /audit/events)
	QueryAuditEvents(c *gin.Context, params QueryAuditEventsParams)
	// Authenticate and obtain tokens
	// (POST /auth/login)
	Login(c *gin.Context)
	// Get current authenticated user
	// (GET /auth/me)
	GetCurrentUser(c *gin.Context)
	// Refresh access token
	// (POST /auth/refresh)
	RefreshToken(c *gin.Context)
	// Get dashboard statistics
	// (GET /dashboard/stats)
	GetDashboardStats(c *gin.Context, params GetDashboardStatsParams)
	// List inventory tasks
	// (GET /inventory/tasks)
	ListInventoryTasks(c *gin.Context, params ListInventoryTasksParams)
	// Get an inventory task by ID
	// (GET /inventory/tasks/{id})
	GetInventoryTask(c *gin.Context, id IdPath)
	// List items in an inventory task
	// (GET /inventory/tasks/{id}/items)
	ListInventoryItems(c *gin.Context, id IdPath)
	// List locations
	// (GET /locations)
	ListLocations(c *gin.Context, params ListLocationsParams)
	// Get a location by ID
	// (GET /locations/{id})
	GetLocation(c *gin.Context, id IdPath)
	// List ancestor locations
	// (GET /locations/{id}/ancestors)
	ListLocationAncestors(c *gin.Context, id IdPath)
	// List child locations
	// (GET /locations/{id}/children)
	ListLocationChildren(c *gin.Context, id IdPath)
	// List racks in a location
	// (GET /locations/{id}/racks)
	ListLocationRacks(c *gin.Context, id IdPath)
	// Get location statistics
	// (GET /locations/{id}/stats)
	GetLocationStats(c *gin.Context, id IdPath)
	// List work orders
	// (GET /maintenance/orders)
	ListWorkOrders(c *gin.Context, params ListWorkOrdersParams)
	// Create a new work order
	// (POST /maintenance/orders)
	CreateWorkOrder(c *gin.Context)
	// Get a work order by ID
	// (GET /maintenance/orders/{id})
	GetWorkOrder(c *gin.Context, id IdPath)
	// Transition work order status
	// (POST /maintenance/orders/{id}/transition)
	TransitionWorkOrder(c *gin.Context, id IdPath)
	// List alert events
	// (GET /monitoring/alerts)
	ListAlerts(c *gin.Context, params ListAlertsParams)
	// Acknowledge an alert
	// (POST /monitoring/alerts/{id}/ack)
	AcknowledgeAlert(c *gin.Context, id IdPath)
	// Resolve an alert
	// (POST /monitoring/alerts/{id}/resolve)
	ResolveAlert(c *gin.Context, id IdPath)
	// List prediction models
	// (GET /prediction/models)
	ListPredictionModels(c *gin.Context)
	// Create a root cause analysis
	// (POST /prediction/rca)
	CreateRCA(c *gin.Context)
	// Verify an RCA analysis
	// (POST /prediction/rca/{id}/verify)
	VerifyRCA(c *gin.Context, id IdPath)
	// List predictions for a specific asset
	// (GET /prediction/results/ci/{ciId})
	ListPredictionsByAsset(c *gin.Context, ciId openapi_types.UUID)
	// Get a rack by ID
	// (GET /racks/{id})
	GetRack(c *gin.Context, id IdPath)
	// List assets in a rack
	// (GET /racks/{id}/assets)
	ListRackAssets(c *gin.Context, id IdPath)
	// List roles
	// (GET /roles)
	ListRoles(c *gin.Context)
	// List users
	// (GET /users)
	ListUsers(c *gin.Context, params ListUsersParams)
	// Get a user by ID
	// (GET /users/{id})
	GetUser(c *gin.Context, id IdPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", c.Request.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "location_id", c.Request.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter location_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "rack_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rack_id", c.Request.URL.Query(), &params.RackId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter rack_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "serial_number" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "serial_number", c.Request.URL.Query(), &params.SerialNumber, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter serial_number: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAssets(c, params)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAsset(c)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAsset(c, id)
}

// QueryAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) QueryAuditEvents(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryAuditEventsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "module" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "module", c.Request.URL.Query(), &params.Module, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter module: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "target_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "target_type", c.Request.URL.Query(), &params.TargetType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter target_type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "target_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "target_id", c.Request.URL.Query(), &params.TargetId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter target_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.QueryAuditEvents(c, params)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentUser(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// GetDashboardStats operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardStats(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardStatsParams

	// ------------- Optional query parameter "idc_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "idc_id", c.Request.URL.Query(), &params.IdcId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter idc_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDashboardStats(c, params)
}

// ListInventoryTasks operation middleware
func (siw *ServerInterfaceWrapper) ListInventoryTasks(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInventoryTasksParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInventoryTasks(c, params)
}

// GetInventoryTask operation middleware
func (siw *ServerInterfaceWrapper) GetInventoryTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventoryTask(c, id)
}

// ListInventoryItems operation middleware
func (siw *ServerInterfaceWrapper) ListInventoryItems(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInventoryItems(c, id)
}

// ListLocations operation middleware
func (siw *ServerInterfaceWrapper) ListLocations(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLocationsParams

	// ------------- Optional query parameter "slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "slug", c.Request.URL.Query(), &params.Slug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "level", c.Request.URL.Query(), &params.Level, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter level: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLocations(c, params)
}

// GetLocation operation middleware
func (siw *ServerInterfaceWrapper) GetLocation(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLocation(c, id)
}

// ListLocationAncestors operation middleware
func (siw *ServerInterfaceWrapper) ListLocationAncestors(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLocationAncestors(c, id)
}

// ListLocationChildren operation middleware
func (siw *ServerInterfaceWrapper) ListLocationChildren(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLocationChildren(c, id)
}

// ListLocationRacks operation middleware
func (siw *ServerInterfaceWrapper) ListLocationRacks(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLocationRacks(c, id)
}

// GetLocationStats operation middleware
func (siw *ServerInterfaceWrapper) GetLocationStats(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLocationStats(c, id)
}

// ListWorkOrders operation middleware
func (siw *ServerInterfaceWrapper) ListWorkOrders(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkOrdersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "asset_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "asset_id", c.Request.URL.Query(), &params.AssetId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter asset_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListWorkOrders(c, params)
}

// CreateWorkOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkOrder(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWorkOrder(c)
}

// GetWorkOrder operation middleware
func (siw *ServerInterfaceWrapper) GetWorkOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkOrder(c, id)
}

// TransitionWorkOrder operation middleware
func (siw *ServerInterfaceWrapper) TransitionWorkOrder(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TransitionWorkOrder(c, id)
}

// ListAlerts operation middleware
func (siw *ServerInterfaceWrapper) ListAlerts(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAlertsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "severity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "severity", c.Request.URL.Query(), &params.Severity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter severity: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "asset_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "asset_id", c.Request.URL.Query(), &params.AssetId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter asset_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAlerts(c, params)
}

// AcknowledgeAlert operation middleware
func (siw *ServerInterfaceWrapper) AcknowledgeAlert(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcknowledgeAlert(c, id)
}

// ResolveAlert operation middleware
func (siw *ServerInterfaceWrapper) ResolveAlert(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResolveAlert(c, id)
}

// ListPredictionModels operation middleware
func (siw *ServerInterfaceWrapper) ListPredictionModels(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPredictionModels(c)
}

// CreateRCA operation middleware
func (siw *ServerInterfaceWrapper) CreateRCA(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRCA(c)
}

// VerifyRCA operation middleware
func (siw *ServerInterfaceWrapper) VerifyRCA(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyRCA(c, id)
}

// ListPredictionsByAsset operation middleware
func (siw *ServerInterfaceWrapper) ListPredictionsByAsset(c *gin.Context) {

	var err error

	// ------------- Path parameter "ciId" -------------
	var ciId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ciId", c.Param("ciId"), &ciId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ciId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPredictionsByAsset(c, ciId)
}

// GetRack operation middleware
func (siw *ServerInterfaceWrapper) GetRack(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRack(c, id)
}

// ListRackAssets operation middleware
func (siw *ServerInterfaceWrapper) ListRackAssets(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRackAssets(c, id)
}

// ListRoles operation middleware
func (siw *ServerInterfaceWrapper) ListRoles(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRoles(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c, params)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUser(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/assets", wrapper.ListAssets)
	router.POST(options.BaseURL+"/assets", wrapper.CreateAsset)
	router.GET(options.BaseURL+"/assets/:id", wrapper.GetAsset)
	router.GET(options.BaseURL+"/audit/events", wrapper.QueryAuditEvents)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	router.GET(options.BaseURL+"/dashboard/stats", wrapper.GetDashboardStats)
	router.GET(options.BaseURL+"/inventory/tasks", wrapper.ListInventoryTasks)
	router.GET(options.BaseURL+"/inventory/tasks/:id", wrapper.GetInventoryTask)
	router.GET(options.BaseURL+"/inventory/tasks/:id/items", wrapper.ListInventoryItems)
	router.GET(options.BaseURL+"/locations", wrapper.ListLocations)
	router.GET(options.BaseURL+"/locations/:id", wrapper.GetLocation)
	router.GET(options.BaseURL+"/locations/:id/ancestors", wrapper.ListLocationAncestors)
	router.GET(options.BaseURL+"/locations/:id/children", wrapper.ListLocationChildren)
	router.GET(options.BaseURL+"/locations/:id/racks", wrapper.ListLocationRacks)
	router.GET(options.BaseURL+"/locations/:id/stats", wrapper.GetLocationStats)
	router.GET(options.BaseURL+"/maintenance/orders", wrapper.ListWorkOrders)
	router.POST(options.BaseURL+"/maintenance/orders", wrapper.CreateWorkOrder)
	router.GET(options.BaseURL+"/maintenance/orders/:id", wrapper.GetWorkOrder)
	router.POST(options.BaseURL+"/maintenance/orders/:id/transition", wrapper.TransitionWorkOrder)
	router.GET(options.BaseURL+"/monitoring/alerts", wrapper.ListAlerts)
	router.POST(options.BaseURL+"/monitoring/alerts/:id/ack", wrapper.AcknowledgeAlert)
	router.POST(options.BaseURL+"/monitoring/alerts/:id/resolve", wrapper.ResolveAlert)
	router.GET(options.BaseURL+"/prediction/models", wrapper.ListPredictionModels)
	router.POST(options.BaseURL+"/prediction/rca", wrapper.CreateRCA)
	router.POST(options.BaseURL+"/prediction/rca/:id/verify", wrapper.VerifyRCA)
	router.GET(options.BaseURL+"/prediction/results/ci/:ciId", wrapper.ListPredictionsByAsset)
	router.GET(options.BaseURL+"/racks/:id", wrapper.GetRack)
	router.GET(options.BaseURL+"/racks/:id/assets", wrapper.ListRackAssets)
	router.GET(options.BaseURL+"/roles", wrapper.ListRoles)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.GET(options.BaseURL+"/users/:id", wrapper.GetUser)
}
