// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_events.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alert_events SET
    status   = 'acknowledged',
    acked_at = now()
WHERE id = $1 AND status = 'firing'
RETURNING id, tenant_id, rule_id, asset_id, status, severity, message, trigger_value, fired_at, acked_at, resolved_at
`

func (q *Queries) AcknowledgeAlert(ctx context.Context, id uuid.UUID) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, id)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuleID,
		&i.AssetID,
		&i.Status,
		&i.Severity,
		&i.Message,
		&i.TriggerValue,
		&i.FiredAt,
		&i.AckedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const countAlerts = `-- name: CountAlerts :one
SELECT count(*) FROM alert_events
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::varchar IS NULL OR severity = $3)
  AND ($4::uuid IS NULL OR asset_id = $4)
`

type CountAlertsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Severity pgtype.Text `json:"severity"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) CountAlerts(ctx context.Context, arg CountAlertsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlerts,
		arg.TenantID,
		arg.Status,
		arg.Severity,
		arg.AssetID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertsUnderLocation = `-- name: CountAlertsUnderLocation :one
SELECT count(*) FROM alert_events ae
JOIN assets a ON ae.asset_id = a.id
JOIN locations l ON a.location_id = l.id
WHERE a.tenant_id = $1
  AND ae.status = 'firing'
  AND l.path <@ (SELECT loc.path FROM locations loc WHERE loc.id = $2)::ltree
`

type CountAlertsUnderLocationParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

// Count firing alerts for assets under a location and all its descendants
func (q *Queries) CountAlertsUnderLocation(ctx context.Context, arg CountAlertsUnderLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsUnderLocation, arg.TenantID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, tenant_id, rule_id, asset_id, status, severity, message, trigger_value, fired_at, acked_at, resolved_at FROM alert_events
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::varchar IS NULL OR severity = $5)
  AND ($6::uuid IS NULL OR asset_id = $6)
ORDER BY fired_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
	Severity pgtype.Text `json:"severity"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Severity,
		arg.AssetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuleID,
			&i.AssetID,
			&i.Status,
			&i.Severity,
			&i.Message,
			&i.TriggerValue,
			&i.FiredAt,
			&i.AckedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alert_events SET
    status      = 'resolved',
    resolved_at = now()
WHERE id = $1 AND status IN ('firing', 'acknowledged')
RETURNING id, tenant_id, rule_id, asset_id, status, severity, message, trigger_value, fired_at, acked_at, resolved_at
`

func (q *Queries) ResolveAlert(ctx context.Context, id uuid.UUID) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, resolveAlert, id)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuleID,
		&i.AssetID,
		&i.Status,
		&i.Severity,
		&i.Message,
		&i.TriggerValue,
		&i.FiredAt,
		&i.AckedAt,
		&i.ResolvedAt,
	)
	return i, err
}
