// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_rules.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countAlertRules = `-- name: CountAlertRules :one
SELECT count(*) FROM alert_rules
WHERE tenant_id = $1
`

func (q *Queries) CountAlertRules(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertRules, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (tenant_id, name, metric_name, condition, severity, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, metric_name, condition, severity, enabled, created_at
`

type CreateAlertRuleParams struct {
	TenantID   uuid.UUID       `json:"tenant_id"`
	Name       string          `json:"name"`
	MetricName string          `json:"metric_name"`
	Condition  json.RawMessage `json:"condition"`
	Severity   string          `json:"severity"`
	Enabled    bool            `json:"enabled"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.TenantID,
		arg.Name,
		arg.MetricName,
		arg.Condition,
		arg.Severity,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MetricName,
		&i.Condition,
		&i.Severity,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, tenant_id, name, metric_name, condition, severity, enabled, created_at FROM alert_rules
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertRulesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAlertRules(ctx context.Context, arg ListAlertRulesParams) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.MetricName,
			&i.Condition,
			&i.Severity,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
