// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_dependencies.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetDependency = `-- name: CreateAssetDependency :exec
INSERT INTO asset_dependencies (id, tenant_id, source_asset_id, target_asset_id, dependency_type, description)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAssetDependencyParams struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	SourceAssetID  uuid.UUID   `json:"source_asset_id"`
	TargetAssetID  uuid.UUID   `json:"target_asset_id"`
	DependencyType string      `json:"dependency_type"`
	Description    pgtype.Text `json:"description"`
}

// The unique index on (source_asset_id, target_asset_id, dependency_type)
// means duplicate edges surface as a unique-violation error — callers
// translate that to HTTP 409.
func (q *Queries) CreateAssetDependency(ctx context.Context, arg CreateAssetDependencyParams) error {
	_, err := q.db.Exec(ctx, createAssetDependency,
		arg.ID,
		arg.TenantID,
		arg.SourceAssetID,
		arg.TargetAssetID,
		arg.DependencyType,
		arg.Description,
	)
	return err
}

const deleteAssetDependency = `-- name: DeleteAssetDependency :execrows
DELETE FROM asset_dependencies
WHERE id = $1 AND tenant_id = $2
`

type DeleteAssetDependencyParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Returns rows affected so the caller can map 0 -> 404.
func (q *Queries) DeleteAssetDependency(ctx context.Context, arg DeleteAssetDependencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssetDependency, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAssetDependencies = `-- name: ListAssetDependencies :many

SELECT
    ad.id,
    ad.source_asset_id,
    sa.name AS source_asset_name,
    ad.target_asset_id,
    ta.name AS target_asset_name,
    ad.dependency_type,
    COALESCE(ad.description, '') AS description
FROM asset_dependencies ad
JOIN assets sa ON ad.source_asset_id = sa.id
JOIN assets ta ON ad.target_asset_id = ta.id
WHERE ad.tenant_id = $1
  AND (ad.source_asset_id = $2 OR ad.target_asset_id = $2)
`

type ListAssetDependenciesParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	SourceAssetID uuid.UUID `json:"source_asset_id"`
}

type ListAssetDependenciesRow struct {
	ID              uuid.UUID `json:"id"`
	SourceAssetID   uuid.UUID `json:"source_asset_id"`
	SourceAssetName string    `json:"source_asset_name"`
	TargetAssetID   uuid.UUID `json:"target_asset_id"`
	TargetAssetName string    `json:"target_asset_name"`
	DependencyType  string    `json:"dependency_type"`
	Description     string    `json:"description"`
}

// asset_dependencies: directed edges between assets (source depends on
// target). tenant_id is a first-class column and indexed; ListAssetDependencies
// and DeleteAssetDependency enforce it explicitly. ListAssetDependenciesByAssetIDs
// (used by the topology graph builder) deliberately omits the tenant_id filter
// because its caller has already narrowed the asset ID set to a single tenant;
// adding one here would be a no-op in the common case and a behavior change
// for the edge case where an external (cross-location, same-tenant) asset is
// part of the graph. Pre-migration behavior preserved.
// Returns dependency edges where the given asset is either source or target,
// joined to the assets table on both ends for display names.
func (q *Queries) ListAssetDependencies(ctx context.Context, arg ListAssetDependenciesParams) ([]ListAssetDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listAssetDependencies, arg.TenantID, arg.SourceAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetDependenciesRow{}
	for rows.Next() {
		var i ListAssetDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceAssetID,
			&i.SourceAssetName,
			&i.TargetAssetID,
			&i.TargetAssetName,
			&i.DependencyType,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetDependenciesByAssetIDs = `-- name: ListAssetDependenciesByAssetIDs :many
SELECT id, source_asset_id, target_asset_id, dependency_type
FROM asset_dependencies
WHERE source_asset_id = ANY($1::uuid[]) OR target_asset_id = ANY($1::uuid[])
`

type ListAssetDependenciesByAssetIDsRow struct {
	ID             uuid.UUID `json:"id"`
	SourceAssetID  uuid.UUID `json:"source_asset_id"`
	TargetAssetID  uuid.UUID `json:"target_asset_id"`
	DependencyType string    `json:"dependency_type"`
}

// cross-tenant: no tenant_id filter by design. Caller (GetTopologyGraph)
// has already scoped the asset ID list to a single tenant via an earlier
// tenant-scoped query; asset_dependencies rows referencing IDs outside that
// set cannot appear. Preserving pre-migration behavior verbatim.
func (q *Queries) ListAssetDependenciesByAssetIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListAssetDependenciesByAssetIDsRow, error) {
	rows, err := q.db.Query(ctx, listAssetDependenciesByAssetIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetDependenciesByAssetIDsRow{}
	for rows.Next() {
		var i ListAssetDependenciesByAssetIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceAssetID,
			&i.TargetAssetID,
			&i.DependencyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
