// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR type = $2)
  AND ($3::varchar IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR location_id = $4)
  AND ($5::uuid IS NULL OR rack_id = $5)
  AND ($6::varchar IS NULL OR serial_number = $6)
  AND ($7::varchar IS NULL OR (name ILIKE '%' || $7 || '%' OR asset_tag ILIKE '%' || $7 || '%'))
`

type CountAssetsParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Type         pgtype.Text `json:"type"`
	Status       pgtype.Text `json:"status"`
	LocationID   pgtype.UUID `json:"location_id"`
	RackID       pgtype.UUID `json:"rack_id"`
	SerialNumber pgtype.Text `json:"serial_number"`
	Search       pgtype.Text `json:"search"`
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets,
		arg.TenantID,
		arg.Type,
		arg.Status,
		arg.LocationID,
		arg.RackID,
		arg.SerialNumber,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsUnderLocation = `-- name: CountAssetsUnderLocation :one
SELECT count(*) FROM assets a
JOIN locations l ON a.location_id = l.id
WHERE a.tenant_id = $1
  AND l.path <@ (SELECT loc.path FROM locations loc WHERE loc.id = $2)::ltree
`

type CountAssetsUnderLocationParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

// Count all assets under a location and all its descendants (using ltree)
func (q *Queries) CountAssetsUnderLocation(ctx context.Context, arg CountAssetsUnderLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsUnderLocation, arg.TenantID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    tenant_id, asset_tag, property_number, control_number, name,
    type, sub_type, status, bia_level, location_id,
    rack_id, vendor, model, serial_number, attributes, tags
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16
) RETURNING id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at
`

type CreateAssetParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	AssetTag       string          `json:"asset_tag"`
	PropertyNumber pgtype.Text     `json:"property_number"`
	ControlNumber  pgtype.Text     `json:"control_number"`
	Name           string          `json:"name"`
	Type           string          `json:"type"`
	SubType        pgtype.Text     `json:"sub_type"`
	Status         string          `json:"status"`
	BiaLevel       string          `json:"bia_level"`
	LocationID     pgtype.UUID     `json:"location_id"`
	RackID         pgtype.UUID     `json:"rack_id"`
	Vendor         pgtype.Text     `json:"vendor"`
	Model          pgtype.Text     `json:"model"`
	SerialNumber   pgtype.Text     `json:"serial_number"`
	Attributes     json.RawMessage `json:"attributes"`
	Tags           []string        `json:"tags"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.TenantID,
		arg.AssetTag,
		arg.PropertyNumber,
		arg.ControlNumber,
		arg.Name,
		arg.Type,
		arg.SubType,
		arg.Status,
		arg.BiaLevel,
		arg.LocationID,
		arg.RackID,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.Attributes,
		arg.Tags,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1 AND tenant_id = $2
`

type DeleteAssetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAsset(ctx context.Context, arg DeleteAssetParams) error {
	_, err := q.db.Exec(ctx, deleteAsset, arg.ID, arg.TenantID)
	return err
}

const findAssetBySerialOrTag = `-- name: FindAssetBySerialOrTag :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at FROM assets
WHERE tenant_id = $1
  AND (serial_number = $2 OR asset_tag = $3)
LIMIT 1
`

type FindAssetBySerialOrTagParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	SerialNumber pgtype.Text `json:"serial_number"`
	AssetTag     string      `json:"asset_tag"`
}

func (q *Queries) FindAssetBySerialOrTag(ctx context.Context, arg FindAssetBySerialOrTagParams) (Asset, error) {
	row := q.db.QueryRow(ctx, findAssetBySerialOrTag, arg.TenantID, arg.SerialNumber, arg.AssetTag)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at FROM assets WHERE id = $1 AND tenant_id = $2
`

type GetAssetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.ID, arg.TenantID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByTag = `-- name: GetAssetByTag :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at FROM assets WHERE asset_tag = $1
`

func (q *Queries) GetAssetByTag(ctx context.Context, assetTag string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByTag, assetTag)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at FROM assets
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($4::varchar IS NULL OR type = $4)
  AND ($5::varchar IS NULL OR status = $5)
  AND ($6::uuid IS NULL OR location_id = $6)
  AND ($7::uuid IS NULL OR rack_id = $7)
  AND ($8::varchar IS NULL OR serial_number = $8)
  AND ($9::varchar IS NULL OR (name ILIKE '%' || $9 || '%' OR asset_tag ILIKE '%' || $9 || '%'))
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssetsParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	Type         pgtype.Text `json:"type"`
	Status       pgtype.Text `json:"status"`
	LocationID   pgtype.UUID `json:"location_id"`
	RackID       pgtype.UUID `json:"rack_id"`
	SerialNumber pgtype.Text `json:"serial_number"`
	Search       pgtype.Text `json:"search"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.Status,
		arg.LocationID,
		arg.RackID,
		arg.SerialNumber,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetTag,
			&i.PropertyNumber,
			&i.ControlNumber,
			&i.Name,
			&i.Type,
			&i.SubType,
			&i.Status,
			&i.BiaLevel,
			&i.LocationID,
			&i.RackID,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.Attributes,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets SET
    asset_tag       = COALESCE($1, asset_tag),
    property_number = COALESCE($2, property_number),
    control_number  = COALESCE($3, control_number),
    name            = COALESCE($4, name),
    type            = COALESCE($5, type),
    sub_type        = COALESCE($6, sub_type),
    status          = COALESCE($7, status),
    bia_level       = COALESCE($8, bia_level),
    location_id     = COALESCE($9, location_id),
    rack_id         = COALESCE($10, rack_id),
    vendor          = COALESCE($11, vendor),
    model           = COALESCE($12, model),
    serial_number   = COALESCE($13, serial_number),
    attributes      = COALESCE($14, attributes),
    tags            = COALESCE($15, tags),
    updated_at      = now()
WHERE id = $16
RETURNING id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at
`

type UpdateAssetParams struct {
	AssetTag       pgtype.Text `json:"asset_tag"`
	PropertyNumber pgtype.Text `json:"property_number"`
	ControlNumber  pgtype.Text `json:"control_number"`
	Name           pgtype.Text `json:"name"`
	Type           pgtype.Text `json:"type"`
	SubType        pgtype.Text `json:"sub_type"`
	Status         pgtype.Text `json:"status"`
	BiaLevel       pgtype.Text `json:"bia_level"`
	LocationID     pgtype.UUID `json:"location_id"`
	RackID         pgtype.UUID `json:"rack_id"`
	Vendor         pgtype.Text `json:"vendor"`
	Model          pgtype.Text `json:"model"`
	SerialNumber   pgtype.Text `json:"serial_number"`
	Attributes     []byte      `json:"attributes"`
	Tags           []string    `json:"tags"`
	ID             uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.AssetTag,
		arg.PropertyNumber,
		arg.ControlNumber,
		arg.Name,
		arg.Type,
		arg.SubType,
		arg.Status,
		arg.BiaLevel,
		arg.LocationID,
		arg.RackID,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.Attributes,
		arg.Tags,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
