// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: asset_snapshots.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAssetSnapshots = `-- name: CountAssetSnapshots :one
SELECT COUNT(*) FROM asset_snapshots
WHERE tenant_id = $1
`

// Health-check query used by the admin diagnostics endpoint to confirm
// the snapshot trigger is firing. A stuck trigger shows up as a count
// that stops growing relative to audit_events.
func (q *Queries) CountAssetSnapshots(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetSnapshots, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAssetStateAt = `-- name: GetAssetStateAt :one
SELECT id, asset_id, tenant_id, valid_at, name, asset_tag, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, owner_team
FROM asset_snapshots
WHERE asset_id = $1
  AND tenant_id = $2
  AND valid_at <= $3
ORDER BY valid_at DESC
LIMIT 1
`

type GetAssetStateAtParams struct {
	AssetID  uuid.UUID `json:"asset_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	ValidAt  time.Time `json:"valid_at"`
}

// D10-P0: point-in-time query. Returns the most-recent snapshot whose
// valid_at is <= the caller's target time, scoped to the asset and
// tenant. The (asset_id, valid_at DESC) index makes this a single
// partition+index lookup regardless of how many snapshots exist.
// Returns sql.ErrNoRows when the asset has no snapshot at or before
// the query time — the service layer maps this to a 404.
func (q *Queries) GetAssetStateAt(ctx context.Context, arg GetAssetStateAtParams) (AssetSnapshot, error) {
	row := q.db.QueryRow(ctx, getAssetStateAt, arg.AssetID, arg.TenantID, arg.ValidAt)
	var i AssetSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TenantID,
		&i.ValidAt,
		&i.Name,
		&i.AssetTag,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.OwnerTeam,
	)
	return i, err
}

const listAssetSnapshots = `-- name: ListAssetSnapshots :many
SELECT id, asset_id, tenant_id, valid_at, name, asset_tag, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, owner_team
FROM asset_snapshots
WHERE asset_id = $1
  AND tenant_id = $2
ORDER BY valid_at DESC
LIMIT $3
`

type ListAssetSnapshotsParams struct {
	AssetID  uuid.UUID `json:"asset_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

// All snapshots for an asset, newest first. Feeds the "asset history"
// UI and lets an operator walk every state change without needing to
// replay the audit diff chain. Bounded by $3 because a heavily-edited
// asset can produce thousands of rows; the default call site passes
// 100.
func (q *Queries) ListAssetSnapshots(ctx context.Context, arg ListAssetSnapshotsParams) ([]AssetSnapshot, error) {
	rows, err := q.db.Query(ctx, listAssetSnapshots, arg.AssetID, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetSnapshot{}
	for rows.Next() {
		var i AssetSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.TenantID,
			&i.ValidAt,
			&i.Name,
			&i.AssetTag,
			&i.Status,
			&i.BiaLevel,
			&i.LocationID,
			&i.RackID,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.Attributes,
			&i.Tags,
			&i.OwnerTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
