// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assets.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpAssetAccess = `-- name: BumpAssetAccess :exec
UPDATE assets
SET access_count_24h = access_count_24h + 1,
    last_accessed_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type BumpAssetAccessParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// D9-P1 read-heat counter. Called from the GetAsset/ListAssets handlers
// to track which assets are actively being read. Bypasses the 000058
// snapshot trigger because access_count_24h / last_accessed_at are NOT
// in the trigger's WHEN column list — an UPDATE that only touches these
// columns leaves asset_snapshots untouched.
//
// Tenant scoping is enforced even though the caller already has the
// tenant from context; defense-in-depth against any future code path
// that might forward an asset_id without its tenant.
func (q *Queries) BumpAssetAccess(ctx context.Context, arg BumpAssetAccessParams) error {
	_, err := q.db.Exec(ctx, bumpAssetAccess, arg.ID, arg.TenantID)
	return err
}

const bumpAssetsAccess = `-- name: BumpAssetsAccess :exec
UPDATE assets
SET access_count_24h = access_count_24h + 1,
    last_accessed_at = now()
WHERE id = ANY($1::uuid[])
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type BumpAssetsAccessParams struct {
	Ids      []uuid.UUID `json:"ids"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

// Batch variant for ListAssets: one UPDATE touches N rows. Cheaper
// than emitting N separate BumpAssetAccess calls when a large list
// page is rendered.
func (q *Queries) BumpAssetsAccess(ctx context.Context, arg BumpAssetsAccessParams) error {
	_, err := q.db.Exec(ctx, bumpAssetsAccess, arg.Ids, arg.TenantID)
	return err
}

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR type = $2)
  AND ($3::varchar IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR location_id = $4)
  AND ($5::uuid IS NULL OR rack_id = $5)
  AND ($6::varchar IS NULL OR serial_number = $6)
  AND ($7::varchar IS NULL OR owner_team = $7)
  AND ($8::varchar IS NULL OR (name ILIKE '%' || $8 || '%' OR asset_tag ILIKE '%' || $8 || '%'))
`

type CountAssetsParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Type         pgtype.Text `json:"type"`
	Status       pgtype.Text `json:"status"`
	LocationID   pgtype.UUID `json:"location_id"`
	RackID       pgtype.UUID `json:"rack_id"`
	SerialNumber pgtype.Text `json:"serial_number"`
	OwnerTeam    pgtype.Text `json:"owner_team"`
	Search       pgtype.Text `json:"search"`
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets,
		arg.TenantID,
		arg.Type,
		arg.Status,
		arg.LocationID,
		arg.RackID,
		arg.SerialNumber,
		arg.OwnerTeam,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsUnderLocation = `-- name: CountAssetsUnderLocation :one
SELECT count(*) FROM assets a
JOIN locations l ON a.location_id = l.id
WHERE a.tenant_id = $1
  AND l.path <@ (SELECT loc.path FROM locations loc WHERE loc.id = $2)::ltree
`

type CountAssetsUnderLocationParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

// Count all assets under a location and all its descendants (using ltree)
func (q *Queries) CountAssetsUnderLocation(ctx context.Context, arg CountAssetsUnderLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsUnderLocation, arg.TenantID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    tenant_id, asset_tag, property_number, control_number, name,
    type, sub_type, status, bia_level, location_id,
    rack_id, vendor, model, serial_number, attributes, tags,
    bmc_ip, bmc_type, bmc_firmware,
    purchase_date, purchase_cost, warranty_start, warranty_end,
    warranty_vendor, warranty_contract, expected_lifespan_months, eol_date,
    owner_team
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22, $23,
    $24, $25, $26, $27,
    $28
) RETURNING id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team
`

type CreateAssetParams struct {
	TenantID               uuid.UUID       `json:"tenant_id"`
	AssetTag               string          `json:"asset_tag"`
	PropertyNumber         pgtype.Text     `json:"property_number"`
	ControlNumber          pgtype.Text     `json:"control_number"`
	Name                   string          `json:"name"`
	Type                   string          `json:"type"`
	SubType                pgtype.Text     `json:"sub_type"`
	Status                 string          `json:"status"`
	BiaLevel               string          `json:"bia_level"`
	LocationID             pgtype.UUID     `json:"location_id"`
	RackID                 pgtype.UUID     `json:"rack_id"`
	Vendor                 pgtype.Text     `json:"vendor"`
	Model                  pgtype.Text     `json:"model"`
	SerialNumber           pgtype.Text     `json:"serial_number"`
	Attributes             json.RawMessage `json:"attributes"`
	Tags                   []string        `json:"tags"`
	BmcIp                  pgtype.Text     `json:"bmc_ip"`
	BmcType                pgtype.Text     `json:"bmc_type"`
	BmcFirmware            pgtype.Text     `json:"bmc_firmware"`
	PurchaseDate           pgtype.Date     `json:"purchase_date"`
	PurchaseCost           pgtype.Numeric  `json:"purchase_cost"`
	WarrantyStart          pgtype.Date     `json:"warranty_start"`
	WarrantyEnd            pgtype.Date     `json:"warranty_end"`
	WarrantyVendor         pgtype.Text     `json:"warranty_vendor"`
	WarrantyContract       pgtype.Text     `json:"warranty_contract"`
	ExpectedLifespanMonths pgtype.Int4     `json:"expected_lifespan_months"`
	EolDate                pgtype.Date     `json:"eol_date"`
	OwnerTeam              pgtype.Text     `json:"owner_team"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.TenantID,
		arg.AssetTag,
		arg.PropertyNumber,
		arg.ControlNumber,
		arg.Name,
		arg.Type,
		arg.SubType,
		arg.Status,
		arg.BiaLevel,
		arg.LocationID,
		arg.RackID,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.Attributes,
		arg.Tags,
		arg.BmcIp,
		arg.BmcType,
		arg.BmcFirmware,
		arg.PurchaseDate,
		arg.PurchaseCost,
		arg.WarrantyStart,
		arg.WarrantyEnd,
		arg.WarrantyVendor,
		arg.WarrantyContract,
		arg.ExpectedLifespanMonths,
		arg.EolDate,
		arg.OwnerTeam,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.BmcIp,
		&i.BmcType,
		&i.BmcFirmware,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyStart,
		&i.WarrantyEnd,
		&i.WarrantyVendor,
		&i.WarrantyContract,
		&i.ExpectedLifespanMonths,
		&i.EolDate,
		&i.AccessCount24h,
		&i.LastAccessedAt,
		&i.OwnerTeam,
	)
	return i, err
}

const decayAssetAccessCounts = `-- name: DecayAssetAccessCounts :exec
UPDATE assets SET access_count_24h = 0 WHERE access_count_24h > 0
`

// D9-P1 nightly rollup. Zeroes the rolling 24h counter so the number
// stays bounded. last_accessed_at is deliberately preserved — it's an
// absolute wall-clock reference used elsewhere (cold-asset detection,
// quality downweighting) and has no "decay" semantics.
func (q *Queries) DecayAssetAccessCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, decayAssetAccessCounts)
	return err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1 AND tenant_id = $2
`

type DeleteAssetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAsset(ctx context.Context, arg DeleteAssetParams) error {
	_, err := q.db.Exec(ctx, deleteAsset, arg.ID, arg.TenantID)
	return err
}

const findAssetBySerialOrTag = `-- name: FindAssetBySerialOrTag :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team FROM assets
WHERE tenant_id = $1
  AND (serial_number = $2 OR asset_tag = $3)
LIMIT 1
`

type FindAssetBySerialOrTagParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	SerialNumber pgtype.Text `json:"serial_number"`
	AssetTag     string      `json:"asset_tag"`
}

func (q *Queries) FindAssetBySerialOrTag(ctx context.Context, arg FindAssetBySerialOrTagParams) (Asset, error) {
	row := q.db.QueryRow(ctx, findAssetBySerialOrTag, arg.TenantID, arg.SerialNumber, arg.AssetTag)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.BmcIp,
		&i.BmcType,
		&i.BmcFirmware,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyStart,
		&i.WarrantyEnd,
		&i.WarrantyVendor,
		&i.WarrantyContract,
		&i.ExpectedLifespanMonths,
		&i.EolDate,
		&i.AccessCount24h,
		&i.LastAccessedAt,
		&i.OwnerTeam,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team FROM assets WHERE id = $1 AND tenant_id = $2
`

type GetAssetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.ID, arg.TenantID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.BmcIp,
		&i.BmcType,
		&i.BmcFirmware,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyStart,
		&i.WarrantyEnd,
		&i.WarrantyVendor,
		&i.WarrantyContract,
		&i.ExpectedLifespanMonths,
		&i.EolDate,
		&i.AccessCount24h,
		&i.LastAccessedAt,
		&i.OwnerTeam,
	)
	return i, err
}

const getAssetByTag = `-- name: GetAssetByTag :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team FROM assets WHERE asset_tag = $1
`

func (q *Queries) GetAssetByTag(ctx context.Context, assetTag string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByTag, assetTag)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.BmcIp,
		&i.BmcType,
		&i.BmcFirmware,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyStart,
		&i.WarrantyEnd,
		&i.WarrantyVendor,
		&i.WarrantyContract,
		&i.ExpectedLifespanMonths,
		&i.EolDate,
		&i.AccessCount24h,
		&i.LastAccessedAt,
		&i.OwnerTeam,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team FROM assets
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($4::varchar IS NULL OR type = $4)
  AND ($5::varchar IS NULL OR status = $5)
  AND ($6::uuid IS NULL OR location_id = $6)
  AND ($7::uuid IS NULL OR rack_id = $7)
  AND ($8::varchar IS NULL OR serial_number = $8)
  AND ($9::varchar IS NULL OR owner_team = $9)
  AND ($10::varchar IS NULL OR (name ILIKE '%' || $10 || '%' OR asset_tag ILIKE '%' || $10 || '%'))
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssetsParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	Type         pgtype.Text `json:"type"`
	Status       pgtype.Text `json:"status"`
	LocationID   pgtype.UUID `json:"location_id"`
	RackID       pgtype.UUID `json:"rack_id"`
	SerialNumber pgtype.Text `json:"serial_number"`
	OwnerTeam    pgtype.Text `json:"owner_team"`
	Search       pgtype.Text `json:"search"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.Status,
		arg.LocationID,
		arg.RackID,
		arg.SerialNumber,
		arg.OwnerTeam,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetTag,
			&i.PropertyNumber,
			&i.ControlNumber,
			&i.Name,
			&i.Type,
			&i.SubType,
			&i.Status,
			&i.BiaLevel,
			&i.LocationID,
			&i.RackID,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.Attributes,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.DeletedAt,
			&i.SyncVersion,
			&i.BmcIp,
			&i.BmcType,
			&i.BmcFirmware,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyStart,
			&i.WarrantyEnd,
			&i.WarrantyVendor,
			&i.WarrantyContract,
			&i.ExpectedLifespanMonths,
			&i.EolDate,
			&i.AccessCount24h,
			&i.LastAccessedAt,
			&i.OwnerTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotAssets = `-- name: ListHotAssets :many
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team FROM assets
WHERE tenant_id = $1 AND deleted_at IS NULL AND access_count_24h > 0
ORDER BY access_count_24h DESC, last_accessed_at DESC NULLS LAST
LIMIT $2
`

type ListHotAssetsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

// Top-N hot assets per tenant, used by the admin dashboard's "most
// read" widget. Uses idx_assets_access_heat (partial, count>0).
func (q *Queries) ListHotAssets(ctx context.Context, arg ListHotAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listHotAssets, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetTag,
			&i.PropertyNumber,
			&i.ControlNumber,
			&i.Name,
			&i.Type,
			&i.SubType,
			&i.Status,
			&i.BiaLevel,
			&i.LocationID,
			&i.RackID,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.Attributes,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.DeletedAt,
			&i.SyncVersion,
			&i.BmcIp,
			&i.BmcType,
			&i.BmcFirmware,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyStart,
			&i.WarrantyEnd,
			&i.WarrantyVendor,
			&i.WarrantyContract,
			&i.ExpectedLifespanMonths,
			&i.EolDate,
			&i.AccessCount24h,
			&i.LastAccessedAt,
			&i.OwnerTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets SET
    asset_tag       = COALESCE($1, asset_tag),
    property_number = COALESCE($2, property_number),
    control_number  = COALESCE($3, control_number),
    name            = COALESCE($4, name),
    type            = COALESCE($5, type),
    sub_type        = COALESCE($6, sub_type),
    status          = COALESCE($7, status),
    bia_level       = COALESCE($8, bia_level),
    location_id     = COALESCE($9, location_id),
    rack_id         = COALESCE($10, rack_id),
    vendor          = COALESCE($11, vendor),
    model           = COALESCE($12, model),
    serial_number   = COALESCE($13, serial_number),
    attributes      = COALESCE($14, attributes),
    tags            = COALESCE($15, tags),
    bmc_ip                   = COALESCE($16, bmc_ip),
    bmc_type                 = COALESCE($17, bmc_type),
    bmc_firmware             = COALESCE($18, bmc_firmware),
    purchase_date            = COALESCE($19, purchase_date),
    purchase_cost            = COALESCE($20, purchase_cost),
    warranty_start           = COALESCE($21, warranty_start),
    warranty_end             = COALESCE($22, warranty_end),
    warranty_vendor          = COALESCE($23, warranty_vendor),
    warranty_contract        = COALESCE($24, warranty_contract),
    expected_lifespan_months = COALESCE($25, expected_lifespan_months),
    eol_date                 = COALESCE($26, eol_date),
    owner_team               = COALESCE($27, owner_team),
    updated_at               = now()
WHERE id = $28
RETURNING id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, attributes, tags, created_at, updated_at, ip_address, deleted_at, sync_version, bmc_ip, bmc_type, bmc_firmware, purchase_date, purchase_cost, warranty_start, warranty_end, warranty_vendor, warranty_contract, expected_lifespan_months, eol_date, access_count_24h, last_accessed_at, owner_team
`

type UpdateAssetParams struct {
	AssetTag               pgtype.Text    `json:"asset_tag"`
	PropertyNumber         pgtype.Text    `json:"property_number"`
	ControlNumber          pgtype.Text    `json:"control_number"`
	Name                   pgtype.Text    `json:"name"`
	Type                   pgtype.Text    `json:"type"`
	SubType                pgtype.Text    `json:"sub_type"`
	Status                 pgtype.Text    `json:"status"`
	BiaLevel               pgtype.Text    `json:"bia_level"`
	LocationID             pgtype.UUID    `json:"location_id"`
	RackID                 pgtype.UUID    `json:"rack_id"`
	Vendor                 pgtype.Text    `json:"vendor"`
	Model                  pgtype.Text    `json:"model"`
	SerialNumber           pgtype.Text    `json:"serial_number"`
	Attributes             []byte         `json:"attributes"`
	Tags                   []string       `json:"tags"`
	BmcIp                  pgtype.Text    `json:"bmc_ip"`
	BmcType                pgtype.Text    `json:"bmc_type"`
	BmcFirmware            pgtype.Text    `json:"bmc_firmware"`
	PurchaseDate           pgtype.Date    `json:"purchase_date"`
	PurchaseCost           pgtype.Numeric `json:"purchase_cost"`
	WarrantyStart          pgtype.Date    `json:"warranty_start"`
	WarrantyEnd            pgtype.Date    `json:"warranty_end"`
	WarrantyVendor         pgtype.Text    `json:"warranty_vendor"`
	WarrantyContract       pgtype.Text    `json:"warranty_contract"`
	ExpectedLifespanMonths pgtype.Int4    `json:"expected_lifespan_months"`
	EolDate                pgtype.Date    `json:"eol_date"`
	OwnerTeam              pgtype.Text    `json:"owner_team"`
	ID                     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.AssetTag,
		arg.PropertyNumber,
		arg.ControlNumber,
		arg.Name,
		arg.Type,
		arg.SubType,
		arg.Status,
		arg.BiaLevel,
		arg.LocationID,
		arg.RackID,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.Attributes,
		arg.Tags,
		arg.BmcIp,
		arg.BmcType,
		arg.BmcFirmware,
		arg.PurchaseDate,
		arg.PurchaseCost,
		arg.WarrantyStart,
		arg.WarrantyEnd,
		arg.WarrantyVendor,
		arg.WarrantyContract,
		arg.ExpectedLifespanMonths,
		arg.EolDate,
		arg.OwnerTeam,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.BmcIp,
		&i.BmcType,
		&i.BmcFirmware,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyStart,
		&i.WarrantyEnd,
		&i.WarrantyVendor,
		&i.WarrantyContract,
		&i.ExpectedLifespanMonths,
		&i.EolDate,
		&i.AccessCount24h,
		&i.LastAccessedAt,
		&i.OwnerTeam,
	)
	return i, err
}
