// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_location_history.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuthorizedRelocationsSince = `-- name: CountAuthorizedRelocationsSince :one
SELECT count(*)
FROM asset_location_history
WHERE tenant_id = $1
  AND detected_at > now() - ($2::int * interval '1 day')
  AND work_order_id IS NOT NULL
`

type CountAuthorizedRelocationsSinceParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  int32     `json:"column_2"`
}

// Used by LocationDetectGetReport — count of relocations in the last
// $2 days that also have a backing work_order_id.
func (q *Queries) CountAuthorizedRelocationsSince(ctx context.Context, arg CountAuthorizedRelocationsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthorizedRelocationsSince, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelocationsSince = `-- name: CountRelocationsSince :one
SELECT count(*)
FROM asset_location_history
WHERE tenant_id = $1
  AND detected_at > now() - ($2::int * interval '1 day')
`

type CountRelocationsSinceParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  int32     `json:"column_2"`
}

// Used by LocationDetectGetReport (variable window in days).
// Intervals pass as an int day count rather than pgtype.Interval —
// the convention established by DeleteOldWebhookDeliveries.
func (q *Queries) CountRelocationsSince(ctx context.Context, arg CountRelocationsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRelocationsSince, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelocationsSince24h = `-- name: CountRelocationsSince24h :one
SELECT count(*)
FROM asset_location_history
WHERE tenant_id = $1
  AND detected_at > now() - interval '24 hours'
`

// Used by LocationDetectGetSummary (fixed 24h window).
func (q *Queries) CountRelocationsSince24h(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRelocationsSince24h, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const detectBulkDisappearance = `-- name: DetectBulkDisappearance :many
SELECT h.from_rack_id, r.name, count(*)::bigint AS device_count
FROM asset_location_history h
JOIN racks r ON h.from_rack_id = r.id
WHERE h.tenant_id = $1
  AND h.detected_at > now() - interval '1 hour'
  AND h.from_rack_id IS NOT NULL
GROUP BY h.from_rack_id, r.name
HAVING count(*) >= 3
`

type DetectBulkDisappearanceRow struct {
	FromRackID  pgtype.UUID `json:"from_rack_id"`
	Name        string      `json:"name"`
	DeviceCount int64       `json:"device_count"`
}

// Racks where 3 or more devices left in the last hour.
func (q *Queries) DetectBulkDisappearance(ctx context.Context, tenantID uuid.UUID) ([]DetectBulkDisappearanceRow, error) {
	rows, err := q.db.Query(ctx, detectBulkDisappearance, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectBulkDisappearanceRow{}
	for rows.Next() {
		var i DetectBulkDisappearanceRow
		if err := rows.Scan(&i.FromRackID, &i.Name, &i.DeviceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const detectFrequentRelocations = `-- name: DetectFrequentRelocations :many
SELECT h.asset_id, a.asset_tag, a.name, count(*)::bigint AS move_count
FROM asset_location_history h
JOIN assets a ON h.asset_id = a.id
WHERE h.tenant_id = $1 AND h.detected_at > now() - interval '30 days'
GROUP BY h.asset_id, a.asset_tag, a.name
HAVING count(*) >= 3
ORDER BY count(*) DESC
`

type DetectFrequentRelocationsRow struct {
	AssetID   uuid.UUID `json:"asset_id"`
	AssetTag  string    `json:"asset_tag"`
	Name      string    `json:"name"`
	MoveCount int64     `json:"move_count"`
}

// Assets that moved 3 or more times in 30 days. Used by the anomaly
// detector.
func (q *Queries) DetectFrequentRelocations(ctx context.Context, tenantID uuid.UUID) ([]DetectFrequentRelocationsRow, error) {
	rows, err := q.db.Query(ctx, detectFrequentRelocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectFrequentRelocationsRow{}
	for rows.Next() {
		var i DetectFrequentRelocationsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AssetTag,
			&i.Name,
			&i.MoveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const detectOffHoursRelocations = `-- name: DetectOffHoursRelocations :many
SELECT h.asset_id, a.asset_tag, a.name, h.detected_at
FROM asset_location_history h
JOIN assets a ON h.asset_id = a.id
WHERE h.tenant_id = $1
  AND h.detected_at > now() - interval '24 hours'
  AND (EXTRACT(HOUR FROM h.detected_at) >= 22 OR EXTRACT(HOUR FROM h.detected_at) < 6)
ORDER BY h.detected_at DESC
`

type DetectOffHoursRelocationsRow struct {
	AssetID    uuid.UUID          `json:"asset_id"`
	AssetTag   string             `json:"asset_tag"`
	Name       string             `json:"name"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
}

// Relocations between 22:00 and 06:00 in the last 24h. The HOUR EXTRACT
// uses server local time — preserving pre-migration behavior.
func (q *Queries) DetectOffHoursRelocations(ctx context.Context, tenantID uuid.UUID) ([]DetectOffHoursRelocationsRow, error) {
	rows, err := q.db.Query(ctx, detectOffHoursRelocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DetectOffHoursRelocationsRow{}
	for rows.Next() {
		var i DetectOffHoursRelocationsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AssetTag,
			&i.Name,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationHistory = `-- name: GetLocationHistory :many
SELECT
    h.id,
    h.from_rack_id,
    fr.name AS from_rack_name,
    h.to_rack_id,
    tr.name AS to_rack_name,
    h.detected_by,
    h.work_order_id,
    h.detected_at
FROM asset_location_history h
LEFT JOIN racks fr ON h.from_rack_id = fr.id
LEFT JOIN racks tr ON h.to_rack_id = tr.id
WHERE h.asset_id = $1
ORDER BY h.detected_at DESC
LIMIT $2
`

type GetLocationHistoryParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	Limit   int32     `json:"limit"`
}

type GetLocationHistoryRow struct {
	ID           uuid.UUID          `json:"id"`
	FromRackID   pgtype.UUID        `json:"from_rack_id"`
	FromRackName pgtype.Text        `json:"from_rack_name"`
	ToRackID     pgtype.UUID        `json:"to_rack_id"`
	ToRackName   pgtype.Text        `json:"to_rack_name"`
	DetectedBy   string             `json:"detected_by"`
	WorkOrderID  pgtype.UUID        `json:"work_order_id"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
}

// cross-tenant: scoped by asset_id only. Pre-migration parity.
func (q *Queries) GetLocationHistory(ctx context.Context, arg GetLocationHistoryParams) ([]GetLocationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getLocationHistory, arg.AssetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLocationHistoryRow{}
	for rows.Next() {
		var i GetLocationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FromRackID,
			&i.FromRackName,
			&i.ToRackID,
			&i.ToRackName,
			&i.DetectedBy,
			&i.WorkOrderID,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLocationChange = `-- name: RecordLocationChange :exec

INSERT INTO asset_location_history (tenant_id, asset_id, from_rack_id, to_rack_id, detected_by, work_order_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordLocationChangeParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	AssetID     uuid.UUID   `json:"asset_id"`
	FromRackID  pgtype.UUID `json:"from_rack_id"`
	ToRackID    pgtype.UUID `json:"to_rack_id"`
	DetectedBy  string      `json:"detected_by"`
	WorkOrderID pgtype.UUID `json:"work_order_id"`
}

// asset_location_history: append-only audit of physical relocations
// detected by the location_detect pipeline. tenant_id is a first-class
// column. All queries here are tenant-scoped EXCEPT GetLocationHistory,
// which historically scopes only by asset_id — that is preserved
// verbatim and annotated cross-tenant: (the asset FK row is tenant-
// scoped upstream, so callers that have already fetched the asset are
// implicitly tenant-safe; adding a tenant filter here would be a
// behavior change for no security gain).
// Called by location_detect.Service on every detected asset move.
// All nullable columns are passed through as pgtype.UUID so callers can
// record an initial placement (from_rack_id NULL) or a relocation
// without a work order (work_order_id NULL).
func (q *Queries) RecordLocationChange(ctx context.Context, arg RecordLocationChangeParams) error {
	_, err := q.db.Exec(ctx, recordLocationChange,
		arg.TenantID,
		arg.AssetID,
		arg.FromRackID,
		arg.ToRackID,
		arg.DetectedBy,
		arg.WorkOrderID,
	)
	return err
}
