// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR module = $2)
  AND ($3::varchar IS NULL OR target_type = $3)
  AND ($4::uuid IS NULL OR target_id = $4)
`

type CountAuditEventsParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Module     pgtype.Text `json:"module"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.TenantID,
		arg.Module,
		arg.TargetType,
		arg.TargetID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    tenant_id, action, module, target_type,
    target_id, operator_type, operator_id, diff, source
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
) RETURNING id, tenant_id, action, module, target_type, target_id, operator_id, diff, source, created_at, operator_type
`

type CreateAuditEventParams struct {
	TenantID     uuid.UUID         `json:"tenant_id"`
	Action       string            `json:"action"`
	Module       pgtype.Text       `json:"module"`
	TargetType   pgtype.Text       `json:"target_type"`
	TargetID     pgtype.UUID       `json:"target_id"`
	OperatorType AuditOperatorType `json:"operator_type"`
	OperatorID   pgtype.UUID       `json:"operator_id"`
	Diff         []byte            `json:"diff"`
	Source       string            `json:"source"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.TenantID,
		arg.Action,
		arg.Module,
		arg.TargetType,
		arg.TargetID,
		arg.OperatorType,
		arg.OperatorID,
		arg.Diff,
		arg.Source,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Action,
		&i.Module,
		&i.TargetType,
		&i.TargetID,
		&i.OperatorID,
		&i.Diff,
		&i.Source,
		&i.CreatedAt,
		&i.OperatorType,
	)
	return i, err
}

const queryAuditEvents = `-- name: QueryAuditEvents :many
SELECT id, tenant_id, action, module, target_type, target_id, operator_id, diff, source, created_at, operator_type FROM audit_events
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR module = $4)
  AND ($5::varchar IS NULL OR target_type = $5)
  AND ($6::uuid IS NULL OR target_id = $6)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type QueryAuditEventsParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Module     pgtype.Text `json:"module"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) QueryAuditEvents(ctx context.Context, arg QueryAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, queryAuditEvents,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Module,
		arg.TargetType,
		arg.TargetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.Module,
			&i.TargetType,
			&i.TargetID,
			&i.OperatorID,
			&i.Diff,
			&i.Source,
			&i.CreatedAt,
			&i.OperatorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
