// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bia.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBIAAssessments = `-- name: CountBIAAssessments :one
SELECT count(*) FROM bia_assessments WHERE tenant_id = $1
`

func (q *Queries) CountBIAAssessments(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBIAAssessments, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBIAByTier = `-- name: CountBIAByTier :many
SELECT tier, count(*) as count FROM bia_assessments
WHERE tenant_id = $1
GROUP BY tier
`

type CountBIAByTierRow struct {
	Tier  string `json:"tier"`
	Count int64  `json:"count"`
}

func (q *Queries) CountBIAByTier(ctx context.Context, tenantID uuid.UUID) ([]CountBIAByTierRow, error) {
	rows, err := q.db.Query(ctx, countBIAByTier, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBIAByTierRow{}
	for rows.Next() {
		var i CountBIAByTierRow
		if err := rows.Scan(&i.Tier, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBIAAssessment = `-- name: CreateBIAAssessment :one
INSERT INTO bia_assessments (
    tenant_id, system_name, system_code, owner, bia_score, tier,
    rto_hours, rpo_minutes, mtpd_hours,
    data_compliance, asset_compliance, audit_compliance,
    description, assessed_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, tenant_id, system_name, system_code, owner, bia_score, tier, rto_hours, rpo_minutes, mtpd_hours, data_compliance, asset_compliance, audit_compliance, description, last_assessed, assessed_by, created_at, updated_at
`

type CreateBIAAssessmentParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	SystemName      string         `json:"system_name"`
	SystemCode      string         `json:"system_code"`
	Owner           pgtype.Text    `json:"owner"`
	BiaScore        int32          `json:"bia_score"`
	Tier            string         `json:"tier"`
	RtoHours        pgtype.Numeric `json:"rto_hours"`
	RpoMinutes      pgtype.Numeric `json:"rpo_minutes"`
	MtpdHours       pgtype.Numeric `json:"mtpd_hours"`
	DataCompliance  pgtype.Bool    `json:"data_compliance"`
	AssetCompliance pgtype.Bool    `json:"asset_compliance"`
	AuditCompliance pgtype.Bool    `json:"audit_compliance"`
	Description     pgtype.Text    `json:"description"`
	AssessedBy      pgtype.UUID    `json:"assessed_by"`
}

func (q *Queries) CreateBIAAssessment(ctx context.Context, arg CreateBIAAssessmentParams) (BiaAssessment, error) {
	row := q.db.QueryRow(ctx, createBIAAssessment,
		arg.TenantID,
		arg.SystemName,
		arg.SystemCode,
		arg.Owner,
		arg.BiaScore,
		arg.Tier,
		arg.RtoHours,
		arg.RpoMinutes,
		arg.MtpdHours,
		arg.DataCompliance,
		arg.AssetCompliance,
		arg.AuditCompliance,
		arg.Description,
		arg.AssessedBy,
	)
	var i BiaAssessment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SystemName,
		&i.SystemCode,
		&i.Owner,
		&i.BiaScore,
		&i.Tier,
		&i.RtoHours,
		&i.RpoMinutes,
		&i.MtpdHours,
		&i.DataCompliance,
		&i.AssetCompliance,
		&i.AuditCompliance,
		&i.Description,
		&i.LastAssessed,
		&i.AssessedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBIADependency = `-- name: CreateBIADependency :one
INSERT INTO bia_dependencies (tenant_id, assessment_id, asset_id, dependency_type, criticality)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, tenant_id, assessment_id, asset_id, dependency_type, criticality, created_at
`

type CreateBIADependencyParams struct {
	TenantID       uuid.UUID   `json:"tenant_id"`
	AssessmentID   uuid.UUID   `json:"assessment_id"`
	AssetID        uuid.UUID   `json:"asset_id"`
	DependencyType string      `json:"dependency_type"`
	Criticality    pgtype.Text `json:"criticality"`
}

func (q *Queries) CreateBIADependency(ctx context.Context, arg CreateBIADependencyParams) (BiaDependency, error) {
	row := q.db.QueryRow(ctx, createBIADependency,
		arg.TenantID,
		arg.AssessmentID,
		arg.AssetID,
		arg.DependencyType,
		arg.Criticality,
	)
	var i BiaDependency
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentID,
		&i.AssetID,
		&i.DependencyType,
		&i.Criticality,
		&i.CreatedAt,
	)
	return i, err
}

const createBIAScoringRule = `-- name: CreateBIAScoringRule :one
INSERT INTO bia_scoring_rules (tenant_id, tier_name, tier_level, display_name, min_score, max_score, rto_threshold, rpo_threshold, description, color, icon)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, tenant_id, tier_name, tier_level, display_name, min_score, max_score, rto_threshold, rpo_threshold, description, color, icon, created_at
`

type CreateBIAScoringRuleParams struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	TierName     string         `json:"tier_name"`
	TierLevel    int32          `json:"tier_level"`
	DisplayName  string         `json:"display_name"`
	MinScore     int32          `json:"min_score"`
	MaxScore     int32          `json:"max_score"`
	RtoThreshold pgtype.Numeric `json:"rto_threshold"`
	RpoThreshold pgtype.Numeric `json:"rpo_threshold"`
	Description  pgtype.Text    `json:"description"`
	Color        pgtype.Text    `json:"color"`
	Icon         pgtype.Text    `json:"icon"`
}

func (q *Queries) CreateBIAScoringRule(ctx context.Context, arg CreateBIAScoringRuleParams) (BiaScoringRule, error) {
	row := q.db.QueryRow(ctx, createBIAScoringRule,
		arg.TenantID,
		arg.TierName,
		arg.TierLevel,
		arg.DisplayName,
		arg.MinScore,
		arg.MaxScore,
		arg.RtoThreshold,
		arg.RpoThreshold,
		arg.Description,
		arg.Color,
		arg.Icon,
	)
	var i BiaScoringRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TierName,
		&i.TierLevel,
		&i.DisplayName,
		&i.MinScore,
		&i.MaxScore,
		&i.RtoThreshold,
		&i.RpoThreshold,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBIAAssessment = `-- name: DeleteBIAAssessment :exec
DELETE FROM bia_assessments WHERE id = $1
`

func (q *Queries) DeleteBIAAssessment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBIAAssessment, id)
	return err
}

const deleteBIADependency = `-- name: DeleteBIADependency :exec
DELETE FROM bia_dependencies WHERE id = $1
`

func (q *Queries) DeleteBIADependency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBIADependency, id)
	return err
}

const getBIAAssessment = `-- name: GetBIAAssessment :one
SELECT id, tenant_id, system_name, system_code, owner, bia_score, tier, rto_hours, rpo_minutes, mtpd_hours, data_compliance, asset_compliance, audit_compliance, description, last_assessed, assessed_by, created_at, updated_at FROM bia_assessments WHERE id = $1
`

func (q *Queries) GetBIAAssessment(ctx context.Context, id uuid.UUID) (BiaAssessment, error) {
	row := q.db.QueryRow(ctx, getBIAAssessment, id)
	var i BiaAssessment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SystemName,
		&i.SystemCode,
		&i.Owner,
		&i.BiaScore,
		&i.Tier,
		&i.RtoHours,
		&i.RpoMinutes,
		&i.MtpdHours,
		&i.DataCompliance,
		&i.AssetCompliance,
		&i.AuditCompliance,
		&i.Description,
		&i.LastAssessed,
		&i.AssessedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBIAComplianceStats = `-- name: GetBIAComplianceStats :one
SELECT
    count(*) as total,
    count(*) FILTER (WHERE data_compliance = true) as data_compliant,
    count(*) FILTER (WHERE asset_compliance = true) as asset_compliant,
    count(*) FILTER (WHERE audit_compliance = true) as audit_compliant
FROM bia_assessments
WHERE tenant_id = $1
`

type GetBIAComplianceStatsRow struct {
	Total          int64 `json:"total"`
	DataCompliant  int64 `json:"data_compliant"`
	AssetCompliant int64 `json:"asset_compliant"`
	AuditCompliant int64 `json:"audit_compliant"`
}

func (q *Queries) GetBIAComplianceStats(ctx context.Context, tenantID uuid.UUID) (GetBIAComplianceStatsRow, error) {
	row := q.db.QueryRow(ctx, getBIAComplianceStats, tenantID)
	var i GetBIAComplianceStatsRow
	err := row.Scan(
		&i.Total,
		&i.DataCompliant,
		&i.AssetCompliant,
		&i.AuditCompliant,
	)
	return i, err
}

const getImpactedAssessments = `-- name: GetImpactedAssessments :many
SELECT ba.id, ba.tenant_id, ba.system_name, ba.system_code, ba.owner, ba.bia_score, ba.tier, ba.rto_hours, ba.rpo_minutes, ba.mtpd_hours, ba.data_compliance, ba.asset_compliance, ba.audit_compliance, ba.description, ba.last_assessed, ba.assessed_by, ba.created_at, ba.updated_at FROM bia_assessments ba
JOIN bia_dependencies bd ON bd.assessment_id = ba.id
WHERE bd.asset_id = $1
`

func (q *Queries) GetImpactedAssessments(ctx context.Context, assetID uuid.UUID) ([]BiaAssessment, error) {
	rows, err := q.db.Query(ctx, getImpactedAssessments, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BiaAssessment{}
	for rows.Next() {
		var i BiaAssessment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SystemName,
			&i.SystemCode,
			&i.Owner,
			&i.BiaScore,
			&i.Tier,
			&i.RtoHours,
			&i.RpoMinutes,
			&i.MtpdHours,
			&i.DataCompliance,
			&i.AssetCompliance,
			&i.AuditCompliance,
			&i.Description,
			&i.LastAssessed,
			&i.AssessedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBIAAssessments = `-- name: ListBIAAssessments :many
SELECT id, tenant_id, system_name, system_code, owner, bia_score, tier, rto_hours, rpo_minutes, mtpd_hours, data_compliance, asset_compliance, audit_compliance, description, last_assessed, assessed_by, created_at, updated_at FROM bia_assessments
WHERE tenant_id = $1
ORDER BY bia_score DESC
LIMIT $2 OFFSET $3
`

type ListBIAAssessmentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBIAAssessments(ctx context.Context, arg ListBIAAssessmentsParams) ([]BiaAssessment, error) {
	rows, err := q.db.Query(ctx, listBIAAssessments, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BiaAssessment{}
	for rows.Next() {
		var i BiaAssessment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SystemName,
			&i.SystemCode,
			&i.Owner,
			&i.BiaScore,
			&i.Tier,
			&i.RtoHours,
			&i.RpoMinutes,
			&i.MtpdHours,
			&i.DataCompliance,
			&i.AssetCompliance,
			&i.AuditCompliance,
			&i.Description,
			&i.LastAssessed,
			&i.AssessedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBIADependencies = `-- name: ListBIADependencies :many
SELECT id, tenant_id, assessment_id, asset_id, dependency_type, criticality, created_at FROM bia_dependencies
WHERE assessment_id = $1
`

func (q *Queries) ListBIADependencies(ctx context.Context, assessmentID uuid.UUID) ([]BiaDependency, error) {
	rows, err := q.db.Query(ctx, listBIADependencies, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BiaDependency{}
	for rows.Next() {
		var i BiaDependency
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentID,
			&i.AssetID,
			&i.DependencyType,
			&i.Criticality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBIAScoringRules = `-- name: ListBIAScoringRules :many
SELECT id, tenant_id, tier_name, tier_level, display_name, min_score, max_score, rto_threshold, rpo_threshold, description, color, icon, created_at FROM bia_scoring_rules
WHERE tenant_id = $1
ORDER BY tier_level
`

func (q *Queries) ListBIAScoringRules(ctx context.Context, tenantID uuid.UUID) ([]BiaScoringRule, error) {
	rows, err := q.db.Query(ctx, listBIAScoringRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BiaScoringRule{}
	for rows.Next() {
		var i BiaScoringRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TierName,
			&i.TierLevel,
			&i.DisplayName,
			&i.MinScore,
			&i.MaxScore,
			&i.RtoThreshold,
			&i.RpoThreshold,
			&i.Description,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const propagateBIALevelByAssessment = `-- name: PropagateBIALevelByAssessment :exec
UPDATE assets SET
    bia_level = sub.max_tier,
    updated_at = now()
FROM (
    SELECT bd.asset_id,
        CASE
            WHEN 'critical' = ANY(array_agg(ba.tier)) THEN 'critical'
            WHEN 'important' = ANY(array_agg(ba.tier)) THEN 'important'
            WHEN 'normal' = ANY(array_agg(ba.tier)) THEN 'normal'
            ELSE 'minor'
        END as max_tier
    FROM bia_dependencies bd
    JOIN bia_assessments ba ON ba.id = bd.assessment_id
    WHERE bd.asset_id IN (
        SELECT bd2.asset_id FROM bia_dependencies bd2 WHERE bd2.assessment_id = $1
    )
    GROUP BY bd.asset_id
) sub
WHERE assets.id = sub.asset_id
`

func (q *Queries) PropagateBIALevelByAssessment(ctx context.Context, assessmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, propagateBIALevelByAssessment, assessmentID)
	return err
}

const updateBIAAssessment = `-- name: UpdateBIAAssessment :one
UPDATE bia_assessments SET
    system_name      = COALESCE($1, system_name),
    owner            = COALESCE($2, owner),
    bia_score        = COALESCE($3, bia_score),
    tier             = COALESCE($4, tier),
    rto_hours        = COALESCE($5, rto_hours),
    rpo_minutes      = COALESCE($6, rpo_minutes),
    mtpd_hours       = COALESCE($7, mtpd_hours),
    data_compliance  = COALESCE($8, data_compliance),
    asset_compliance = COALESCE($9, asset_compliance),
    audit_compliance = COALESCE($10, audit_compliance),
    description      = COALESCE($11, description),
    last_assessed    = now(),
    updated_at       = now()
WHERE id = $12
RETURNING id, tenant_id, system_name, system_code, owner, bia_score, tier, rto_hours, rpo_minutes, mtpd_hours, data_compliance, asset_compliance, audit_compliance, description, last_assessed, assessed_by, created_at, updated_at
`

type UpdateBIAAssessmentParams struct {
	SystemName      pgtype.Text    `json:"system_name"`
	Owner           pgtype.Text    `json:"owner"`
	BiaScore        pgtype.Int4    `json:"bia_score"`
	Tier            pgtype.Text    `json:"tier"`
	RtoHours        pgtype.Numeric `json:"rto_hours"`
	RpoMinutes      pgtype.Numeric `json:"rpo_minutes"`
	MtpdHours       pgtype.Numeric `json:"mtpd_hours"`
	DataCompliance  pgtype.Bool    `json:"data_compliance"`
	AssetCompliance pgtype.Bool    `json:"asset_compliance"`
	AuditCompliance pgtype.Bool    `json:"audit_compliance"`
	Description     pgtype.Text    `json:"description"`
	ID              uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBIAAssessment(ctx context.Context, arg UpdateBIAAssessmentParams) (BiaAssessment, error) {
	row := q.db.QueryRow(ctx, updateBIAAssessment,
		arg.SystemName,
		arg.Owner,
		arg.BiaScore,
		arg.Tier,
		arg.RtoHours,
		arg.RpoMinutes,
		arg.MtpdHours,
		arg.DataCompliance,
		arg.AssetCompliance,
		arg.AuditCompliance,
		arg.Description,
		arg.ID,
	)
	var i BiaAssessment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SystemName,
		&i.SystemCode,
		&i.Owner,
		&i.BiaScore,
		&i.Tier,
		&i.RtoHours,
		&i.RpoMinutes,
		&i.MtpdHours,
		&i.DataCompliance,
		&i.AssetCompliance,
		&i.AuditCompliance,
		&i.Description,
		&i.LastAssessed,
		&i.AssessedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBIAScoringRule = `-- name: UpdateBIAScoringRule :one
UPDATE bia_scoring_rules SET
    display_name   = COALESCE($1, display_name),
    min_score      = COALESCE($2, min_score),
    max_score      = COALESCE($3, max_score),
    rto_threshold  = COALESCE($4, rto_threshold),
    rpo_threshold  = COALESCE($5, rpo_threshold),
    description    = COALESCE($6, description),
    color          = COALESCE($7, color)
WHERE id = $8
RETURNING id, tenant_id, tier_name, tier_level, display_name, min_score, max_score, rto_threshold, rpo_threshold, description, color, icon, created_at
`

type UpdateBIAScoringRuleParams struct {
	DisplayName  pgtype.Text    `json:"display_name"`
	MinScore     pgtype.Int4    `json:"min_score"`
	MaxScore     pgtype.Int4    `json:"max_score"`
	RtoThreshold pgtype.Numeric `json:"rto_threshold"`
	RpoThreshold pgtype.Numeric `json:"rpo_threshold"`
	Description  pgtype.Text    `json:"description"`
	Color        pgtype.Text    `json:"color"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBIAScoringRule(ctx context.Context, arg UpdateBIAScoringRuleParams) (BiaScoringRule, error) {
	row := q.db.QueryRow(ctx, updateBIAScoringRule,
		arg.DisplayName,
		arg.MinScore,
		arg.MaxScore,
		arg.RtoThreshold,
		arg.RpoThreshold,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	var i BiaScoringRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TierName,
		&i.TierLevel,
		&i.DisplayName,
		&i.MinScore,
		&i.MaxScore,
		&i.RtoThreshold,
		&i.RpoThreshold,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}
