// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveDiscoveredAsset = `-- name: ApproveDiscoveredAsset :one
UPDATE discovered_assets SET status = 'approved', reviewed_by = $2, reviewed_at = now()
WHERE id = $1 RETURNING id, tenant_id, source, external_id, hostname, ip_address, raw_data, status, matched_asset_id, diff_details, discovered_at, reviewed_by, reviewed_at
`

type ApproveDiscoveredAssetParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ApproveDiscoveredAsset(ctx context.Context, arg ApproveDiscoveredAssetParams) (DiscoveredAsset, error) {
	row := q.db.QueryRow(ctx, approveDiscoveredAsset, arg.ID, arg.ReviewedBy)
	var i DiscoveredAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ExternalID,
		&i.Hostname,
		&i.IpAddress,
		&i.RawData,
		&i.Status,
		&i.MatchedAssetID,
		&i.DiffDetails,
		&i.DiscoveredAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
	)
	return i, err
}

const countDiscoveredAssets = `-- name: CountDiscoveredAssets :one
SELECT count(*) FROM discovered_assets
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR status = $2)
`

type CountDiscoveredAssetsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CountDiscoveredAssets(ctx context.Context, arg CountDiscoveredAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDiscoveredAssets, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDiscoveredAsset = `-- name: CreateDiscoveredAsset :one
INSERT INTO discovered_assets (tenant_id, source, external_id, hostname, ip_address, raw_data, status, matched_asset_id, diff_details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, source, external_id, hostname, ip_address, raw_data, status, matched_asset_id, diff_details, discovered_at, reviewed_by, reviewed_at
`

type CreateDiscoveredAssetParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	Source         string          `json:"source"`
	ExternalID     pgtype.Text     `json:"external_id"`
	Hostname       pgtype.Text     `json:"hostname"`
	IpAddress      pgtype.Text     `json:"ip_address"`
	RawData        json.RawMessage `json:"raw_data"`
	Status         string          `json:"status"`
	MatchedAssetID pgtype.UUID     `json:"matched_asset_id"`
	DiffDetails    []byte          `json:"diff_details"`
}

func (q *Queries) CreateDiscoveredAsset(ctx context.Context, arg CreateDiscoveredAssetParams) (DiscoveredAsset, error) {
	row := q.db.QueryRow(ctx, createDiscoveredAsset,
		arg.TenantID,
		arg.Source,
		arg.ExternalID,
		arg.Hostname,
		arg.IpAddress,
		arg.RawData,
		arg.Status,
		arg.MatchedAssetID,
		arg.DiffDetails,
	)
	var i DiscoveredAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ExternalID,
		&i.Hostname,
		&i.IpAddress,
		&i.RawData,
		&i.Status,
		&i.MatchedAssetID,
		&i.DiffDetails,
		&i.DiscoveredAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
	)
	return i, err
}

const findAssetByIP = `-- name: FindAssetByIP :one
SELECT id, tenant_id, asset_tag, property_number, control_number, name, type, sub_type, status, bia_level, location_id, rack_id, vendor, model, serial_number, ip_address, attributes, tags, created_at, updated_at FROM assets WHERE tenant_id = $1 AND ip_address = $2 LIMIT 1
`

type FindAssetByIPParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) FindAssetByIP(ctx context.Context, arg FindAssetByIPParams) (Asset, error) {
	row := q.db.QueryRow(ctx, findAssetByIP, arg.TenantID, arg.IpAddress)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetTag,
		&i.PropertyNumber,
		&i.ControlNumber,
		&i.Name,
		&i.Type,
		&i.SubType,
		&i.Status,
		&i.BiaLevel,
		&i.LocationID,
		&i.RackID,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.IpAddress,
		&i.Attributes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscoveredAsset = `-- name: GetDiscoveredAsset :one
SELECT id, tenant_id, source, external_id, hostname, ip_address, raw_data, status, matched_asset_id, diff_details, discovered_at, reviewed_by, reviewed_at FROM discovered_assets WHERE id = $1 AND tenant_id = $2
`

type GetDiscoveredAssetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDiscoveredAsset(ctx context.Context, arg GetDiscoveredAssetParams) (DiscoveredAsset, error) {
	row := q.db.QueryRow(ctx, getDiscoveredAsset, arg.ID, arg.TenantID)
	var i DiscoveredAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ExternalID,
		&i.Hostname,
		&i.IpAddress,
		&i.RawData,
		&i.Status,
		&i.MatchedAssetID,
		&i.DiffDetails,
		&i.DiscoveredAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
	)
	return i, err
}

const getDiscoveryStats = `-- name: GetDiscoveryStats :one
SELECT
    count(*) as total,
    count(*) FILTER (WHERE status = 'pending') as pending,
    count(*) FILTER (WHERE status = 'conflict') as conflict,
    count(*) FILTER (WHERE status = 'approved') as approved,
    count(*) FILTER (WHERE status = 'ignored') as ignored,
    count(*) FILTER (WHERE matched_asset_id IS NOT NULL) as matched
FROM discovered_assets
WHERE tenant_id = $1
  AND discovered_at > now() - interval '24 hours'
`

type GetDiscoveryStatsRow struct {
	Total    int64 `json:"total"`
	Pending  int64 `json:"pending"`
	Conflict int64 `json:"conflict"`
	Approved int64 `json:"approved"`
	Ignored  int64 `json:"ignored"`
	Matched  int64 `json:"matched"`
}

func (q *Queries) GetDiscoveryStats(ctx context.Context, tenantID uuid.UUID) (GetDiscoveryStatsRow, error) {
	row := q.db.QueryRow(ctx, getDiscoveryStats, tenantID)
	var i GetDiscoveryStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Conflict,
		&i.Approved,
		&i.Ignored,
		&i.Matched,
	)
	return i, err
}

const ignoreDiscoveredAsset = `-- name: IgnoreDiscoveredAsset :one
UPDATE discovered_assets SET status = 'ignored', reviewed_by = $2, reviewed_at = now()
WHERE id = $1 RETURNING id, tenant_id, source, external_id, hostname, ip_address, raw_data, status, matched_asset_id, diff_details, discovered_at, reviewed_by, reviewed_at
`

type IgnoreDiscoveredAssetParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) IgnoreDiscoveredAsset(ctx context.Context, arg IgnoreDiscoveredAssetParams) (DiscoveredAsset, error) {
	row := q.db.QueryRow(ctx, ignoreDiscoveredAsset, arg.ID, arg.ReviewedBy)
	var i DiscoveredAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ExternalID,
		&i.Hostname,
		&i.IpAddress,
		&i.RawData,
		&i.Status,
		&i.MatchedAssetID,
		&i.DiffDetails,
		&i.DiscoveredAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
	)
	return i, err
}

const listDiscoveredAssets = `-- name: ListDiscoveredAssets :many
SELECT id, tenant_id, source, external_id, hostname, ip_address, raw_data, status, matched_asset_id, diff_details, discovered_at, reviewed_by, reviewed_at FROM discovered_assets
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR status = $4)
ORDER BY discovered_at DESC
LIMIT $2 OFFSET $3
`

type ListDiscoveredAssetsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) ListDiscoveredAssets(ctx context.Context, arg ListDiscoveredAssetsParams) ([]DiscoveredAsset, error) {
	rows, err := q.db.Query(ctx, listDiscoveredAssets,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoveredAsset{}
	for rows.Next() {
		var i DiscoveredAsset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.ExternalID,
			&i.Hostname,
			&i.IpAddress,
			&i.RawData,
			&i.Status,
			&i.MatchedAssetID,
			&i.DiffDetails,
			&i.DiscoveredAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
