// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidents = `-- name: CountIncidents :one
SELECT count(*) FROM incidents
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::varchar IS NULL OR severity = $3)
`

type CountIncidentsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Severity pgtype.Text `json:"severity"`
}

func (q *Queries) CountIncidents(ctx context.Context, arg CountIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents, arg.TenantID, arg.Status, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (tenant_id, title, status, severity, started_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at
`

type CreateIncidentParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	Severity  string    `json:"severity"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.TenantID,
		arg.Title,
		arg.Status,
		arg.Severity,
		arg.StartedAt,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, tenant_id, title, status, severity, started_at, resolved_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, tenant_id, title, status, severity, started_at, resolved_at FROM incidents
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::varchar IS NULL OR severity = $5)
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListIncidentsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
	Severity pgtype.Text `json:"severity"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Severity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents SET
    title       = COALESCE($1, title),
    status      = COALESCE($2, status),
    severity    = COALESCE($3, severity),
    resolved_at = COALESCE($4, resolved_at)
WHERE id = $5
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at
`

type UpdateIncidentParams struct {
	Title      pgtype.Text        `json:"title"`
	Status     pgtype.Text        `json:"status"`
	Severity   pgtype.Text        `json:"severity"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Title,
		arg.Status,
		arg.Severity,
		arg.ResolvedAt,
		arg.ID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return i, err
}
