// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeIncident = `-- name: AcknowledgeIncident :one
UPDATE incidents SET
    status          = 'acknowledged',
    acknowledged_at = now(),
    acknowledged_by = $1
WHERE id = $2
  AND tenant_id = $3
  AND status = 'open'
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type AcknowledgeIncidentParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

// Status change: open → acknowledged. We apply the transition in SQL with
// a WHERE on current status so concurrent acks can't double-stamp the
// acknowledged_at/by. The caller receives 0 rows if the guard fails.
func (q *Queries) AcknowledgeIncident(ctx context.Context, arg AcknowledgeIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, acknowledgeIncident, arg.UserID, arg.ID, arg.TenantID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const closeIncident = `-- name: CloseIncident :one
UPDATE incidents SET status = 'closed'
WHERE id = $1
  AND tenant_id = $2
  AND status = 'resolved'
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type CloseIncidentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// resolved → closed. Post-mortem lock: once closed, no transitions out.
func (q *Queries) CloseIncident(ctx context.Context, arg CloseIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, closeIncident, arg.ID, arg.TenantID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const countIncidents = `-- name: CountIncidents :one
SELECT count(*) FROM incidents
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::varchar IS NULL OR severity = $3)
`

type CountIncidentsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Severity pgtype.Text `json:"severity"`
}

func (q *Queries) CountIncidents(ctx context.Context, arg CountIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents, arg.TenantID, arg.Status, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    tenant_id, title, status, severity, started_at,
    description, priority, assignee_user_id, affected_asset_id,
    affected_service_id, impact
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type CreateIncidentParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	Title             string      `json:"title"`
	Status            string      `json:"status"`
	Severity          string      `json:"severity"`
	StartedAt         time.Time   `json:"started_at"`
	Description       pgtype.Text `json:"description"`
	Priority          pgtype.Text `json:"priority"`
	AssigneeUserID    pgtype.UUID `json:"assignee_user_id"`
	AffectedAssetID   pgtype.UUID `json:"affected_asset_id"`
	AffectedServiceID pgtype.UUID `json:"affected_service_id"`
	Impact            pgtype.Text `json:"impact"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.TenantID,
		arg.Title,
		arg.Status,
		arg.Severity,
		arg.StartedAt,
		arg.Description,
		arg.Priority,
		arg.AssigneeUserID,
		arg.AffectedAssetID,
		arg.AffectedServiceID,
		arg.Impact,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncidentComment = `-- name: CreateIncidentComment :one
INSERT INTO incident_comments (tenant_id, incident_id, author_id, kind, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, incident_id, author_id, kind, body, created_at
`

type CreateIncidentCommentParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	IncidentID uuid.UUID   `json:"incident_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Kind       string      `json:"kind"`
	Body       string      `json:"body"`
}

func (q *Queries) CreateIncidentComment(ctx context.Context, arg CreateIncidentCommentParams) (IncidentComment, error) {
	row := q.db.QueryRow(ctx, createIncidentComment,
		arg.TenantID,
		arg.IncidentID,
		arg.AuthorID,
		arg.Kind,
		arg.Body,
	)
	var i IncidentComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IncidentID,
		&i.AuthorID,
		&i.Kind,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at FROM incidents WHERE id = $1 AND tenant_id = $2
`

type GetIncidentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetIncident(ctx context.Context, arg GetIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, arg.ID, arg.TenantID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertEventsByIncident = `-- name: ListAlertEventsByIncident :many
SELECT ae.id, ae.tenant_id, ae.rule_id, ae.asset_id, ae.status,
       ae.severity, ae.message, ae.trigger_value, ae.fired_at,
       ae.acked_at, ae.resolved_at, ae.sync_version
FROM alert_events ae
JOIN incidents i
  ON i.id = $1::uuid
 AND i.tenant_id = $2::uuid
WHERE ae.tenant_id = $2::uuid
  AND ae.fired_at >= i.started_at
  AND ae.fired_at <= COALESCE(i.resolved_at, now())
ORDER BY ae.fired_at DESC
LIMIT 100
`

type ListAlertEventsByIncidentParams struct {
	IncidentID uuid.UUID `json:"incident_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

type ListAlertEventsByIncidentRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	RuleID       pgtype.UUID        `json:"rule_id"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	Status       string             `json:"status"`
	Severity     string             `json:"severity"`
	Message      pgtype.Text        `json:"message"`
	TriggerValue pgtype.Numeric     `json:"trigger_value"`
	FiredAt      time.Time          `json:"fired_at"`
	AckedAt      pgtype.Timestamptz `json:"acked_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	SyncVersion  int64              `json:"sync_version"`
}

// Returns alert_events considered "related" to an incident for RCA context.
// There is no alert_events.incident_id FK, so the link is derived by:
//  1. Same tenant (defence-in-depth; tenant_id is passed explicitly).
//  2. The alert fired during the incident's active window: between the
//     incident's started_at and COALESCE(resolved_at, now()).
//
// This is the most conservative temporal association we can make without a
// dedicated link table. Results are ordered newest-first and capped at 100
// rows to bound the payload handed to the AI provider.
func (q *Queries) ListAlertEventsByIncident(ctx context.Context, arg ListAlertEventsByIncidentParams) ([]ListAlertEventsByIncidentRow, error) {
	rows, err := q.db.Query(ctx, listAlertEventsByIncident, arg.IncidentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertEventsByIncidentRow{}
	for rows.Next() {
		var i ListAlertEventsByIncidentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuleID,
			&i.AssetID,
			&i.Status,
			&i.Severity,
			&i.Message,
			&i.TriggerValue,
			&i.FiredAt,
			&i.AckedAt,
			&i.ResolvedAt,
			&i.SyncVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsForIncident = `-- name: ListAssetsForIncident :many
SELECT DISTINCT a.id, a.tenant_id, a.asset_tag, a.property_number,
       a.control_number, a.name, a.type, a.sub_type, a.status, a.bia_level,
       a.location_id, a.rack_id, a.vendor, a.model, a.serial_number,
       a.attributes, a.tags, a.created_at, a.updated_at, a.ip_address,
       a.deleted_at, a.sync_version, a.bmc_ip, a.bmc_type, a.bmc_firmware,
       a.purchase_date, a.purchase_cost, a.warranty_start, a.warranty_end,
       a.warranty_vendor, a.warranty_contract, a.expected_lifespan_months,
       a.eol_date, a.access_count_24h, a.last_accessed_at, a.owner_team
FROM assets a
JOIN alert_events ae ON ae.asset_id = a.id
JOIN incidents i
  ON i.id = $1::uuid
 AND i.tenant_id = $2::uuid
WHERE a.tenant_id = $2::uuid
  AND ae.tenant_id = $2::uuid
  AND a.deleted_at IS NULL
  AND ae.fired_at >= i.started_at
  AND ae.fired_at <= COALESCE(i.resolved_at, now())
ORDER BY a.name
LIMIT 100
`

type ListAssetsForIncidentParams struct {
	IncidentID uuid.UUID `json:"incident_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

// Returns DISTINCT assets referenced by alert_events related to the incident
// (same temporal window as ListAlertEventsByIncident). Soft-deleted assets
// are excluded. Tenant scope is enforced on BOTH alert_events and assets
// and on the incidents row (defence-in-depth).
//
// Explicit column list mirrors dbgen.Asset so sqlc returns []Asset rather
// than a bespoke row type. When the assets table gains new columns (e.g.
// 000058 added access_count_24h and last_accessed_at; 000060 added
// owner_team), add them here too or the row shape diverges and callers
// break to compile.
func (q *Queries) ListAssetsForIncident(ctx context.Context, arg ListAssetsForIncidentParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsForIncident, arg.IncidentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetTag,
			&i.PropertyNumber,
			&i.ControlNumber,
			&i.Name,
			&i.Type,
			&i.SubType,
			&i.Status,
			&i.BiaLevel,
			&i.LocationID,
			&i.RackID,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.Attributes,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.DeletedAt,
			&i.SyncVersion,
			&i.BmcIp,
			&i.BmcType,
			&i.BmcFirmware,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyStart,
			&i.WarrantyEnd,
			&i.WarrantyVendor,
			&i.WarrantyContract,
			&i.ExpectedLifespanMonths,
			&i.EolDate,
			&i.AccessCount24h,
			&i.LastAccessedAt,
			&i.OwnerTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentComments = `-- name: ListIncidentComments :many
SELECT c.id, c.tenant_id, c.incident_id, c.author_id, c.kind, c.body, c.created_at,
       u.username AS author_username
FROM incident_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.incident_id = $1
  AND c.tenant_id = $2
ORDER BY c.created_at ASC
`

type ListIncidentCommentsParams struct {
	IncidentID uuid.UUID `json:"incident_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

type ListIncidentCommentsRow struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	IncidentID     uuid.UUID   `json:"incident_id"`
	AuthorID       pgtype.UUID `json:"author_id"`
	Kind           string      `json:"kind"`
	Body           string      `json:"body"`
	CreatedAt      time.Time   `json:"created_at"`
	AuthorUsername pgtype.Text `json:"author_username"`
}

// Timeline view: newest-first by default would break visual reading order,
// so we sort ascending. UI can reverse client-side if needed.
func (q *Queries) ListIncidentComments(ctx context.Context, arg ListIncidentCommentsParams) ([]ListIncidentCommentsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentComments, arg.IncidentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentCommentsRow{}
	for rows.Next() {
		var i ListIncidentCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IncidentID,
			&i.AuthorID,
			&i.Kind,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at FROM incidents
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::varchar IS NULL OR severity = $5)
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListIncidentsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
	Severity pgtype.Text `json:"severity"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Severity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Description,
			&i.Priority,
			&i.AssigneeUserID,
			&i.AffectedAssetID,
			&i.AffectedServiceID,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.ResolvedBy,
			&i.RootCause,
			&i.Impact,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenIncident = `-- name: ReopenIncident :one
UPDATE incidents SET
    status      = 'open',
    resolved_at = NULL,
    resolved_by = NULL
WHERE id = $1
  AND tenant_id = $2
  AND status = 'resolved'
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type ReopenIncidentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// resolved → open. Investigation surfaced a regression — flip back to open
// and clear the resolution fields so downstream reports don't show a ghost
// 'resolved_at' on an active incident. 'closed' is immutable.
func (q *Queries) ReopenIncident(ctx context.Context, arg ReopenIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, reopenIncident, arg.ID, arg.TenantID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveIncident = `-- name: ResolveIncident :one
UPDATE incidents SET
    status      = 'resolved',
    resolved_at = now(),
    resolved_by = $1,
    root_cause  = COALESCE($2, root_cause)
WHERE id = $3
  AND tenant_id = $4
  AND status <> 'closed'
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type ResolveIncidentParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RootCause pgtype.Text `json:"root_cause"`
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
}

// * → resolved. Allowed from any non-closed status because an operator may
// resolve a still-open incident (e.g. false alarm) or a mid-investigation
// one. Blocked once status='closed' so post-mortem is immutable.
func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, resolveIncident,
		arg.UserID,
		arg.RootCause,
		arg.ID,
		arg.TenantID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const startInvestigatingIncident = `-- name: StartInvestigatingIncident :one
UPDATE incidents SET
    status = 'investigating'
WHERE id = $1
  AND tenant_id = $2
  AND status = 'acknowledged'
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type StartInvestigatingIncidentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// acknowledged → investigating. Same optimistic guard as acknowledge.
func (q *Queries) StartInvestigatingIncident(ctx context.Context, arg StartInvestigatingIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, startInvestigatingIncident, arg.ID, arg.TenantID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents SET
    title               = COALESCE($1, title),
    severity            = COALESCE($2, severity),
    priority            = COALESCE($3, priority),
    description         = COALESCE($4, description),
    impact              = COALESCE($5, impact),
    assignee_user_id    = COALESCE($6, assignee_user_id),
    affected_asset_id   = COALESCE($7, affected_asset_id),
    affected_service_id = COALESCE($8, affected_service_id)
WHERE id = $9 AND tenant_id = $10
RETURNING id, tenant_id, title, status, severity, started_at, resolved_at, description, priority, assignee_user_id, affected_asset_id, affected_service_id, acknowledged_at, acknowledged_by, resolved_by, root_cause, impact, updated_at
`

type UpdateIncidentParams struct {
	Title             pgtype.Text `json:"title"`
	Severity          pgtype.Text `json:"severity"`
	Priority          pgtype.Text `json:"priority"`
	Description       pgtype.Text `json:"description"`
	Impact            pgtype.Text `json:"impact"`
	AssigneeUserID    pgtype.UUID `json:"assignee_user_id"`
	AffectedAssetID   pgtype.UUID `json:"affected_asset_id"`
	AffectedServiceID pgtype.UUID `json:"affected_service_id"`
	ID                uuid.UUID   `json:"id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
}

// Partial update. Title/severity/priority/description/assignee/links/impact
// are free to change at any time; *status* changes route through dedicated
// queries below so the state-machine guard lives in one place.
func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Title,
		arg.Severity,
		arg.Priority,
		arg.Description,
		arg.Impact,
		arg.AssigneeUserID,
		arg.AffectedAssetID,
		arg.AffectedServiceID,
		arg.ID,
		arg.TenantID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Description,
		&i.Priority,
		&i.AssigneeUserID,
		&i.AffectedAssetID,
		&i.AffectedServiceID,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.RootCause,
		&i.Impact,
		&i.UpdatedAt,
	)
	return i, err
}
