// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdapter = `-- name: CreateAdapter :one
INSERT INTO integration_adapters (tenant_id, name, type, direction, endpoint, config, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, tenant_id, name, type, direction, endpoint, config, enabled, created_at
`

type CreateAdapterParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Direction string      `json:"direction"`
	Endpoint  pgtype.Text `json:"endpoint"`
	Config    []byte      `json:"config"`
	Enabled   pgtype.Bool `json:"enabled"`
}

func (q *Queries) CreateAdapter(ctx context.Context, arg CreateAdapterParams) (IntegrationAdapter, error) {
	row := q.db.QueryRow(ctx, createAdapter,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Direction,
		arg.Endpoint,
		arg.Config,
		arg.Enabled,
	)
	var i IntegrationAdapter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Endpoint,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createDelivery = `-- name: CreateDelivery :exec
INSERT INTO webhook_deliveries (subscription_id, event_type, payload, status_code, response_body)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDeliveryParams struct {
	SubscriptionID uuid.UUID       `json:"subscription_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	StatusCode     pgtype.Int4     `json:"status_code"`
	ResponseBody   pgtype.Text     `json:"response_body"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.Exec(ctx, createDelivery,
		arg.SubscriptionID,
		arg.EventType,
		arg.Payload,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhook_subscriptions (tenant_id, name, url, secret, events, enabled)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, tenant_id, name, url, secret, events, enabled, created_at
`

type CreateWebhookParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Url      string      `json:"url"`
	Secret   pgtype.Text `json:"secret"`
	Events   []string    `json:"events"`
	Enabled  pgtype.Bool `json:"enabled"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Enabled,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAdapters = `-- name: ListAdapters :many
SELECT id, tenant_id, name, type, direction, endpoint, config, enabled, created_at FROM integration_adapters WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListAdapters(ctx context.Context, tenantID uuid.UUID) ([]IntegrationAdapter, error) {
	rows, err := q.db.Query(ctx, listAdapters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationAdapter{}
	for rows.Next() {
		var i IntegrationAdapter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Direction,
			&i.Endpoint,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, subscription_id, event_type, payload, status_code, response_body, delivered_at FROM webhook_deliveries WHERE subscription_id = $1 ORDER BY delivered_at DESC LIMIT $2
`

type ListDeliveriesParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.SubscriptionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.StatusCode,
			&i.ResponseBody,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, tenant_id, name, url, secret, events, enabled, created_at FROM webhook_subscriptions WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListWebhooks(ctx context.Context, tenantID uuid.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhooks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByEvent = `-- name: ListWebhooksByEvent :many
SELECT id, tenant_id, name, url, secret, events, enabled, created_at FROM webhook_subscriptions
WHERE enabled = true
  AND $1::text = ANY(events)
`

func (q *Queries) ListWebhooksByEvent(ctx context.Context, dollar_1 string) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhooksByEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
