// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdapter = `-- name: CreateAdapter :one
INSERT INTO integration_adapters (tenant_id, name, type, direction, endpoint, config, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, tenant_id, name, type, direction, endpoint, config, enabled, created_at, consecutive_failures, last_failure_at, last_failure_reason, next_attempt_at
`

type CreateAdapterParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Direction string      `json:"direction"`
	Endpoint  pgtype.Text `json:"endpoint"`
	Config    []byte      `json:"config"`
	Enabled   pgtype.Bool `json:"enabled"`
}

func (q *Queries) CreateAdapter(ctx context.Context, arg CreateAdapterParams) (IntegrationAdapter, error) {
	row := q.db.QueryRow(ctx, createAdapter,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Direction,
		arg.Endpoint,
		arg.Config,
		arg.Enabled,
	)
	var i IntegrationAdapter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Endpoint,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.ConsecutiveFailures,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.NextAttemptAt,
	)
	return i, err
}

const createDelivery = `-- name: CreateDelivery :exec
INSERT INTO webhook_deliveries (subscription_id, event_type, payload, status_code, response_body)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDeliveryParams struct {
	SubscriptionID uuid.UUID       `json:"subscription_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	StatusCode     pgtype.Int4     `json:"status_code"`
	ResponseBody   pgtype.Text     `json:"response_body"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.Exec(ctx, createDelivery,
		arg.SubscriptionID,
		arg.EventType,
		arg.Payload,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhook_subscriptions (tenant_id, name, url, secret, events, enabled)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, tenant_id, name, url, secret, events, enabled, created_at, filter_bia
`

type CreateWebhookParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Url      string      `json:"url"`
	Secret   pgtype.Text `json:"secret"`
	Events   []string    `json:"events"`
	Enabled  pgtype.Bool `json:"enabled"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Enabled,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.FilterBia,
	)
	return i, err
}

const disableAdapter = `-- name: DisableAdapter :exec
UPDATE integration_adapters
SET enabled = false
WHERE id = $1 AND tenant_id = $2
`

type DisableAdapterParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Auto-disable after threshold reached. Separate from RecordAdapterFailure
// so the workflow can emit an audit event atomically with the decision.
func (q *Queries) DisableAdapter(ctx context.Context, arg DisableAdapterParams) error {
	_, err := q.db.Exec(ctx, disableAdapter, arg.ID, arg.TenantID)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, tenant_id, name, url, secret, events, enabled, created_at, filter_bia FROM webhook_subscriptions WHERE id = $1 AND tenant_id = $2
`

type GetWebhookByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetWebhookByID(ctx context.Context, arg GetWebhookByIDParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, arg.ID, arg.TenantID)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.FilterBia,
	)
	return i, err
}

const listAdapters = `-- name: ListAdapters :many
SELECT id, tenant_id, name, type, direction, endpoint, config, enabled, created_at, consecutive_failures, last_failure_at, last_failure_reason, next_attempt_at FROM integration_adapters WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListAdapters(ctx context.Context, tenantID uuid.UUID) ([]IntegrationAdapter, error) {
	rows, err := q.db.Query(ctx, listAdapters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationAdapter{}
	for rows.Next() {
		var i IntegrationAdapter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Direction,
			&i.Endpoint,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.ConsecutiveFailures,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, subscription_id, event_type, payload, status_code, response_body, delivered_at FROM webhook_deliveries WHERE subscription_id = $1 ORDER BY delivered_at DESC LIMIT $2
`

type ListDeliveriesParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.SubscriptionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.StatusCode,
			&i.ResponseBody,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuePullAdapters = `-- name: ListDuePullAdapters :many
SELECT id, tenant_id, name, type, endpoint, config, consecutive_failures
FROM integration_adapters
WHERE direction = 'inbound'
  AND enabled = true
  AND (next_attempt_at IS NULL OR next_attempt_at <= now())
`

type ListDuePullAdaptersRow struct {
	ID                  uuid.UUID   `json:"id"`
	TenantID            uuid.UUID   `json:"tenant_id"`
	Name                string      `json:"name"`
	Type                string      `json:"type"`
	Endpoint            pgtype.Text `json:"endpoint"`
	Config              []byte      `json:"config"`
	ConsecutiveFailures int32       `json:"consecutive_failures"`
}

// Returns inbound adapters eligible to be polled right now:
// enabled, and either never-failed (next_attempt_at IS NULL) or past their
// backoff window. Used by the metrics puller; backoff is enforced in SQL
// so restarts cannot silently re-poll a broken adapter.
func (q *Queries) ListDuePullAdapters(ctx context.Context) ([]ListDuePullAdaptersRow, error) {
	rows, err := q.db.Query(ctx, listDuePullAdapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuePullAdaptersRow{}
	for rows.Next() {
		var i ListDuePullAdaptersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Endpoint,
			&i.Config,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, tenant_id, name, url, secret, events, enabled, created_at, filter_bia FROM webhook_subscriptions WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListWebhooks(ctx context.Context, tenantID uuid.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhooks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.FilterBia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByEvent = `-- name: ListWebhooksByEvent :many
SELECT id, tenant_id, name, url, secret, events, enabled, created_at, filter_bia FROM webhook_subscriptions
WHERE tenant_id = $1
  AND enabled = true
  AND $2::text = ANY(events)
`

type ListWebhooksByEventParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) ListWebhooksByEvent(ctx context.Context, arg ListWebhooksByEventParams) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhooksByEvent, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.FilterBia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdapterFailure = `-- name: RecordAdapterFailure :one
UPDATE integration_adapters
SET consecutive_failures = consecutive_failures + 1,
    last_failure_at      = now(),
    last_failure_reason  = $3,
    next_attempt_at      = now() + CASE
        WHEN consecutive_failures + 1 = 1 THEN INTERVAL '30 seconds'
        WHEN consecutive_failures + 1 = 2 THEN INTERVAL '2 minutes'
        WHEN consecutive_failures + 1 = 3 THEN INTERVAL '10 minutes'
        ELSE INTERVAL '30 minutes'
    END
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, consecutive_failures, next_attempt_at
`

type RecordAdapterFailureParams struct {
	ID                uuid.UUID   `json:"id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
	LastFailureReason pgtype.Text `json:"last_failure_reason"`
}

type RecordAdapterFailureRow struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Name                string             `json:"name"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
}

// Atomically increments consecutive_failures, stamps the reason (truncated
// to 500 chars by the caller via $3), and computes next_attempt_at using
// the exponential backoff schedule (30s / 2m / 10m / 30m cap).
// Returns the post-update row so the workflow layer can decide whether to
// auto-disable without a follow-up SELECT (avoids TOCTOU races).
func (q *Queries) RecordAdapterFailure(ctx context.Context, arg RecordAdapterFailureParams) (RecordAdapterFailureRow, error) {
	row := q.db.QueryRow(ctx, recordAdapterFailure, arg.ID, arg.TenantID, arg.LastFailureReason)
	var i RecordAdapterFailureRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ConsecutiveFailures,
		&i.NextAttemptAt,
	)
	return i, err
}

const recordAdapterSuccess = `-- name: RecordAdapterSuccess :exec
UPDATE integration_adapters
SET consecutive_failures = 0,
    last_failure_at      = NULL,
    last_failure_reason  = NULL,
    next_attempt_at      = NULL
WHERE id = $1 AND tenant_id = $2
`

type RecordAdapterSuccessParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Clears failure state after a successful pull.
func (q *Queries) RecordAdapterSuccess(ctx context.Context, arg RecordAdapterSuccessParams) error {
	_, err := q.db.Exec(ctx, recordAdapterSuccess, arg.ID, arg.TenantID)
	return err
}
