// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_tasks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeInventoryTask = `-- name: CompleteInventoryTask :one
UPDATE inventory_tasks SET status = 'completed', completed_date = now()
WHERE id = $1
RETURNING id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at
`

func (q *Queries) CompleteInventoryTask(ctx context.Context, id uuid.UUID) (InventoryTask, error) {
	row := q.db.QueryRow(ctx, completeInventoryTask, id)
	var i InventoryTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeLocationID,
		&i.Status,
		&i.Method,
		&i.PlannedDate,
		&i.CompletedDate,
		&i.AssignedTo,
		&i.CreatedAt,
	)
	return i, err
}

const countInventoryTasks = `-- name: CountInventoryTasks :one
SELECT count(*) FROM inventory_tasks
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR scope_location_id = $2)
`

type CountInventoryTasksParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	ScopeLocationID pgtype.UUID `json:"scope_location_id"`
}

func (q *Queries) CountInventoryTasks(ctx context.Context, arg CountInventoryTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryTasks, arg.TenantID, arg.ScopeLocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryTask = `-- name: CreateInventoryTask :one
INSERT INTO inventory_tasks (tenant_id, code, name, scope_location_id, status, method, planned_date, assigned_to)
VALUES ($1, $2, $3, $4, 'planned', $5, $6, $7)
RETURNING id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at
`

type CreateInventoryTaskParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	ScopeLocationID pgtype.UUID `json:"scope_location_id"`
	Method          pgtype.Text `json:"method"`
	PlannedDate     pgtype.Date `json:"planned_date"`
	AssignedTo      pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) CreateInventoryTask(ctx context.Context, arg CreateInventoryTaskParams) (InventoryTask, error) {
	row := q.db.QueryRow(ctx, createInventoryTask,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ScopeLocationID,
		arg.Method,
		arg.PlannedDate,
		arg.AssignedTo,
	)
	var i InventoryTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeLocationID,
		&i.Status,
		&i.Method,
		&i.PlannedDate,
		&i.CompletedDate,
		&i.AssignedTo,
		&i.CreatedAt,
	)
	return i, err
}

const getInventorySummary = `-- name: GetInventorySummary :one
SELECT
    count(*) as total,
    count(*) FILTER (WHERE status = 'scanned') as scanned,
    count(*) FILTER (WHERE status = 'pending') as pending,
    count(*) FILTER (WHERE status = 'discrepancy') as discrepancy
FROM inventory_items
WHERE task_id = $1
`

type GetInventorySummaryRow struct {
	Total       int64 `json:"total"`
	Scanned     int64 `json:"scanned"`
	Pending     int64 `json:"pending"`
	Discrepancy int64 `json:"discrepancy"`
}

func (q *Queries) GetInventorySummary(ctx context.Context, taskID uuid.UUID) (GetInventorySummaryRow, error) {
	row := q.db.QueryRow(ctx, getInventorySummary, taskID)
	var i GetInventorySummaryRow
	err := row.Scan(
		&i.Total,
		&i.Scanned,
		&i.Pending,
		&i.Discrepancy,
	)
	return i, err
}

const getInventoryTask = `-- name: GetInventoryTask :one
SELECT id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at FROM inventory_tasks WHERE id = $1 AND tenant_id = $2
`

type GetInventoryTaskParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetInventoryTask(ctx context.Context, arg GetInventoryTaskParams) (InventoryTask, error) {
	row := q.db.QueryRow(ctx, getInventoryTask, arg.ID, arg.TenantID)
	var i InventoryTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeLocationID,
		&i.Status,
		&i.Method,
		&i.PlannedDate,
		&i.CompletedDate,
		&i.AssignedTo,
		&i.CreatedAt,
	)
	return i, err
}

const countInventoryItems = `-- name: CountInventoryItems :one
SELECT count(*) FROM inventory_items WHERE task_id = $1
`

func (q *Queries) CountInventoryItems(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryItems, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, task_id, asset_id, rack_id, expected, actual, status, scanned_at, scanned_by FROM inventory_items
WHERE task_id = $1
ORDER BY status, scanned_at
LIMIT $2 OFFSET $3
`

type ListInventoryItemsParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListInventoryItems(ctx context.Context, arg ListInventoryItemsParams) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listInventoryItems, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AssetID,
			&i.RackID,
			&i.Expected,
			&i.Actual,
			&i.Status,
			&i.ScannedAt,
			&i.ScannedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryTasks = `-- name: ListInventoryTasks :many
SELECT id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at FROM inventory_tasks
WHERE tenant_id = $1
  AND ($4::uuid IS NULL OR scope_location_id = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInventoryTasksParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	ScopeLocationID pgtype.UUID `json:"scope_location_id"`
}

func (q *Queries) ListInventoryTasks(ctx context.Context, arg ListInventoryTasksParams) ([]InventoryTask, error) {
	rows, err := q.db.Query(ctx, listInventoryTasks, arg.TenantID, arg.Limit, arg.Offset, arg.ScopeLocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryTask{}
	for rows.Next() {
		var i InventoryTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ScopeLocationID,
			&i.Status,
			&i.Method,
			&i.PlannedDate,
			&i.CompletedDate,
			&i.AssignedTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanInventoryItem = `-- name: ScanInventoryItem :one
UPDATE inventory_items SET
    actual = $2,
    status = $3,
    scanned_at = now(),
    scanned_by = $4
WHERE id = $1
RETURNING id, task_id, asset_id, rack_id, expected, actual, status, scanned_at, scanned_by
`

type ScanInventoryItemParams struct {
	ID        uuid.UUID   `json:"id"`
	Actual    []byte      `json:"actual"`
	Status    string      `json:"status"`
	ScannedBy pgtype.UUID `json:"scanned_by"`
}

func (q *Queries) ScanInventoryItem(ctx context.Context, arg ScanInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, scanInventoryItem,
		arg.ID,
		arg.Actual,
		arg.Status,
		arg.ScannedBy,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AssetID,
		&i.RackID,
		&i.Expected,
		&i.Actual,
		&i.Status,
		&i.ScannedAt,
		&i.ScannedBy,
	)
	return i, err
}

const activateInventoryTask = `-- name: ActivateInventoryTask :one
UPDATE inventory_tasks SET status = 'in_progress'
WHERE id = $1 AND status = 'planned'
RETURNING id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at
`

func (q *Queries) ActivateInventoryTask(ctx context.Context, id uuid.UUID) (InventoryTask, error) {
	row := q.db.QueryRow(ctx, activateInventoryTask, id)
	var i InventoryTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeLocationID,
		&i.Status,
		&i.Method,
		&i.PlannedDate,
		&i.CompletedDate,
		&i.AssignedTo,
		&i.CreatedAt,
	)
	return i, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (task_id, asset_id, rack_id, expected, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, task_id, asset_id, rack_id, expected, actual, status, scanned_at, scanned_by
`

type CreateInventoryItemParams struct {
	TaskID   uuid.UUID   `json:"task_id"`
	AssetID  pgtype.UUID `json:"asset_id"`
	RackID   pgtype.UUID `json:"rack_id"`
	Expected []byte      `json:"expected"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem, arg.TaskID, arg.AssetID, arg.RackID, arg.Expected)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AssetID,
		&i.RackID,
		&i.Expected,
		&i.Actual,
		&i.Status,
		&i.ScannedAt,
		&i.ScannedBy,
	)
	return i, err
}

const softDeleteInventoryTask = `-- name: SoftDeleteInventoryTask :exec
DELETE FROM inventory_tasks WHERE id = $1 AND tenant_id = $2
`

type SoftDeleteInventoryTaskParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) SoftDeleteInventoryTask(ctx context.Context, arg SoftDeleteInventoryTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteInventoryTask, arg.ID, arg.TenantID)
	return err
}

const updateInventoryTask = `-- name: UpdateInventoryTask :one
UPDATE inventory_tasks SET
    name         = COALESCE($3, name),
    planned_date = COALESCE($4, planned_date),
    assigned_to  = COALESCE($5, assigned_to)
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at
`

type UpdateInventoryTaskParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Name        pgtype.Text `json:"name"`
	PlannedDate pgtype.Text `json:"planned_date"`
	AssignedTo  pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) UpdateInventoryTask(ctx context.Context, arg UpdateInventoryTaskParams) (InventoryTask, error) {
	row := q.db.QueryRow(ctx, updateInventoryTask,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.PlannedDate,
		arg.AssignedTo,
	)
	var i InventoryTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeLocationID,
		&i.Status,
		&i.Method,
		&i.PlannedDate,
		&i.CompletedDate,
		&i.AssignedTo,
		&i.CreatedAt,
	)
	return i, err
}
