// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_tasks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countInventoryTasks = `-- name: CountInventoryTasks :one
SELECT count(*) FROM inventory_tasks WHERE tenant_id = $1
`

func (q *Queries) CountInventoryTasks(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryTasks, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInventoryTask = `-- name: GetInventoryTask :one
SELECT id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at FROM inventory_tasks WHERE id = $1
`

func (q *Queries) GetInventoryTask(ctx context.Context, id uuid.UUID) (InventoryTask, error) {
	row := q.db.QueryRow(ctx, getInventoryTask, id)
	var i InventoryTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ScopeLocationID,
		&i.Status,
		&i.Method,
		&i.PlannedDate,
		&i.CompletedDate,
		&i.AssignedTo,
		&i.CreatedAt,
	)
	return i, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, task_id, asset_id, rack_id, expected, actual, status, scanned_at, scanned_by FROM inventory_items
WHERE task_id = $1
ORDER BY status, scanned_at
`

func (q *Queries) ListInventoryItems(ctx context.Context, taskID uuid.UUID) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listInventoryItems, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AssetID,
			&i.RackID,
			&i.Expected,
			&i.Actual,
			&i.Status,
			&i.ScannedAt,
			&i.ScannedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryTasks = `-- name: ListInventoryTasks :many
SELECT id, tenant_id, code, name, scope_location_id, status, method, planned_date, completed_date, assigned_to, created_at FROM inventory_tasks
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInventoryTasksParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListInventoryTasks(ctx context.Context, arg ListInventoryTasksParams) ([]InventoryTask, error) {
	rows, err := q.db.Query(ctx, listInventoryTasks, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryTask{}
	for rows.Next() {
		var i InventoryTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ScopeLocationID,
			&i.Status,
			&i.Method,
			&i.PlannedDate,
			&i.CompletedDate,
			&i.AssignedTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
