// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: locations.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAlertsByLocation = `-- name: CountAlertsByLocation :many
SELECT a.location_id AS id, COUNT(ae.id)::bigint AS critical_alerts
FROM assets a
JOIN alert_events ae ON ae.asset_id = a.id AND ae.status = 'firing' AND ae.severity = 'critical'
WHERE a.tenant_id = $1 AND a.deleted_at IS NULL AND a.location_id IS NOT NULL
GROUP BY a.location_id
`

type CountAlertsByLocationRow struct {
	ID             pgtype.UUID `json:"id"`
	CriticalAlerts int64       `json:"critical_alerts"`
}

func (q *Queries) CountAlertsByLocation(ctx context.Context, tenantID uuid.UUID) ([]CountAlertsByLocationRow, error) {
	rows, err := q.db.Query(ctx, countAlertsByLocation, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAlertsByLocationRow{}
	for rows.Next() {
		var i CountAlertsByLocationRow
		if err := rows.Scan(&i.ID, &i.CriticalAlerts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAssetsByLocation = `-- name: CountAssetsByLocation :many
SELECT l.id, COUNT(a.id)::bigint AS total_assets
FROM locations l
LEFT JOIN assets a ON a.location_id IN (
  SELECT sub.id FROM locations sub WHERE sub.path <@ l.path AND sub.deleted_at IS NULL
) AND a.deleted_at IS NULL
WHERE l.tenant_id = $1 AND l.deleted_at IS NULL
GROUP BY l.id
`

type CountAssetsByLocationRow struct {
	ID          uuid.UUID `json:"id"`
	TotalAssets int64     `json:"total_assets"`
}

func (q *Queries) CountAssetsByLocation(ctx context.Context, tenantID uuid.UUID) ([]CountAssetsByLocationRow, error) {
	rows, err := q.db.Query(ctx, countAssetsByLocation, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAssetsByLocationRow{}
	for rows.Next() {
		var i CountAssetsByLocationRow
		if err := rows.Scan(&i.ID, &i.TotalAssets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAssetsByLocationDirect = `-- name: CountAssetsByLocationDirect :one
SELECT count(*)::bigint FROM assets
WHERE location_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAssetsByLocationDirect(ctx context.Context, locationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsByLocationDirect, locationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countChildLocations = `-- name: CountChildLocations :one
SELECT count(*)::bigint FROM locations
WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountChildLocations(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildLocations, parentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRacksByLocation = `-- name: CountRacksByLocation :one
SELECT count(*)::bigint FROM racks
WHERE location_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountRacksByLocation(ctx context.Context, locationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRacksByLocation, locationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
    tenant_id, name, name_en, slug, level,
    parent_id, path, status, metadata, sort_order,
    latitude, longitude
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7::ltree, $8, $9, $10,
    $11, $12
) RETURNING id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude
`

type CreateLocationParams struct {
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	NameEn    pgtype.Text     `json:"name_en"`
	Slug      string          `json:"slug"`
	Level     string          `json:"level"`
	ParentID  pgtype.UUID     `json:"parent_id"`
	Column7   string          `json:"column_7"`
	Status    string          `json:"status"`
	Metadata  json.RawMessage `json:"metadata"`
	SortOrder int32           `json:"sort_order"`
	Latitude  pgtype.Float8   `json:"latitude"`
	Longitude pgtype.Float8   `json:"longitude"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.TenantID,
		arg.Name,
		arg.NameEn,
		arg.Slug,
		arg.Level,
		arg.ParentID,
		arg.Column7,
		arg.Status,
		arg.Metadata,
		arg.SortOrder,
		arg.Latitude,
		arg.Longitude,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NameEn,
		&i.Slug,
		&i.Level,
		&i.ParentID,
		&i.Path,
		&i.Status,
		&i.Metadata,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const deleteDescendantLocations = `-- name: DeleteDescendantLocations :exec
DELETE FROM locations
WHERE tenant_id = $1 AND path <@ $2::ltree AND id != $3
`

type DeleteDescendantLocationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDescendantLocations(ctx context.Context, arg DeleteDescendantLocationsParams) error {
	_, err := q.db.Exec(ctx, deleteDescendantLocations, arg.TenantID, arg.Column2, arg.ID)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1 AND tenant_id = $2
`

type DeleteLocationParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteLocation(ctx context.Context, arg DeleteLocationParams) error {
	_, err := q.db.Exec(ctx, deleteLocation, arg.ID, arg.TenantID)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations WHERE id = $1 AND tenant_id = $2
`

type GetLocationParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, arg.ID, arg.TenantID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NameEn,
		&i.Slug,
		&i.Level,
		&i.ParentID,
		&i.Path,
		&i.Status,
		&i.Metadata,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getLocationBySlug = `-- name: GetLocationBySlug :one
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations
WHERE tenant_id = $1 AND slug = $2 AND level = $3
`

type GetLocationBySlugParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
	Level    string    `json:"level"`
}

func (q *Queries) GetLocationBySlug(ctx context.Context, arg GetLocationBySlugParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationBySlug, arg.TenantID, arg.Slug, arg.Level)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NameEn,
		&i.Slug,
		&i.Level,
		&i.ParentID,
		&i.Path,
		&i.Status,
		&i.Metadata,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listAllLocations = `-- name: ListAllLocations :many
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY path, sort_order
`

func (q *Queries) ListAllLocations(ctx context.Context, tenantID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listAllLocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NameEn,
			&i.Slug,
			&i.Level,
			&i.ParentID,
			&i.Path,
			&i.Status,
			&i.Metadata,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncVersion,
			&i.DeletedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAncestors = `-- name: ListAncestors :many
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations
WHERE tenant_id = $1 AND path @> $2::ltree
ORDER BY path
`

type ListAncestorsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) ListAncestors(ctx context.Context, arg ListAncestorsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listAncestors, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NameEn,
			&i.Slug,
			&i.Level,
			&i.ParentID,
			&i.Path,
			&i.Status,
			&i.Metadata,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncVersion,
			&i.DeletedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations
WHERE parent_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListChildren(ctx context.Context, parentID pgtype.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NameEn,
			&i.Slug,
			&i.Level,
			&i.ParentID,
			&i.Path,
			&i.Status,
			&i.Metadata,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncVersion,
			&i.DeletedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescendants = `-- name: ListDescendants :many
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations
WHERE tenant_id = $1 AND path <@ $2::ltree
ORDER BY path
`

type ListDescendantsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) ListDescendants(ctx context.Context, arg ListDescendantsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listDescendants, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NameEn,
			&i.Slug,
			&i.Level,
			&i.ParentID,
			&i.Path,
			&i.Status,
			&i.Metadata,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncVersion,
			&i.DeletedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootLocations = `-- name: ListRootLocations :many
SELECT id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude FROM locations
WHERE tenant_id = $1 AND parent_id IS NULL
ORDER BY sort_order, name
`

func (q *Queries) ListRootLocations(ctx context.Context, tenantID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listRootLocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NameEn,
			&i.Slug,
			&i.Level,
			&i.ParentID,
			&i.Path,
			&i.Status,
			&i.Metadata,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncVersion,
			&i.DeletedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET
    name       = COALESCE($1, name),
    name_en    = COALESCE($2, name_en),
    slug       = COALESCE($3, slug),
    level      = COALESCE($4, level),
    status     = COALESCE($5, status),
    metadata   = COALESCE($6, metadata),
    sort_order = COALESCE($7, sort_order),
    updated_at = now()
WHERE id = $8
RETURNING id, tenant_id, name, name_en, slug, level, parent_id, path, status, metadata, sort_order, created_at, updated_at, sync_version, deleted_at, latitude, longitude
`

type UpdateLocationParams struct {
	Name      pgtype.Text `json:"name"`
	NameEn    pgtype.Text `json:"name_en"`
	Slug      pgtype.Text `json:"slug"`
	Level     pgtype.Text `json:"level"`
	Status    pgtype.Text `json:"status"`
	Metadata  []byte      `json:"metadata"`
	SortOrder pgtype.Int4 `json:"sort_order"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.NameEn,
		arg.Slug,
		arg.Level,
		arg.Status,
		arg.Metadata,
		arg.SortOrder,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NameEn,
		&i.Slug,
		&i.Level,
		&i.ParentID,
		&i.Path,
		&i.Status,
		&i.Metadata,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
