// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMetric = `-- name: InsertMetric :exec
INSERT INTO metrics (time, asset_id, tenant_id, name, value, labels)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMetricParams struct {
	Time     time.Time     `json:"time"`
	AssetID  pgtype.UUID   `json:"asset_id"`
	TenantID pgtype.UUID   `json:"tenant_id"`
	Name     string        `json:"name"`
	Value    pgtype.Float8 `json:"value"`
	Labels   []byte        `json:"labels"`
}

func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) error {
	_, err := q.db.Exec(ctx, insertMetric,
		arg.Time,
		arg.AssetID,
		arg.TenantID,
		arg.Name,
		arg.Value,
		arg.Labels,
	)
	return err
}

const queryMetricsByAsset = `-- name: QueryMetricsByAsset :many
SELECT time, name, value
FROM metrics
WHERE asset_id = $1
  AND name = $2
  AND time > $3
ORDER BY time DESC
LIMIT 500
`

type QueryMetricsByAssetParams struct {
	AssetID pgtype.UUID `json:"asset_id"`
	Name    string      `json:"name"`
	Time    time.Time   `json:"time"`
}

type QueryMetricsByAssetRow struct {
	Time  time.Time     `json:"time"`
	Name  string        `json:"name"`
	Value pgtype.Float8 `json:"value"`
}

func (q *Queries) QueryMetricsByAsset(ctx context.Context, arg QueryMetricsByAssetParams) ([]QueryMetricsByAssetRow, error) {
	rows, err := q.db.Query(ctx, queryMetricsByAsset, arg.AssetID, arg.Name, arg.Time)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryMetricsByAssetRow{}
	for rows.Next() {
		var i QueryMetricsByAssetRow
		if err := rows.Scan(&i.Time, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
