// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metric_sources.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMetricSource = `-- name: CreateMetricSource :one
INSERT INTO metric_sources (
    tenant_id, name, kind, expected_interval_seconds, status, notes
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, kind, expected_interval_seconds, status, last_heartbeat_at, last_sample_count, notes, created_at, updated_at
`

type CreateMetricSourceParams struct {
	TenantID                uuid.UUID   `json:"tenant_id"`
	Name                    string      `json:"name"`
	Kind                    string      `json:"kind"`
	ExpectedIntervalSeconds int32       `json:"expected_interval_seconds"`
	Status                  string      `json:"status"`
	Notes                   pgtype.Text `json:"notes"`
}

func (q *Queries) CreateMetricSource(ctx context.Context, arg CreateMetricSourceParams) (MetricSource, error) {
	row := q.db.QueryRow(ctx, createMetricSource,
		arg.TenantID,
		arg.Name,
		arg.Kind,
		arg.ExpectedIntervalSeconds,
		arg.Status,
		arg.Notes,
	)
	var i MetricSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.ExpectedIntervalSeconds,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSampleCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMetricSource = `-- name: DeleteMetricSource :exec
DELETE FROM metric_sources WHERE id = $1 AND tenant_id = $2
`

type DeleteMetricSourceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMetricSource(ctx context.Context, arg DeleteMetricSourceParams) error {
	_, err := q.db.Exec(ctx, deleteMetricSource, arg.ID, arg.TenantID)
	return err
}

const getMetricSource = `-- name: GetMetricSource :one
SELECT id, tenant_id, name, kind, expected_interval_seconds, status, last_heartbeat_at, last_sample_count, notes, created_at, updated_at FROM metric_sources WHERE id = $1 AND tenant_id = $2
`

type GetMetricSourceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetMetricSource(ctx context.Context, arg GetMetricSourceParams) (MetricSource, error) {
	row := q.db.QueryRow(ctx, getMetricSource, arg.ID, arg.TenantID)
	var i MetricSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.ExpectedIntervalSeconds,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSampleCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetricSourceByName = `-- name: GetMetricSourceByName :one
SELECT id, tenant_id, name, kind, expected_interval_seconds, status, last_heartbeat_at, last_sample_count, notes, created_at, updated_at FROM metric_sources WHERE tenant_id = $1 AND name = $2
`

type GetMetricSourceByNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) GetMetricSourceByName(ctx context.Context, arg GetMetricSourceByNameParams) (MetricSource, error) {
	row := q.db.QueryRow(ctx, getMetricSourceByName, arg.TenantID, arg.Name)
	var i MetricSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.ExpectedIntervalSeconds,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSampleCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatMetricSource = `-- name: HeartbeatMetricSource :one
UPDATE metric_sources SET
    last_heartbeat_at = now(),
    last_sample_count = last_sample_count + $1
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, kind, expected_interval_seconds, status, last_heartbeat_at, last_sample_count, notes, created_at, updated_at
`

type HeartbeatMetricSourceParams struct {
	SampleDelta int64     `json:"sample_delta"`
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
}

// Bumps last_heartbeat_at to now() and adds the supplied sample count
// to the lifetime counter. Operators don't have to compute the new
// count themselves; the SQL adds it server-side so concurrent
// heartbeats can't race-clobber each other.
func (q *Queries) HeartbeatMetricSource(ctx context.Context, arg HeartbeatMetricSourceParams) (MetricSource, error) {
	row := q.db.QueryRow(ctx, heartbeatMetricSource, arg.SampleDelta, arg.ID, arg.TenantID)
	var i MetricSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.ExpectedIntervalSeconds,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSampleCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMetricSources = `-- name: ListMetricSources :many
SELECT id, tenant_id, name, kind, expected_interval_seconds, status, last_heartbeat_at, last_sample_count, notes, created_at, updated_at FROM metric_sources
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::varchar   IS NULL OR kind   = $3)
ORDER BY last_heartbeat_at NULLS FIRST, name
`

type ListMetricSourcesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Kind     pgtype.Text `json:"kind"`
}

func (q *Queries) ListMetricSources(ctx context.Context, arg ListMetricSourcesParams) ([]MetricSource, error) {
	rows, err := q.db.Query(ctx, listMetricSources, arg.TenantID, arg.Status, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSource{}
	for rows.Next() {
		var i MetricSource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Kind,
			&i.ExpectedIntervalSeconds,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.LastSampleCount,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleMetricSources = `-- name: ListStaleMetricSources :many
SELECT
    s.id, s.tenant_id, s.name, s.kind, s.expected_interval_seconds, s.status, s.last_heartbeat_at, s.last_sample_count, s.notes, s.created_at, s.updated_at,
    -- sqlc generates non-nullable int32 from EXTRACT(...)::int. NULL
    -- last_heartbeat_at would scan-fail, so coerce never-heartbeated
    -- rows to -1 — the handler maps that sentinel back to a nil
    -- "seconds_since_heartbeat" in the API response.
    COALESCE(EXTRACT(EPOCH FROM (now() - s.last_heartbeat_at))::int, -1) AS seconds_since_heartbeat
FROM metric_sources s
WHERE s.tenant_id = $1
  AND s.status    = 'active'
  AND (
        s.last_heartbeat_at IS NULL
     OR s.last_heartbeat_at < now() - (s.expected_interval_seconds * 2 || ' seconds')::interval
      )
ORDER BY s.last_heartbeat_at NULLS FIRST, s.name
`

type ListStaleMetricSourcesRow struct {
	ID                      uuid.UUID          `json:"id"`
	TenantID                uuid.UUID          `json:"tenant_id"`
	Name                    string             `json:"name"`
	Kind                    string             `json:"kind"`
	ExpectedIntervalSeconds int32              `json:"expected_interval_seconds"`
	Status                  string             `json:"status"`
	LastHeartbeatAt         pgtype.Timestamptz `json:"last_heartbeat_at"`
	LastSampleCount         int64              `json:"last_sample_count"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
	SecondsSinceHeartbeat   interface{}        `json:"seconds_since_heartbeat"`
}

// The "data plane health" query. A source is stale when its
// last_heartbeat_at is more than 2× expected_interval old (or it has
// never sent a heartbeat at all). Disabled sources are excluded.
// The 2× factor is tolerant of jitter / short restarts without
// flapping the freshness alert.
func (q *Queries) ListStaleMetricSources(ctx context.Context, tenantID uuid.UUID) ([]ListStaleMetricSourcesRow, error) {
	rows, err := q.db.Query(ctx, listStaleMetricSources, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleMetricSourcesRow{}
	for rows.Next() {
		var i ListStaleMetricSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Kind,
			&i.ExpectedIntervalSeconds,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.LastSampleCount,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecondsSinceHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetricSource = `-- name: UpdateMetricSource :one
UPDATE metric_sources SET
    name                      = COALESCE($1,                      name),
    kind                      = COALESCE($2,                      kind),
    expected_interval_seconds = COALESCE($3, expected_interval_seconds),
    status                    = COALESCE($4,                    status),
    notes                     = COALESCE($5,                     notes)
WHERE id = $6 AND tenant_id = $7
RETURNING id, tenant_id, name, kind, expected_interval_seconds, status, last_heartbeat_at, last_sample_count, notes, created_at, updated_at
`

type UpdateMetricSourceParams struct {
	Name                    pgtype.Text `json:"name"`
	Kind                    pgtype.Text `json:"kind"`
	ExpectedIntervalSeconds pgtype.Int4 `json:"expected_interval_seconds"`
	Status                  pgtype.Text `json:"status"`
	Notes                   pgtype.Text `json:"notes"`
	ID                      uuid.UUID   `json:"id"`
	TenantID                uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateMetricSource(ctx context.Context, arg UpdateMetricSourceParams) (MetricSource, error) {
	row := q.db.QueryRow(ctx, updateMetricSource,
		arg.Name,
		arg.Kind,
		arg.ExpectedIntervalSeconds,
		arg.Status,
		arg.Notes,
		arg.ID,
		arg.TenantID,
	)
	var i MetricSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.ExpectedIntervalSeconds,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSampleCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
