// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateMetricPerAsset = `-- name: AggregateMetricPerAsset :many
SELECT
    asset_id,
    CASE $3::text
        WHEN 'avg' THEN avg(value)
        WHEN 'max' THEN max(value)
        WHEN 'min' THEN min(value)
        WHEN 'p95' THEN percentile_cont(0.95) WITHIN GROUP (ORDER BY value)
        WHEN 'p99' THEN percentile_cont(0.99) WITHIN GROUP (ORDER BY value)
        ELSE NULL
    END AS aggregated_value,
    count(*) AS sample_count
FROM metrics
WHERE tenant_id = $1
  AND name = $2
  AND time > $4
GROUP BY asset_id
`

type AggregateMetricPerAssetParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Column3  string      `json:"column_3"`
	Time     time.Time   `json:"time"`
}

type AggregateMetricPerAssetRow struct {
	AssetID         pgtype.UUID `json:"asset_id"`
	AggregatedValue interface{} `json:"aggregated_value"`
	SampleCount     int64       `json:"sample_count"`
}

// Tenant-scoped aggregation used by the alert evaluator. Every call is
// strictly scoped by tenant_id so rules never read another tenant's metrics.
// The aggregation is chosen via $3 ('avg'|'max'|'min'|'p95'|'p99'); anything
// else short-circuits to NULL and the evaluator treats the row as missing.
// We group by asset_id so each asset is judged against the threshold
// independently — one rule, one metric, many assets.
func (q *Queries) AggregateMetricPerAsset(ctx context.Context, arg AggregateMetricPerAssetParams) ([]AggregateMetricPerAssetRow, error) {
	rows, err := q.db.Query(ctx, aggregateMetricPerAsset,
		arg.TenantID,
		arg.Name,
		arg.Column3,
		arg.Time,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateMetricPerAssetRow{}
	for rows.Next() {
		var i AggregateMetricPerAssetRow
		if err := rows.Scan(&i.AssetID, &i.AggregatedValue, &i.SampleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMetric = `-- name: InsertMetric :exec
INSERT INTO metrics (time, asset_id, tenant_id, name, value, labels)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMetricParams struct {
	Time     time.Time     `json:"time"`
	AssetID  pgtype.UUID   `json:"asset_id"`
	TenantID pgtype.UUID   `json:"tenant_id"`
	Name     string        `json:"name"`
	Value    pgtype.Float8 `json:"value"`
	Labels   []byte        `json:"labels"`
}

func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) error {
	_, err := q.db.Exec(ctx, insertMetric,
		arg.Time,
		arg.AssetID,
		arg.TenantID,
		arg.Name,
		arg.Value,
		arg.Labels,
	)
	return err
}

const queryMetricsByAsset = `-- name: QueryMetricsByAsset :many
SELECT time, name, value
FROM metrics
WHERE asset_id = $1
  AND name = $2
  AND time > $3
ORDER BY time DESC
LIMIT 500
`

type QueryMetricsByAssetParams struct {
	AssetID pgtype.UUID `json:"asset_id"`
	Name    string      `json:"name"`
	Time    time.Time   `json:"time"`
}

type QueryMetricsByAssetRow struct {
	Time  time.Time     `json:"time"`
	Name  string        `json:"name"`
	Value pgtype.Float8 `json:"value"`
}

func (q *Queries) QueryMetricsByAsset(ctx context.Context, arg QueryMetricsByAssetParams) ([]QueryMetricsByAssetRow, error) {
	rows, err := q.db.Query(ctx, queryMetricsByAsset, arg.AssetID, arg.Name, arg.Time)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryMetricsByAssetRow{}
	for rows.Next() {
		var i QueryMetricsByAssetRow
		if err := rows.Scan(&i.Time, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLatestPowerKW = `-- name: SumLatestPowerKW :one
SELECT (COALESCE(SUM(value), 0) / 1000.0)::float8
FROM (
    SELECT DISTINCT ON (asset_id) value
    FROM metrics
    WHERE tenant_id = $1::uuid
      AND name = 'power.current_w'
      AND time > now() - interval '10 minutes'
    ORDER BY asset_id, time DESC
) latest
`

// Sum of each asset's most-recent power.current_w reading within the
// last 10 minutes, converted to kilowatts. DISTINCT ON picks the
// newest value per asset; stale assets (no reading in the window)
// drop out of the sum rather than contributing zeroed-out energy.
// Returns 0 when no readings exist. The 10-minute lookback matches
// the typical scrape cadence with headroom for one missed interval.
func (q *Queries) SumLatestPowerKW(ctx context.Context, tenantID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, sumLatestPowerKW, tenantID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
