// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertEvent struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	RuleID       pgtype.UUID        `json:"rule_id"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	Status       string             `json:"status"`
	Severity     string             `json:"severity"`
	Message      pgtype.Text        `json:"message"`
	TriggerValue pgtype.Numeric     `json:"trigger_value"`
	FiredAt      time.Time          `json:"fired_at"`
	AckedAt      pgtype.Timestamptz `json:"acked_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
}

type AlertRule struct {
	ID         uuid.UUID       `json:"id"`
	TenantID   uuid.UUID       `json:"tenant_id"`
	Name       string          `json:"name"`
	MetricName string          `json:"metric_name"`
	Condition  json.RawMessage `json:"condition"`
	Severity   string          `json:"severity"`
	Enabled    bool            `json:"enabled"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Asset struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	AssetTag       string          `json:"asset_tag"`
	PropertyNumber pgtype.Text     `json:"property_number"`
	ControlNumber  pgtype.Text     `json:"control_number"`
	Name           string          `json:"name"`
	Type           string          `json:"type"`
	SubType        pgtype.Text     `json:"sub_type"`
	Status         string          `json:"status"`
	BiaLevel       string          `json:"bia_level"`
	LocationID     pgtype.UUID     `json:"location_id"`
	RackID         pgtype.UUID     `json:"rack_id"`
	Vendor         pgtype.Text     `json:"vendor"`
	Model          pgtype.Text     `json:"model"`
	SerialNumber   pgtype.Text     `json:"serial_number"`
	Attributes     json.RawMessage `json:"attributes"`
	Tags           []string        `json:"tags"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type AuditEvent struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	Action     string      `json:"action"`
	Module     pgtype.Text `json:"module"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	OperatorID pgtype.UUID `json:"operator_id"`
	Diff       []byte      `json:"diff"`
	Source     string      `json:"source"`
	CreatedAt  time.Time   `json:"created_at"`
}

type BiaAssessment struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	SystemName      string             `json:"system_name"`
	SystemCode      string             `json:"system_code"`
	Owner           pgtype.Text        `json:"owner"`
	BiaScore        int32              `json:"bia_score"`
	Tier            string             `json:"tier"`
	RtoHours        pgtype.Numeric     `json:"rto_hours"`
	RpoMinutes      pgtype.Numeric     `json:"rpo_minutes"`
	MtpdHours       pgtype.Numeric     `json:"mtpd_hours"`
	DataCompliance  pgtype.Bool        `json:"data_compliance"`
	AssetCompliance pgtype.Bool        `json:"asset_compliance"`
	AuditCompliance pgtype.Bool        `json:"audit_compliance"`
	Description     pgtype.Text        `json:"description"`
	LastAssessed    pgtype.Timestamptz `json:"last_assessed"`
	AssessedBy      pgtype.UUID        `json:"assessed_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type BiaDependency struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	AssessmentID   uuid.UUID   `json:"assessment_id"`
	AssetID        uuid.UUID   `json:"asset_id"`
	DependencyType string      `json:"dependency_type"`
	Criticality    pgtype.Text `json:"criticality"`
	CreatedAt      time.Time   `json:"created_at"`
}

type BiaScoringRule struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	TierName     string         `json:"tier_name"`
	TierLevel    int32          `json:"tier_level"`
	DisplayName  string         `json:"display_name"`
	MinScore     int32          `json:"min_score"`
	MaxScore     int32          `json:"max_score"`
	RtoThreshold pgtype.Numeric `json:"rto_threshold"`
	RpoThreshold pgtype.Numeric `json:"rpo_threshold"`
	Description  pgtype.Text    `json:"description"`
	Color        pgtype.Text    `json:"color"`
	Icon         pgtype.Text    `json:"icon"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Department struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Permissions json.RawMessage `json:"permissions"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Incident struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Severity   string             `json:"severity"`
	StartedAt  time.Time          `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type IntegrationAdapter struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Direction string             `json:"direction"`
	Endpoint  pgtype.Text        `json:"endpoint"`
	Config    []byte             `json:"config"`
	Enabled   pgtype.Bool        `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InventoryItem struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	AssetID   pgtype.UUID        `json:"asset_id"`
	RackID    pgtype.UUID        `json:"rack_id"`
	Expected  []byte             `json:"expected"`
	Actual    []byte             `json:"actual"`
	Status    string             `json:"status"`
	ScannedAt pgtype.Timestamptz `json:"scanned_at"`
	ScannedBy pgtype.UUID        `json:"scanned_by"`
}

type InventoryTask struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	ScopeLocationID pgtype.UUID `json:"scope_location_id"`
	Status          string      `json:"status"`
	Method          pgtype.Text `json:"method"`
	PlannedDate     pgtype.Date `json:"planned_date"`
	CompletedDate   pgtype.Date `json:"completed_date"`
	AssignedTo      pgtype.UUID `json:"assigned_to"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Location struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	NameEn    pgtype.Text     `json:"name_en"`
	Slug      string          `json:"slug"`
	Level     string          `json:"level"`
	ParentID  pgtype.UUID     `json:"parent_id"`
	Path      pgtype.Text     `json:"path"`
	Status    string          `json:"status"`
	Metadata  json.RawMessage `json:"metadata"`
	SortOrder int32           `json:"sort_order"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Metric struct {
	Time     time.Time     `json:"time"`
	AssetID  pgtype.UUID   `json:"asset_id"`
	TenantID pgtype.UUID   `json:"tenant_id"`
	Name     string        `json:"name"`
	Value    pgtype.Float8 `json:"value"`
	Labels   []byte        `json:"labels"`
}

type Metrics1hour struct {
	Bucket   interface{} `json:"bucket"`
	AssetID  pgtype.UUID `json:"asset_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	AvgValue float64     `json:"avg_value"`
	MaxValue interface{} `json:"max_value"`
	MinValue interface{} `json:"min_value"`
}

type Metrics5min struct {
	Bucket   interface{} `json:"bucket"`
	AssetID  pgtype.UUID `json:"asset_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	AvgValue float64     `json:"avg_value"`
	MaxValue interface{} `json:"max_value"`
	MinValue interface{} `json:"min_value"`
}

type PredictionModel struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Provider  string             `json:"provider"`
	Config    json.RawMessage    `json:"config"`
	Enabled   pgtype.Bool        `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PredictionResult struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ModelID           uuid.UUID          `json:"model_id"`
	AssetID           uuid.UUID          `json:"asset_id"`
	PredictionType    string             `json:"prediction_type"`
	Result            json.RawMessage    `json:"result"`
	Severity          pgtype.Text        `json:"severity"`
	RecommendedAction pgtype.Text        `json:"recommended_action"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Rack struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	LocationID      uuid.UUID      `json:"location_id"`
	Name            string         `json:"name"`
	RowLabel        pgtype.Text    `json:"row_label"`
	TotalU          int32          `json:"total_u"`
	PowerCapacityKw pgtype.Numeric `json:"power_capacity_kw"`
	Status          string         `json:"status"`
	Tags            []string       `json:"tags"`
	CreatedAt       time.Time      `json:"created_at"`
}

type RackSlot struct {
	ID      uuid.UUID `json:"id"`
	RackID  uuid.UUID `json:"rack_id"`
	AssetID uuid.UUID `json:"asset_id"`
	StartU  int32     `json:"start_u"`
	EndU    int32     `json:"end_u"`
	Side    string    `json:"side"`
}

type RcaAnalysis struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	IncidentID        uuid.UUID          `json:"incident_id"`
	ModelID           pgtype.UUID        `json:"model_id"`
	Reasoning         json.RawMessage    `json:"reasoning"`
	ConclusionAssetID pgtype.UUID        `json:"conclusion_asset_id"`
	Confidence        pgtype.Numeric     `json:"confidence"`
	HumanVerified     pgtype.Bool        `json:"human_verified"`
	VerifiedBy        pgtype.UUID        `json:"verified_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    pgtype.UUID     `json:"tenant_id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	IsSystem    bool            `json:"is_system"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Status    string          `json:"status"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	DeptID       pgtype.UUID `json:"dept_id"`
	Username     string      `json:"username"`
	DisplayName  string      `json:"display_name"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash string      `json:"password_hash"`
	Status       string      `json:"status"`
	Source       string      `json:"source"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	EventType      string             `json:"event_type"`
	Payload        json.RawMessage    `json:"payload"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}

type WebhookSubscription struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Secret    pgtype.Text        `json:"secret"`
	Events    []string           `json:"events"`
	Enabled   pgtype.Bool        `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkOrder struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	LocationID     pgtype.UUID        `json:"location_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	RequestorID    pgtype.UUID        `json:"requestor_id"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	Description    pgtype.Text        `json:"description"`
	Reason         pgtype.Text        `json:"reason"`
	PredictionID   pgtype.UUID        `json:"prediction_id"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd   pgtype.Timestamptz `json:"scheduled_end"`
	ActualStart    pgtype.Timestamptz `json:"actual_start"`
	ActualEnd      pgtype.Timestamptz `json:"actual_end"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type WorkOrderLog struct {
	ID         uuid.UUID   `json:"id"`
	OrderID    uuid.UUID   `json:"order_id"`
	Action     string      `json:"action"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   pgtype.Text `json:"to_status"`
	OperatorID pgtype.UUID `json:"operator_id"`
	Comment    pgtype.Text `json:"comment"`
	CreatedAt  time.Time   `json:"created_at"`
}
