// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditOperatorType string

const (
	AuditOperatorTypeUser        AuditOperatorType = "user"
	AuditOperatorTypeSystem      AuditOperatorType = "system"
	AuditOperatorTypeIntegration AuditOperatorType = "integration"
	AuditOperatorTypeSync        AuditOperatorType = "sync"
	AuditOperatorTypeAnonymous   AuditOperatorType = "anonymous"
)

func (e *AuditOperatorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditOperatorType(s)
	case string:
		*e = AuditOperatorType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditOperatorType: %T", src)
	}
	return nil
}

type NullAuditOperatorType struct {
	AuditOperatorType AuditOperatorType `json:"audit_operator_type"`
	Valid             bool              `json:"valid"` // Valid is true if AuditOperatorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditOperatorType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditOperatorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditOperatorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditOperatorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditOperatorType), nil
}

type DependencyCategory string

const (
	DependencyCategoryContainment   DependencyCategory = "containment"
	DependencyCategoryDependency    DependencyCategory = "dependency"
	DependencyCategoryCommunication DependencyCategory = "communication"
	DependencyCategoryCustom        DependencyCategory = "custom"
)

func (e *DependencyCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DependencyCategory(s)
	case string:
		*e = DependencyCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for DependencyCategory: %T", src)
	}
	return nil
}

type NullDependencyCategory struct {
	DependencyCategory DependencyCategory `json:"dependency_category"`
	Valid              bool               `json:"valid"` // Valid is true if DependencyCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDependencyCategory) Scan(value interface{}) error {
	if value == nil {
		ns.DependencyCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DependencyCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDependencyCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DependencyCategory), nil
}

type AlertEvent struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	RuleID       pgtype.UUID        `json:"rule_id"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	Status       string             `json:"status"`
	Severity     string             `json:"severity"`
	Message      pgtype.Text        `json:"message"`
	TriggerValue pgtype.Numeric     `json:"trigger_value"`
	FiredAt      time.Time          `json:"fired_at"`
	AckedAt      pgtype.Timestamptz `json:"acked_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	SyncVersion  int64              `json:"sync_version"`
	DedupKey     string             `json:"dedup_key"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type AlertRule struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	Name        string          `json:"name"`
	MetricName  string          `json:"metric_name"`
	Condition   json.RawMessage `json:"condition"`
	Severity    string          `json:"severity"`
	Enabled     bool            `json:"enabled"`
	CreatedAt   time.Time       `json:"created_at"`
	SyncVersion int64           `json:"sync_version"`
}

type Asset struct {
	ID                     uuid.UUID          `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	AssetTag               string             `json:"asset_tag"`
	PropertyNumber         pgtype.Text        `json:"property_number"`
	ControlNumber          pgtype.Text        `json:"control_number"`
	Name                   string             `json:"name"`
	Type                   string             `json:"type"`
	SubType                pgtype.Text        `json:"sub_type"`
	Status                 string             `json:"status"`
	BiaLevel               string             `json:"bia_level"`
	LocationID             pgtype.UUID        `json:"location_id"`
	RackID                 pgtype.UUID        `json:"rack_id"`
	Vendor                 pgtype.Text        `json:"vendor"`
	Model                  pgtype.Text        `json:"model"`
	SerialNumber           pgtype.Text        `json:"serial_number"`
	Attributes             json.RawMessage    `json:"attributes"`
	Tags                   []string           `json:"tags"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	IpAddress              pgtype.Text        `json:"ip_address"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	SyncVersion            int64              `json:"sync_version"`
	BmcIp                  pgtype.Text        `json:"bmc_ip"`
	BmcType                pgtype.Text        `json:"bmc_type"`
	BmcFirmware            pgtype.Text        `json:"bmc_firmware"`
	PurchaseDate           pgtype.Date        `json:"purchase_date"`
	PurchaseCost           pgtype.Numeric     `json:"purchase_cost"`
	WarrantyStart          pgtype.Date        `json:"warranty_start"`
	WarrantyEnd            pgtype.Date        `json:"warranty_end"`
	WarrantyVendor         pgtype.Text        `json:"warranty_vendor"`
	WarrantyContract       pgtype.Text        `json:"warranty_contract"`
	ExpectedLifespanMonths pgtype.Int4        `json:"expected_lifespan_months"`
	EolDate                pgtype.Date        `json:"eol_date"`
}

type AssetDependency struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	SourceAssetID      uuid.UUID          `json:"source_asset_id"`
	TargetAssetID      uuid.UUID          `json:"target_asset_id"`
	DependencyType     string             `json:"dependency_type"`
	Description        pgtype.Text        `json:"description"`
	CreatedAt          time.Time          `json:"created_at"`
	DependencyCategory DependencyCategory `json:"dependency_category"`
}

type AssetLocationHistory struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	AssetID     uuid.UUID          `json:"asset_id"`
	FromRackID  pgtype.UUID        `json:"from_rack_id"`
	ToRackID    pgtype.UUID        `json:"to_rack_id"`
	DetectedBy  string             `json:"detected_by"`
	WorkOrderID pgtype.UUID        `json:"work_order_id"`
	DetectedAt  pgtype.Timestamptz `json:"detected_at"`
}

type AssetSnapshot struct {
	ID           uuid.UUID       `json:"id"`
	AssetID      uuid.UUID       `json:"asset_id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	ValidAt      time.Time       `json:"valid_at"`
	Name         string          `json:"name"`
	AssetTag     string          `json:"asset_tag"`
	Status       string          `json:"status"`
	BiaLevel     string          `json:"bia_level"`
	LocationID   pgtype.UUID     `json:"location_id"`
	RackID       pgtype.UUID     `json:"rack_id"`
	Vendor       pgtype.Text     `json:"vendor"`
	Model        pgtype.Text     `json:"model"`
	SerialNumber pgtype.Text     `json:"serial_number"`
	Attributes   json.RawMessage `json:"attributes"`
	Tags         []string        `json:"tags"`
}

type AssetSnapshotsLegacyPartition struct {
	ID           uuid.UUID       `json:"id"`
	AssetID      uuid.UUID       `json:"asset_id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	ValidAt      time.Time       `json:"valid_at"`
	Name         string          `json:"name"`
	AssetTag     string          `json:"asset_tag"`
	Status       string          `json:"status"`
	BiaLevel     string          `json:"bia_level"`
	LocationID   pgtype.UUID     `json:"location_id"`
	RackID       pgtype.UUID     `json:"rack_id"`
	Vendor       pgtype.Text     `json:"vendor"`
	Model        pgtype.Text     `json:"model"`
	SerialNumber pgtype.Text     `json:"serial_number"`
	Attributes   json.RawMessage `json:"attributes"`
	Tags         []string        `json:"tags"`
}

type AuditEvent struct {
	ID           uuid.UUID         `json:"id"`
	TenantID     uuid.UUID         `json:"tenant_id"`
	Action       string            `json:"action"`
	Module       pgtype.Text       `json:"module"`
	TargetType   pgtype.Text       `json:"target_type"`
	TargetID     pgtype.UUID       `json:"target_id"`
	OperatorID   pgtype.UUID       `json:"operator_id"`
	Diff         []byte            `json:"diff"`
	Source       string            `json:"source"`
	CreatedAt    time.Time         `json:"created_at"`
	OperatorType AuditOperatorType `json:"operator_type"`
}

type AuditEventsCurrentMonth struct {
	ID           uuid.UUID         `json:"id"`
	TenantID     uuid.UUID         `json:"tenant_id"`
	Action       string            `json:"action"`
	Module       pgtype.Text       `json:"module"`
	TargetType   pgtype.Text       `json:"target_type"`
	TargetID     pgtype.UUID       `json:"target_id"`
	OperatorID   pgtype.UUID       `json:"operator_id"`
	Diff         []byte            `json:"diff"`
	Source       string            `json:"source"`
	CreatedAt    time.Time         `json:"created_at"`
	OperatorType AuditOperatorType `json:"operator_type"`
}

// orphan from 000053; safe to drop after 7 days of steady state
type AuditEventsLegacy struct {
	ID           uuid.UUID         `json:"id"`
	TenantID     uuid.UUID         `json:"tenant_id"`
	Action       string            `json:"action"`
	Module       pgtype.Text       `json:"module"`
	TargetType   pgtype.Text       `json:"target_type"`
	TargetID     pgtype.UUID       `json:"target_id"`
	OperatorID   pgtype.UUID       `json:"operator_id"`
	Diff         []byte            `json:"diff"`
	Source       string            `json:"source"`
	CreatedAt    time.Time         `json:"created_at"`
	OperatorType AuditOperatorType `json:"operator_type"`
}

type AuditEventsLegacyPartition struct {
	ID           uuid.UUID         `json:"id"`
	TenantID     uuid.UUID         `json:"tenant_id"`
	Action       string            `json:"action"`
	Module       pgtype.Text       `json:"module"`
	TargetType   pgtype.Text       `json:"target_type"`
	TargetID     pgtype.UUID       `json:"target_id"`
	OperatorID   pgtype.UUID       `json:"operator_id"`
	Diff         []byte            `json:"diff"`
	Source       string            `json:"source"`
	CreatedAt    time.Time         `json:"created_at"`
	OperatorType AuditOperatorType `json:"operator_type"`
}

type BiaAssessment struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	SystemName      string             `json:"system_name"`
	SystemCode      string             `json:"system_code"`
	Owner           pgtype.Text        `json:"owner"`
	BiaScore        int32              `json:"bia_score"`
	Tier            string             `json:"tier"`
	RtoHours        pgtype.Numeric     `json:"rto_hours"`
	RpoMinutes      pgtype.Numeric     `json:"rpo_minutes"`
	MtpdHours       pgtype.Numeric     `json:"mtpd_hours"`
	DataCompliance  pgtype.Bool        `json:"data_compliance"`
	AssetCompliance pgtype.Bool        `json:"asset_compliance"`
	AuditCompliance pgtype.Bool        `json:"audit_compliance"`
	Description     pgtype.Text        `json:"description"`
	LastAssessed    pgtype.Timestamptz `json:"last_assessed"`
	AssessedBy      pgtype.UUID        `json:"assessed_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type BiaDependency struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	AssessmentID   uuid.UUID   `json:"assessment_id"`
	AssetID        uuid.UUID   `json:"asset_id"`
	DependencyType string      `json:"dependency_type"`
	Criticality    pgtype.Text `json:"criticality"`
	CreatedAt      time.Time   `json:"created_at"`
}

type BiaScoringRule struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	TierName     string         `json:"tier_name"`
	TierLevel    int32          `json:"tier_level"`
	DisplayName  string         `json:"display_name"`
	MinScore     int32          `json:"min_score"`
	MaxScore     int32          `json:"max_score"`
	RtoThreshold pgtype.Numeric `json:"rto_threshold"`
	RpoThreshold pgtype.Numeric `json:"rpo_threshold"`
	Description  pgtype.Text    `json:"description"`
	Color        pgtype.Text    `json:"color"`
	Icon         pgtype.Text    `json:"icon"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Credential struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Params    []byte      `json:"params"`
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Department struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Permissions json.RawMessage `json:"permissions"`
	CreatedAt   time.Time       `json:"created_at"`
}

type DiscoveredAsset struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Source          string             `json:"source"`
	ExternalID      pgtype.Text        `json:"external_id"`
	Hostname        pgtype.Text        `json:"hostname"`
	IpAddress       pgtype.Text        `json:"ip_address"`
	RawData         json.RawMessage    `json:"raw_data"`
	Status          string             `json:"status"`
	MatchedAssetID  pgtype.UUID        `json:"matched_asset_id"`
	DiffDetails     []byte             `json:"diff_details"`
	DiscoveredAt    time.Time          `json:"discovered_at"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	ApprovedAssetID pgtype.UUID        `json:"approved_asset_id"`
}

type Incident struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	Title      string             `json:"title"`
	Status     string             `json:"status"`
	Severity   string             `json:"severity"`
	StartedAt  time.Time          `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type IntegrationAdapter struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Direction           string             `json:"direction"`
	Endpoint            pgtype.Text        `json:"endpoint"`
	Config              []byte             `json:"config"`
	Enabled             pgtype.Bool        `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ConfigEncrypted     []byte             `json:"config_encrypted"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	LastFailureReason   pgtype.Text        `json:"last_failure_reason"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
}

type InventoryItem struct {
	ID          uuid.UUID          `json:"id"`
	TaskID      uuid.UUID          `json:"task_id"`
	AssetID     pgtype.UUID        `json:"asset_id"`
	RackID      pgtype.UUID        `json:"rack_id"`
	Expected    []byte             `json:"expected"`
	Actual      []byte             `json:"actual"`
	Status      string             `json:"status"`
	ScannedAt   pgtype.Timestamptz `json:"scanned_at"`
	ScannedBy   pgtype.UUID        `json:"scanned_by"`
	SyncVersion int64              `json:"sync_version"`
}

type InventoryNote struct {
	ID        uuid.UUID   `json:"id"`
	ItemID    uuid.UUID   `json:"item_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	Severity  string      `json:"severity"`
	Text      string      `json:"text"`
	CreatedAt time.Time   `json:"created_at"`
}

type InventoryScanHistory struct {
	ID        uuid.UUID   `json:"id"`
	ItemID    uuid.UUID   `json:"item_id"`
	ScannedAt time.Time   `json:"scanned_at"`
	ScannedBy pgtype.UUID `json:"scanned_by"`
	Method    string      `json:"method"`
	Result    string      `json:"result"`
	Note      pgtype.Text `json:"note"`
}

type InventoryTask struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	ScopeLocationID pgtype.UUID        `json:"scope_location_id"`
	Status          string             `json:"status"`
	Method          pgtype.Text        `json:"method"`
	PlannedDate     pgtype.Date        `json:"planned_date"`
	CompletedDate   pgtype.Date        `json:"completed_date"`
	AssignedTo      pgtype.UUID        `json:"assigned_to"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	SyncVersion     int64              `json:"sync_version"`
}

type Location struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Name        string             `json:"name"`
	NameEn      pgtype.Text        `json:"name_en"`
	Slug        string             `json:"slug"`
	Level       string             `json:"level"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Path        pgtype.Text        `json:"path"`
	Status      string             `json:"status"`
	Metadata    json.RawMessage    `json:"metadata"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	SyncVersion int64              `json:"sync_version"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Latitude    pgtype.Float8      `json:"latitude"`
	Longitude   pgtype.Float8      `json:"longitude"`
}

type MacAddressCache struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	MacAddress     string             `json:"mac_address"`
	SwitchAssetID  uuid.UUID          `json:"switch_asset_id"`
	PortName       string             `json:"port_name"`
	VlanID         pgtype.Int4        `json:"vlan_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	DetectedRackID pgtype.UUID        `json:"detected_rack_id"`
	FirstSeen      pgtype.Timestamptz `json:"first_seen"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
}

type Metric struct {
	Time     time.Time     `json:"time"`
	AssetID  pgtype.UUID   `json:"asset_id"`
	TenantID pgtype.UUID   `json:"tenant_id"`
	Name     string        `json:"name"`
	Value    pgtype.Float8 `json:"value"`
	Labels   []byte        `json:"labels"`
}

type Metrics1hour struct {
	Bucket   interface{} `json:"bucket"`
	AssetID  pgtype.UUID `json:"asset_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	AvgValue float64     `json:"avg_value"`
	MaxValue interface{} `json:"max_value"`
	MinValue interface{} `json:"min_value"`
}

type Metrics5min struct {
	Bucket   interface{} `json:"bucket"`
	AssetID  pgtype.UUID `json:"asset_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	AvgValue float64     `json:"avg_value"`
	MaxValue interface{} `json:"max_value"`
	MinValue interface{} `json:"min_value"`
}

type Notification struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	UserID       uuid.UUID   `json:"user_id"`
	Type         string      `json:"type"`
	Title        string      `json:"title"`
	Body         pgtype.Text `json:"body"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	IsRead       bool        `json:"is_read"`
	CreatedAt    time.Time   `json:"created_at"`
}

type PredictionModel struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Provider  string          `json:"provider"`
	Config    json.RawMessage `json:"config"`
	Enabled   bool            `json:"enabled"`
	CreatedAt time.Time       `json:"created_at"`
}

type PredictionResult struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ModelID           uuid.UUID          `json:"model_id"`
	AssetID           uuid.UUID          `json:"asset_id"`
	PredictionType    string             `json:"prediction_type"`
	Result            json.RawMessage    `json:"result"`
	Severity          pgtype.Text        `json:"severity"`
	RecommendedAction pgtype.Text        `json:"recommended_action"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         time.Time          `json:"created_at"`
}

type QualityFlag struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	AssetID        uuid.UUID          `json:"asset_id"`
	ReporterType   string             `json:"reporter_type"`
	ReporterID     pgtype.UUID        `json:"reporter_id"`
	Severity       string             `json:"severity"`
	Category       string             `json:"category"`
	Message        string             `json:"message"`
	Status         string             `json:"status"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy     pgtype.UUID        `json:"resolved_by"`
	ResolutionNote pgtype.Text        `json:"resolution_note"`
	CreatedAt      time.Time          `json:"created_at"`
}

type QualityRule struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	CiType     pgtype.Text `json:"ci_type"`
	Dimension  string      `json:"dimension"`
	FieldName  string      `json:"field_name"`
	RuleType   string      `json:"rule_type"`
	RuleConfig []byte      `json:"rule_config"`
	Weight     pgtype.Int4 `json:"weight"`
	Enabled    pgtype.Bool `json:"enabled"`
	CreatedAt  time.Time   `json:"created_at"`
}

type QualityScore struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	AssetID      uuid.UUID      `json:"asset_id"`
	Completeness pgtype.Numeric `json:"completeness"`
	Accuracy     pgtype.Numeric `json:"accuracy"`
	Timeliness   pgtype.Numeric `json:"timeliness"`
	Consistency  pgtype.Numeric `json:"consistency"`
	TotalScore   pgtype.Numeric `json:"total_score"`
	IssueDetails []byte         `json:"issue_details"`
	ScanDate     time.Time      `json:"scan_date"`
}

type Rack struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	LocationID      uuid.UUID          `json:"location_id"`
	Name            string             `json:"name"`
	RowLabel        pgtype.Text        `json:"row_label"`
	TotalU          int32              `json:"total_u"`
	PowerCapacityKw pgtype.Numeric     `json:"power_capacity_kw"`
	Status          string             `json:"status"`
	Tags            []string           `json:"tags"`
	CreatedAt       time.Time          `json:"created_at"`
	SyncVersion     int64              `json:"sync_version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RackNetworkConnection struct {
	ID               uuid.UUID   `json:"id"`
	TenantID         uuid.UUID   `json:"tenant_id"`
	RackID           uuid.UUID   `json:"rack_id"`
	SourcePort       string      `json:"source_port"`
	ConnectedAssetID pgtype.UUID `json:"connected_asset_id"`
	ExternalDevice   pgtype.Text `json:"external_device"`
	Speed            pgtype.Text `json:"speed"`
	Status           pgtype.Text `json:"status"`
	Vlans            []int32     `json:"vlans"`
	ConnectionType   pgtype.Text `json:"connection_type"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type RackSlot struct {
	ID      uuid.UUID `json:"id"`
	RackID  uuid.UUID `json:"rack_id"`
	AssetID uuid.UUID `json:"asset_id"`
	StartU  int32     `json:"start_u"`
	EndU    int32     `json:"end_u"`
	Side    string    `json:"side"`
}

type RcaAnalysis struct {
	ID                uuid.UUID       `json:"id"`
	TenantID          uuid.UUID       `json:"tenant_id"`
	IncidentID        uuid.UUID       `json:"incident_id"`
	ModelID           pgtype.UUID     `json:"model_id"`
	Reasoning         json.RawMessage `json:"reasoning"`
	ConclusionAssetID pgtype.UUID     `json:"conclusion_asset_id"`
	Confidence        pgtype.Numeric  `json:"confidence"`
	HumanVerified     pgtype.Bool     `json:"human_verified"`
	VerifiedBy        pgtype.UUID     `json:"verified_by"`
	CreatedAt         time.Time       `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    pgtype.UUID     `json:"tenant_id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	IsSystem    bool            `json:"is_system"`
	CreatedAt   time.Time       `json:"created_at"`
}

type ScanTarget struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Name          string      `json:"name"`
	Cidrs         []string    `json:"cidrs"`
	CollectorType string      `json:"collector_type"`
	CredentialID  uuid.UUID   `json:"credential_id"`
	Mode          string      `json:"mode"`
	LocationID    pgtype.UUID `json:"location_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type Sensor struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	AssetID         pgtype.UUID        `json:"asset_id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	Location        pgtype.Text        `json:"location"`
	PollingInterval int32              `json:"polling_interval"`
	Enabled         bool               `json:"enabled"`
	Status          string             `json:"status"`
	LastHeartbeat   pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type SwitchPortMapping struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	SwitchAssetID      uuid.UUID          `json:"switch_asset_id"`
	PortName           string             `json:"port_name"`
	ConnectedRackID    pgtype.UUID        `json:"connected_rack_id"`
	ConnectedUPosition pgtype.Int4        `json:"connected_u_position"`
	Description        pgtype.Text        `json:"description"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type SyncConflict struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	LocalVersion  int64              `json:"local_version"`
	RemoteVersion int64              `json:"remote_version"`
	LocalDiff     json.RawMessage    `json:"local_diff"`
	RemoteDiff    json.RawMessage    `json:"remote_diff"`
	Resolution    pgtype.Text        `json:"resolution"`
	ResolvedBy    pgtype.UUID        `json:"resolved_by"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SyncState struct {
	ID              uuid.UUID          `json:"id"`
	NodeID          string             `json:"node_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	EntityType      string             `json:"entity_type"`
	LastSyncVersion pgtype.Int8        `json:"last_sync_version"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	Status          pgtype.Text        `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Status    string          `json:"status"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type UpgradeRule struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	AssetType      string         `json:"asset_type"`
	Category       string         `json:"category"`
	MetricName     string         `json:"metric_name"`
	Threshold      pgtype.Numeric `json:"threshold"`
	DurationDays   int32          `json:"duration_days"`
	Priority       string         `json:"priority"`
	Recommendation string         `json:"recommendation"`
	Enabled        bool           `json:"enabled"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	DeptID            pgtype.UUID        `json:"dept_id"`
	Username          string             `json:"username"`
	DisplayName       string             `json:"display_name"`
	Email             string             `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	PasswordHash      string             `json:"password_hash"`
	Status            string             `json:"status"`
	Source            string             `json:"source"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp       pgtype.Text        `json:"last_login_ip"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	PasswordChangedAt time.Time          `json:"password_changed_at"`
}

type UserRole struct {
	UserID   uuid.UUID `json:"user_id"`
	RoleID   uuid.UUID `json:"role_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type UserSession struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	DeviceType   pgtype.Text        `json:"device_type"`
	Browser      pgtype.Text        `json:"browser"`
	CreatedAt    time.Time          `json:"created_at"`
	LastActiveAt time.Time          `json:"last_active_at"`
	ExpiredAt    pgtype.Timestamptz `json:"expired_at"`
	IsCurrent    bool               `json:"is_current"`
}

type WebhookDeliveriesDlq struct {
	ID             uuid.UUID       `json:"id"`
	SubscriptionID pgtype.UUID     `json:"subscription_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	LastError      string          `json:"last_error"`
	AttemptCount   int32           `json:"attempt_count"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	CreatedAt      time.Time       `json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	EventType      string             `json:"event_type"`
	Payload        json.RawMessage    `json:"payload"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	AttemptNumber  int32              `json:"attempt_number"`
}

type WebhookSubscription struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Name                string             `json:"name"`
	Url                 string             `json:"url"`
	Secret              pgtype.Text        `json:"secret"`
	Events              []string           `json:"events"`
	Enabled             pgtype.Bool        `json:"enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	FilterBia           []string           `json:"filter_bia"`
	SecretEncrypted     []byte             `json:"secret_encrypted"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	DisabledAt          pgtype.Timestamptz `json:"disabled_at"`
}

type WorkOrder struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	Code             string             `json:"code"`
	Title            string             `json:"title"`
	Type             string             `json:"type"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	LocationID       pgtype.UUID        `json:"location_id"`
	AssetID          pgtype.UUID        `json:"asset_id"`
	RequestorID      pgtype.UUID        `json:"requestor_id"`
	AssigneeID       pgtype.UUID        `json:"assignee_id"`
	Description      pgtype.Text        `json:"description"`
	Reason           pgtype.Text        `json:"reason"`
	PredictionID     pgtype.UUID        `json:"prediction_id"`
	ScheduledStart   pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd     pgtype.Timestamptz `json:"scheduled_end"`
	ActualStart      pgtype.Timestamptz `json:"actual_start"`
	ActualEnd        pgtype.Timestamptz `json:"actual_end"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy       pgtype.UUID        `json:"approved_by"`
	SlaDeadline      pgtype.Timestamptz `json:"sla_deadline"`
	SlaWarningSent   bool               `json:"sla_warning_sent"`
	SlaBreached      bool               `json:"sla_breached"`
	SyncVersion      int64              `json:"sync_version"`
	ExecutionStatus  string             `json:"execution_status"`
	GovernanceStatus string             `json:"governance_status"`
}

type WorkOrderComment struct {
	ID        uuid.UUID   `json:"id"`
	OrderID   uuid.UUID   `json:"order_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	Text      string      `json:"text"`
	CreatedAt time.Time   `json:"created_at"`
}

type WorkOrderDedup struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	WorkOrderID uuid.UUID `json:"work_order_id"`
	DedupKind   string    `json:"dedup_kind"`
	DedupKey    string    `json:"dedup_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type WorkOrderLog struct {
	ID         uuid.UUID   `json:"id"`
	OrderID    uuid.UUID   `json:"order_id"`
	Action     string      `json:"action"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   pgtype.Text `json:"to_status"`
	OperatorID pgtype.UUID `json:"operator_id"`
	Comment    pgtype.Text `json:"comment"`
	CreatedAt  time.Time   `json:"created_at"`
}
