// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quality.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const avgLatestQualityScore = `-- name: AvgLatestQualityScore :one
SELECT coalesce(avg(total_score), 0)::float8
FROM (
    SELECT DISTINCT ON (asset_id) total_score
    FROM quality_scores
    WHERE tenant_id = $1
    ORDER BY asset_id, scan_date DESC
) latest
`

// Average of each asset's most-recent total_score. DISTINCT ON picks the
// newest row per asset_id; averaging over that avoids skew from assets
// that were scanned many times vs. a single historical run pulling the
// mean down. Returns 0 when a tenant has no scores yet (coalesce wraps
// the outer avg).
func (q *Queries) AvgLatestQualityScore(ctx context.Context, tenantID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, avgLatestQualityScore, tenantID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const createQualityRule = `-- name: CreateQualityRule :one
INSERT INTO quality_rules (tenant_id, ci_type, dimension, field_name, rule_type, rule_config, weight, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, ci_type, dimension, field_name, rule_type, rule_config, weight, enabled, created_at
`

type CreateQualityRuleParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	CiType     pgtype.Text `json:"ci_type"`
	Dimension  string      `json:"dimension"`
	FieldName  string      `json:"field_name"`
	RuleType   string      `json:"rule_type"`
	RuleConfig []byte      `json:"rule_config"`
	Weight     pgtype.Int4 `json:"weight"`
	Enabled    pgtype.Bool `json:"enabled"`
}

func (q *Queries) CreateQualityRule(ctx context.Context, arg CreateQualityRuleParams) (QualityRule, error) {
	row := q.db.QueryRow(ctx, createQualityRule,
		arg.TenantID,
		arg.CiType,
		arg.Dimension,
		arg.FieldName,
		arg.RuleType,
		arg.RuleConfig,
		arg.Weight,
		arg.Enabled,
	)
	var i QualityRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CiType,
		&i.Dimension,
		&i.FieldName,
		&i.RuleType,
		&i.RuleConfig,
		&i.Weight,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createQualityScore = `-- name: CreateQualityScore :exec
INSERT INTO quality_scores (tenant_id, asset_id, completeness, accuracy, timeliness, consistency, total_score, issue_details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateQualityScoreParams struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	AssetID      uuid.UUID      `json:"asset_id"`
	Completeness pgtype.Numeric `json:"completeness"`
	Accuracy     pgtype.Numeric `json:"accuracy"`
	Timeliness   pgtype.Numeric `json:"timeliness"`
	Consistency  pgtype.Numeric `json:"consistency"`
	TotalScore   pgtype.Numeric `json:"total_score"`
	IssueDetails []byte         `json:"issue_details"`
}

func (q *Queries) CreateQualityScore(ctx context.Context, arg CreateQualityScoreParams) error {
	_, err := q.db.Exec(ctx, createQualityScore,
		arg.TenantID,
		arg.AssetID,
		arg.Completeness,
		arg.Accuracy,
		arg.Timeliness,
		arg.Consistency,
		arg.TotalScore,
		arg.IssueDetails,
	)
	return err
}

const getAssetQualityHistory = `-- name: GetAssetQualityHistory :many
SELECT id, tenant_id, asset_id, completeness, accuracy, timeliness, consistency, total_score, issue_details, scan_date FROM quality_scores
WHERE asset_id = $1
ORDER BY scan_date DESC
LIMIT 30
`

func (q *Queries) GetAssetQualityHistory(ctx context.Context, assetID uuid.UUID) ([]QualityScore, error) {
	rows, err := q.db.Query(ctx, getAssetQualityHistory, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityScore{}
	for rows.Next() {
		var i QualityScore
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.Completeness,
			&i.Accuracy,
			&i.Timeliness,
			&i.Consistency,
			&i.TotalScore,
			&i.IssueDetails,
			&i.ScanDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQualityDashboard = `-- name: GetQualityDashboard :one
SELECT
    coalesce(avg(total_score), 0) as avg_total,
    coalesce(avg(completeness), 0) as avg_completeness,
    coalesce(avg(accuracy), 0) as avg_accuracy,
    coalesce(avg(timeliness), 0) as avg_timeliness,
    coalesce(avg(consistency), 0) as avg_consistency,
    count(*) as total_scanned
FROM quality_scores
WHERE tenant_id = $1
  AND scan_date > now() - interval '24 hours'
`

type GetQualityDashboardRow struct {
	AvgTotal        interface{} `json:"avg_total"`
	AvgCompleteness interface{} `json:"avg_completeness"`
	AvgAccuracy     interface{} `json:"avg_accuracy"`
	AvgTimeliness   interface{} `json:"avg_timeliness"`
	AvgConsistency  interface{} `json:"avg_consistency"`
	TotalScanned    int64       `json:"total_scanned"`
}

func (q *Queries) GetQualityDashboard(ctx context.Context, tenantID uuid.UUID) (GetQualityDashboardRow, error) {
	row := q.db.QueryRow(ctx, getQualityDashboard, tenantID)
	var i GetQualityDashboardRow
	err := row.Scan(
		&i.AvgTotal,
		&i.AvgCompleteness,
		&i.AvgAccuracy,
		&i.AvgTimeliness,
		&i.AvgConsistency,
		&i.TotalScanned,
	)
	return i, err
}

const getWorstAssets = `-- name: GetWorstAssets :many
SELECT qs.id, qs.tenant_id, qs.asset_id, qs.completeness, qs.accuracy, qs.timeliness, qs.consistency, qs.total_score, qs.issue_details, qs.scan_date, a.name as asset_name, a.asset_tag
FROM quality_scores qs
JOIN assets a ON qs.asset_id = a.id
WHERE qs.tenant_id = $1
  AND qs.scan_date > now() - interval '24 hours'
ORDER BY qs.total_score ASC
LIMIT 10
`

type GetWorstAssetsRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	AssetID      uuid.UUID      `json:"asset_id"`
	Completeness pgtype.Numeric `json:"completeness"`
	Accuracy     pgtype.Numeric `json:"accuracy"`
	Timeliness   pgtype.Numeric `json:"timeliness"`
	Consistency  pgtype.Numeric `json:"consistency"`
	TotalScore   pgtype.Numeric `json:"total_score"`
	IssueDetails []byte         `json:"issue_details"`
	ScanDate     time.Time      `json:"scan_date"`
	AssetName    string         `json:"asset_name"`
	AssetTag     string         `json:"asset_tag"`
}

func (q *Queries) GetWorstAssets(ctx context.Context, tenantID uuid.UUID) ([]GetWorstAssetsRow, error) {
	rows, err := q.db.Query(ctx, getWorstAssets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorstAssetsRow{}
	for rows.Next() {
		var i GetWorstAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.Completeness,
			&i.Accuracy,
			&i.Timeliness,
			&i.Consistency,
			&i.TotalScore,
			&i.IssueDetails,
			&i.ScanDate,
			&i.AssetName,
			&i.AssetTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityRules = `-- name: ListQualityRules :many
SELECT id, tenant_id, ci_type, dimension, field_name, rule_type, rule_config, weight, enabled, created_at FROM quality_rules
WHERE tenant_id = $1
ORDER BY dimension, field_name
`

func (q *Queries) ListQualityRules(ctx context.Context, tenantID uuid.UUID) ([]QualityRule, error) {
	rows, err := q.db.Query(ctx, listQualityRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityRule{}
	for rows.Next() {
		var i QualityRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CiType,
			&i.Dimension,
			&i.FieldName,
			&i.RuleType,
			&i.RuleConfig,
			&i.Weight,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
