// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rack_slots.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlotConflict = `-- name: CheckSlotConflict :one
SELECT count(*) FROM rack_slots
WHERE rack_id = $1
  AND side = $2
  AND NOT (end_u < $3 OR start_u > $4)
`

type CheckSlotConflictParams struct {
	RackID uuid.UUID `json:"rack_id"`
	Side   string    `json:"side"`
	EndU   int32     `json:"end_u"`
	StartU int32     `json:"start_u"`
}

func (q *Queries) CheckSlotConflict(ctx context.Context, arg CheckSlotConflictParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkSlotConflict,
		arg.RackID,
		arg.Side,
		arg.EndU,
		arg.StartU,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRackSlot = `-- name: CreateRackSlot :one
INSERT INTO rack_slots (rack_id, asset_id, start_u, end_u, side)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, rack_id, asset_id, start_u, end_u, side
`

type CreateRackSlotParams struct {
	RackID  uuid.UUID `json:"rack_id"`
	AssetID uuid.UUID `json:"asset_id"`
	StartU  int32     `json:"start_u"`
	EndU    int32     `json:"end_u"`
	Side    string    `json:"side"`
}

func (q *Queries) CreateRackSlot(ctx context.Context, arg CreateRackSlotParams) (RackSlot, error) {
	row := q.db.QueryRow(ctx, createRackSlot,
		arg.RackID,
		arg.AssetID,
		arg.StartU,
		arg.EndU,
		arg.Side,
	)
	var i RackSlot
	err := row.Scan(
		&i.ID,
		&i.RackID,
		&i.AssetID,
		&i.StartU,
		&i.EndU,
		&i.Side,
	)
	return i, err
}

const deleteRackSlot = `-- name: DeleteRackSlot :exec
DELETE FROM rack_slots
WHERE id = $1
  AND rack_id IN (SELECT r.id FROM racks r WHERE r.tenant_id = $2)
`

type DeleteRackSlotParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRackSlot(ctx context.Context, arg DeleteRackSlotParams) error {
	_, err := q.db.Exec(ctx, deleteRackSlot, arg.ID, arg.TenantID)
	return err
}

const listRackSlots = `-- name: ListRackSlots :many
SELECT rs.id, rs.rack_id, rs.asset_id, rs.start_u, rs.end_u, rs.side,
       a.name as asset_name, a.asset_tag, a.type as asset_type, a.bia_level
FROM rack_slots rs
LEFT JOIN assets a ON rs.asset_id = a.id
WHERE rs.rack_id = $1
ORDER BY rs.start_u
`

type ListRackSlotsRow struct {
	ID        uuid.UUID   `json:"id"`
	RackID    uuid.UUID   `json:"rack_id"`
	AssetID   uuid.UUID   `json:"asset_id"`
	StartU    int32       `json:"start_u"`
	EndU      int32       `json:"end_u"`
	Side      string      `json:"side"`
	AssetName pgtype.Text `json:"asset_name"`
	AssetTag  pgtype.Text `json:"asset_tag"`
	AssetType pgtype.Text `json:"asset_type"`
	BiaLevel  pgtype.Text `json:"bia_level"`
}

func (q *Queries) ListRackSlots(ctx context.Context, rackID uuid.UUID) ([]ListRackSlotsRow, error) {
	rows, err := q.db.Query(ctx, listRackSlots, rackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRackSlotsRow{}
	for rows.Next() {
		var i ListRackSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.RackID,
			&i.AssetID,
			&i.StartU,
			&i.EndU,
			&i.Side,
			&i.AssetName,
			&i.AssetTag,
			&i.AssetType,
			&i.BiaLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
