// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: racks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRacksUnderLocation = `-- name: CountRacksUnderLocation :one
SELECT count(*) FROM racks r
JOIN locations l ON r.location_id = l.id
WHERE r.tenant_id = $1
  AND l.path <@ (SELECT loc.path FROM locations loc WHERE loc.id = $2)::ltree
`

type CountRacksUnderLocationParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

// Count all racks under a location and all its descendants (using ltree)
func (q *Queries) CountRacksUnderLocation(ctx context.Context, arg CountRacksUnderLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRacksUnderLocation, arg.TenantID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRack = `-- name: CreateRack :one
INSERT INTO racks (
    tenant_id, location_id, name, row_label,
    total_u, power_capacity_kw, status, tags
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
) RETURNING id, tenant_id, location_id, name, row_label, total_u, power_capacity_kw, status, tags, created_at, sync_version, deleted_at
`

type CreateRackParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	LocationID      uuid.UUID      `json:"location_id"`
	Name            string         `json:"name"`
	RowLabel        pgtype.Text    `json:"row_label"`
	TotalU          int32          `json:"total_u"`
	PowerCapacityKw pgtype.Numeric `json:"power_capacity_kw"`
	Status          string         `json:"status"`
	Tags            []string       `json:"tags"`
}

func (q *Queries) CreateRack(ctx context.Context, arg CreateRackParams) (Rack, error) {
	row := q.db.QueryRow(ctx, createRack,
		arg.TenantID,
		arg.LocationID,
		arg.Name,
		arg.RowLabel,
		arg.TotalU,
		arg.PowerCapacityKw,
		arg.Status,
		arg.Tags,
	)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.RowLabel,
		&i.TotalU,
		&i.PowerCapacityKw,
		&i.Status,
		&i.Tags,
		&i.CreatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRack = `-- name: DeleteRack :exec
DELETE FROM racks WHERE id = $1 AND tenant_id = $2
`

type DeleteRackParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRack(ctx context.Context, arg DeleteRackParams) error {
	_, err := q.db.Exec(ctx, deleteRack, arg.ID, arg.TenantID)
	return err
}

const getRack = `-- name: GetRack :one
SELECT id, tenant_id, location_id, name, row_label, total_u, power_capacity_kw, status, tags, created_at, sync_version, deleted_at FROM racks WHERE id = $1 AND tenant_id = $2
`

type GetRackParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetRack(ctx context.Context, arg GetRackParams) (Rack, error) {
	row := q.db.QueryRow(ctx, getRack, arg.ID, arg.TenantID)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.RowLabel,
		&i.TotalU,
		&i.PowerCapacityKw,
		&i.Status,
		&i.Tags,
		&i.CreatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getRackOccupancy = `-- name: GetRackOccupancy :one
SELECT r.total_u, COALESCE(SUM(rs.end_u - rs.start_u + 1), 0)::int AS used_u
FROM racks r
LEFT JOIN rack_slots rs ON rs.rack_id = r.id
WHERE r.id = $1
GROUP BY r.id
`

type GetRackOccupancyRow struct {
	TotalU int32 `json:"total_u"`
	UsedU  int32 `json:"used_u"`
}

func (q *Queries) GetRackOccupancy(ctx context.Context, id uuid.UUID) (GetRackOccupancyRow, error) {
	row := q.db.QueryRow(ctx, getRackOccupancy, id)
	var i GetRackOccupancyRow
	err := row.Scan(&i.TotalU, &i.UsedU)
	return i, err
}

const listAssetsByRack = `-- name: ListAssetsByRack :many
SELECT a.id, a.tenant_id, a.asset_tag, a.property_number, a.control_number, a.name, a.type, a.sub_type, a.status, a.bia_level, a.location_id, a.rack_id, a.vendor, a.model, a.serial_number, a.attributes, a.tags, a.created_at, a.updated_at, a.ip_address, a.deleted_at, a.sync_version, a.bmc_ip, a.bmc_type, a.bmc_firmware, a.purchase_date, a.purchase_cost, a.warranty_start, a.warranty_end, a.warranty_vendor, a.warranty_contract, a.expected_lifespan_months, a.eol_date FROM assets a
WHERE a.rack_id = $1
ORDER BY a.name
`

func (q *Queries) ListAssetsByRack(ctx context.Context, rackID pgtype.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByRack, rackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetTag,
			&i.PropertyNumber,
			&i.ControlNumber,
			&i.Name,
			&i.Type,
			&i.SubType,
			&i.Status,
			&i.BiaLevel,
			&i.LocationID,
			&i.RackID,
			&i.Vendor,
			&i.Model,
			&i.SerialNumber,
			&i.Attributes,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.DeletedAt,
			&i.SyncVersion,
			&i.BmcIp,
			&i.BmcType,
			&i.BmcFirmware,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyStart,
			&i.WarrantyEnd,
			&i.WarrantyVendor,
			&i.WarrantyContract,
			&i.ExpectedLifespanMonths,
			&i.EolDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacksByLocation = `-- name: ListRacksByLocation :many
SELECT r.id, r.tenant_id, r.location_id, r.name, r.row_label, r.total_u, r.power_capacity_kw, r.status, r.tags, r.created_at, r.sync_version, r.deleted_at FROM racks r
JOIN locations l ON r.location_id = l.id
WHERE l.path <@ (SELECT loc.path FROM locations loc WHERE loc.id = $1)::ltree
ORDER BY r.name
`

// Returns racks at this location AND all descendant locations (via ltree)
func (q *Queries) ListRacksByLocation(ctx context.Context, id uuid.UUID) ([]Rack, error) {
	rows, err := q.db.Query(ctx, listRacksByLocation, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rack{}
	for rows.Next() {
		var i Rack
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.Name,
			&i.RowLabel,
			&i.TotalU,
			&i.PowerCapacityKw,
			&i.Status,
			&i.Tags,
			&i.CreatedAt,
			&i.SyncVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRack = `-- name: UpdateRack :one
UPDATE racks SET
    name              = COALESCE($1, name),
    row_label         = COALESCE($2, row_label),
    total_u           = COALESCE($3, total_u),
    power_capacity_kw = COALESCE($4, power_capacity_kw),
    status            = COALESCE($5, status),
    tags              = COALESCE($6, tags)
WHERE id = $7
RETURNING id, tenant_id, location_id, name, row_label, total_u, power_capacity_kw, status, tags, created_at, sync_version, deleted_at
`

type UpdateRackParams struct {
	Name            pgtype.Text    `json:"name"`
	RowLabel        pgtype.Text    `json:"row_label"`
	TotalU          pgtype.Int4    `json:"total_u"`
	PowerCapacityKw pgtype.Numeric `json:"power_capacity_kw"`
	Status          pgtype.Text    `json:"status"`
	Tags            []string       `json:"tags"`
	ID              uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateRack(ctx context.Context, arg UpdateRackParams) (Rack, error) {
	row := q.db.QueryRow(ctx, updateRack,
		arg.Name,
		arg.RowLabel,
		arg.TotalU,
		arg.PowerCapacityKw,
		arg.Status,
		arg.Tags,
		arg.ID,
	)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.RowLabel,
		&i.TotalU,
		&i.PowerCapacityKw,
		&i.Status,
		&i.Tags,
		&i.CreatedAt,
		&i.SyncVersion,
		&i.DeletedAt,
	)
	return i, err
}
