// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rack_network_connections.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRackNetworkConnection = `-- name: CreateRackNetworkConnection :exec
INSERT INTO rack_network_connections
    (id, rack_id, tenant_id, source_port, connected_asset_id, external_device,
     speed, status, vlans, connection_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateRackNetworkConnectionParams struct {
	ID               uuid.UUID   `json:"id"`
	RackID           uuid.UUID   `json:"rack_id"`
	TenantID         uuid.UUID   `json:"tenant_id"`
	SourcePort       string      `json:"source_port"`
	ConnectedAssetID pgtype.UUID `json:"connected_asset_id"`
	ExternalDevice   pgtype.Text `json:"external_device"`
	Speed            pgtype.Text `json:"speed"`
	Status           pgtype.Text `json:"status"`
	Vlans            []int32     `json:"vlans"`
	ConnectionType   pgtype.Text `json:"connection_type"`
}

// Insert assumes the handler has already validated tenant ownership of
// rack_id. tenant_id is persisted for index locality and FK coherence.
func (q *Queries) CreateRackNetworkConnection(ctx context.Context, arg CreateRackNetworkConnectionParams) error {
	_, err := q.db.Exec(ctx, createRackNetworkConnection,
		arg.ID,
		arg.RackID,
		arg.TenantID,
		arg.SourcePort,
		arg.ConnectedAssetID,
		arg.ExternalDevice,
		arg.Speed,
		arg.Status,
		arg.Vlans,
		arg.ConnectionType,
	)
	return err
}

const deleteRackNetworkConnection = `-- name: DeleteRackNetworkConnection :execrows
DELETE FROM rack_network_connections rnc
WHERE rnc.id = $1
  AND rnc.rack_id = $2
  AND rnc.rack_id IN (SELECT r.id FROM racks r WHERE r.tenant_id = $3 AND r.deleted_at IS NULL)
`

type DeleteRackNetworkConnectionParams struct {
	ID       uuid.UUID `json:"id"`
	RackID   uuid.UUID `json:"rack_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// "Fix #10" invariant preserved: the connection is only deletable if
// its rack_id belongs to a rack owned by the caller's tenant.
func (q *Queries) DeleteRackNetworkConnection(ctx context.Context, arg DeleteRackNetworkConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRackNetworkConnection, arg.ID, arg.RackID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRackNetworkConnections = `-- name: ListRackNetworkConnections :many

SELECT
    rnc.id,
    rnc.source_port,
    COALESCE(a.name, rnc.external_device, '') AS device,
    rnc.connected_asset_id,
    COALESCE(rnc.external_device, '')         AS external_device,
    COALESCE(rnc.speed, '')                   AS speed,
    COALESCE(rnc.status, '')                  AS status,
    COALESCE(rnc.vlans, '{}')::int[]          AS vlans,
    COALESCE(rnc.connection_type, '')         AS connection_type
FROM rack_network_connections rnc
JOIN racks r ON rnc.rack_id = r.id AND r.tenant_id = $2 AND r.deleted_at IS NULL
LEFT JOIN assets a ON rnc.connected_asset_id = a.id
WHERE rnc.rack_id = $1
ORDER BY rnc.source_port
`

type ListRackNetworkConnectionsParams struct {
	RackID   uuid.UUID `json:"rack_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListRackNetworkConnectionsRow struct {
	ID               uuid.UUID   `json:"id"`
	SourcePort       string      `json:"source_port"`
	Device           string      `json:"device"`
	ConnectedAssetID pgtype.UUID `json:"connected_asset_id"`
	ExternalDevice   string      `json:"external_device"`
	Speed            string      `json:"speed"`
	Status           string      `json:"status"`
	Vlans            []int32     `json:"vlans"`
	ConnectionType   string      `json:"connection_type"`
}

// rack_network_connections: per-rack network port/connection records.
// Tenant isolation: rack_network_connections carries its own tenant_id
// column and the parent racks table also carries tenant_id. Every
// query below joins (or filters) on both rack_id + racks.tenant_id so
// a forged rack_id cannot reach another tenant's rows.
// The JOIN on racks.tenant_id is what actually enforces tenancy —
// rnc.tenant_id alone is not load-bearing here, but the join filter
// on the rack preserves the "Fix #11" invariant from the pre-sqlc
// code verbatim.
func (q *Queries) ListRackNetworkConnections(ctx context.Context, arg ListRackNetworkConnectionsParams) ([]ListRackNetworkConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listRackNetworkConnections, arg.RackID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRackNetworkConnectionsRow{}
	for rows.Next() {
		var i ListRackNetworkConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourcePort,
			&i.Device,
			&i.ConnectedAssetID,
			&i.ExternalDevice,
			&i.Speed,
			&i.Status,
			&i.Vlans,
			&i.ConnectionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
