// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sync_conflicts.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const autoExpireStaleSyncConflicts = `-- name: AutoExpireStaleSyncConflicts :execrows
UPDATE sync_conflicts
SET resolution = 'auto_expired', resolved_at = now()
WHERE resolution = 'pending' AND created_at < now() - interval '7 days'
`

// cross-tenant: runs on a background timer to mark all conflicts older than
// 7 days as auto-expired. The tenant dimension is preserved on each row but
// the sweep itself is intentionally tenant-wide.
func (q *Queries) AutoExpireStaleSyncConflicts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, autoExpireStaleSyncConflicts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingConflictsByTenantNearSLA = `-- name: CountPendingConflictsByTenantNearSLA :many
SELECT tenant_id, count(*)::bigint AS count
FROM sync_conflicts
WHERE resolution = 'pending'
  AND created_at < now() - interval '3 days'
  AND created_at >= now() - interval '4 days'
GROUP BY tenant_id
`

type CountPendingConflictsByTenantNearSLARow struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Count    int64     `json:"count"`
}

// Scans conflicts that crossed the 3-day SLA warning threshold but haven't
// yet hit the 7-day auto-expire. Used by the workflow subscriber to ping
// ops-admins. Cross-tenant on purpose — the caller then looks up each
// tenant's ops-admins and files per-tenant notifications.
func (q *Queries) CountPendingConflictsByTenantNearSLA(ctx context.Context) ([]CountPendingConflictsByTenantNearSLARow, error) {
	rows, err := q.db.Query(ctx, countPendingConflictsByTenantNearSLA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPendingConflictsByTenantNearSLARow{}
	for rows.Next() {
		var i CountPendingConflictsByTenantNearSLARow
		if err := rows.Scan(&i.TenantID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSyncConflict = `-- name: GetPendingSyncConflict :one
SELECT entity_type, entity_id, remote_diff
FROM sync_conflicts
WHERE id = $1 AND tenant_id = $2 AND resolution = 'pending'
`

type GetPendingSyncConflictParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPendingSyncConflictRow struct {
	EntityType string          `json:"entity_type"`
	EntityID   uuid.UUID       `json:"entity_id"`
	RemoteDiff json.RawMessage `json:"remote_diff"`
}

// Used by the resolve handler. Tenant-scoped so a resolve attempt against
// another tenant's conflict yields ErrNoRows (maps to HTTP 404 in the
// handler, which is how cross-tenant IDOR is blocked).
func (q *Queries) GetPendingSyncConflict(ctx context.Context, arg GetPendingSyncConflictParams) (GetPendingSyncConflictRow, error) {
	row := q.db.QueryRow(ctx, getPendingSyncConflict, arg.ID, arg.TenantID)
	var i GetPendingSyncConflictRow
	err := row.Scan(&i.EntityType, &i.EntityID, &i.RemoteDiff)
	return i, err
}

const listPendingSyncConflicts = `-- name: ListPendingSyncConflicts :many

SELECT id, entity_type, entity_id, local_version, remote_version,
       local_diff, remote_diff, created_at
FROM sync_conflicts
WHERE tenant_id = $1 AND resolution = 'pending'
ORDER BY created_at
`

type ListPendingSyncConflictsRow struct {
	ID            uuid.UUID          `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	LocalVersion  int64              `json:"local_version"`
	RemoteVersion int64              `json:"remote_version"`
	LocalDiff     json.RawMessage    `json:"local_diff"`
	RemoteDiff    json.RawMessage    `json:"remote_diff"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// sync_conflicts: manual-intervention channel.
//
// Rows are inserted by operator tooling when a human dispute needs to be
// arbitrated; automatic sync uses last-write-wins and never writes here.
// See docs/SYNC_CONFLICT.md for the full policy.
func (q *Queries) ListPendingSyncConflicts(ctx context.Context, tenantID uuid.UUID) ([]ListPendingSyncConflictsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSyncConflicts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSyncConflictsRow{}
	for rows.Next() {
		var i ListPendingSyncConflictsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.LocalVersion,
			&i.RemoteVersion,
			&i.LocalDiff,
			&i.RemoteDiff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSyncConflict = `-- name: ResolveSyncConflict :exec
UPDATE sync_conflicts
SET resolution = $1, resolved_by = $2, resolved_at = now()
WHERE id = $3 AND tenant_id = $4
`

type ResolveSyncConflictParams struct {
	Resolution pgtype.Text `json:"resolution"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
}

// Marks a pending conflict as resolved. Tenant-scoped as a second guard
// after GetPendingSyncConflict — even if a caller bypasses the read path,
// this UPDATE still filters by tenant_id.
func (q *Queries) ResolveSyncConflict(ctx context.Context, arg ResolveSyncConflictParams) error {
	_, err := q.db.Exec(ctx, resolveSyncConflict,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ID,
		arg.TenantID,
	)
	return err
}
