// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSyncStateByNode = `-- name: CountSyncStateByNode :one
SELECT count(*) FROM sync_state WHERE node_id = $1
`

// cross-tenant: agent.Start probe — checks whether ANY sync_state row exists
// for this edge node so it can detect a first-boot. The node_id namespace is
// operator-controlled, not tenant-controlled.
func (q *Queries) CountSyncStateByNode(ctx context.Context, nodeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSyncStateByNode, nodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStaleSyncStates = `-- name: ListStaleSyncStates :many
SELECT node_id, tenant_id, entity_type, last_sync_version, last_sync_at
FROM sync_state
WHERE status = 'active' AND last_sync_at < now() - interval '1 hour'
`

type ListStaleSyncStatesRow struct {
	NodeID          string             `json:"node_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	EntityType      string             `json:"entity_type"`
	LastSyncVersion pgtype.Int8        `json:"last_sync_version"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
}

// cross-tenant: the central reconciler fans out to every tenant to find
// stale edges. Returned rows still include tenant_id so downstream logic
// can scope its follow-up writes when needed.
func (q *Queries) ListStaleSyncStates(ctx context.Context) ([]ListStaleSyncStatesRow, error) {
	rows, err := q.db.Query(ctx, listStaleSyncStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleSyncStatesRow{}
	for rows.Next() {
		var i ListStaleSyncStatesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.TenantID,
			&i.EntityType,
			&i.LastSyncVersion,
			&i.LastSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncStatesByTenant = `-- name: ListSyncStatesByTenant :many

SELECT node_id, entity_type, last_sync_version, last_sync_at, status, error_message
FROM sync_state
WHERE tenant_id = $1
ORDER BY node_id, entity_type
`

type ListSyncStatesByTenantRow struct {
	NodeID          string             `json:"node_id"`
	EntityType      string             `json:"entity_type"`
	LastSyncVersion pgtype.Int8        `json:"last_sync_version"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	Status          pgtype.Text        `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}

// sync_state: per-node × entity-type sync watermark.
//
// A unique (node_id, entity_type) row tracks the last_sync_version that a
// given edge node has successfully applied for a given entity_type within
// a specific tenant. Rows are scoped by tenant_id except where the central
// reconciler must sweep across every tenant (ListStaleSyncStates), which
// is explicitly documented as cross-tenant.
func (q *Queries) ListSyncStatesByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListSyncStatesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listSyncStatesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncStatesByTenantRow{}
	for rows.Next() {
		var i ListSyncStatesByTenantRow
		if err := rows.Scan(
			&i.NodeID,
			&i.EntityType,
			&i.LastSyncVersion,
			&i.LastSyncAt,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncStatesByTenantEntity = `-- name: ListSyncStatesByTenantEntity :many
SELECT node_id, last_sync_version
FROM sync_state
WHERE tenant_id = $1 AND entity_type = $2
`

type ListSyncStatesByTenantEntityParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EntityType string    `json:"entity_type"`
}

type ListSyncStatesByTenantEntityRow struct {
	NodeID          string      `json:"node_id"`
	LastSyncVersion pgtype.Int8 `json:"last_sync_version"`
}

func (q *Queries) ListSyncStatesByTenantEntity(ctx context.Context, arg ListSyncStatesByTenantEntityParams) ([]ListSyncStatesByTenantEntityRow, error) {
	rows, err := q.db.Query(ctx, listSyncStatesByTenantEntity, arg.TenantID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncStatesByTenantEntityRow{}
	for rows.Next() {
		var i ListSyncStatesByTenantEntityRow
		if err := rows.Scan(&i.NodeID, &i.LastSyncVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSyncStateError = `-- name: MarkSyncStateError :exec
UPDATE sync_state
SET status = 'error', error_message = $3
WHERE node_id = $1 AND entity_type = $2
`

type MarkSyncStateErrorParams struct {
	NodeID       string      `json:"node_id"`
	EntityType   string      `json:"entity_type"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkSyncStateError(ctx context.Context, arg MarkSyncStateErrorParams) error {
	_, err := q.db.Exec(ctx, markSyncStateError, arg.NodeID, arg.EntityType, arg.ErrorMessage)
	return err
}

const updateSyncStateHeartbeat = `-- name: UpdateSyncStateHeartbeat :exec
UPDATE sync_state
SET last_sync_at = now()
WHERE node_id = $1 AND entity_type = $2
`

type UpdateSyncStateHeartbeatParams struct {
	NodeID     string `json:"node_id"`
	EntityType string `json:"entity_type"`
}

// Resets last_sync_at when the reconciler confirms a node is caught up.
// Keyed by (node_id, entity_type) which is the table's unique key.
func (q *Queries) UpdateSyncStateHeartbeat(ctx context.Context, arg UpdateSyncStateHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateSyncStateHeartbeat, arg.NodeID, arg.EntityType)
	return err
}

const upsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO sync_state (node_id, tenant_id, entity_type, last_sync_version, last_sync_at, status)
VALUES ($1, $2, $3, $4, now(), 'active')
ON CONFLICT (node_id, entity_type) DO UPDATE SET
  last_sync_version = GREATEST(sync_state.last_sync_version, EXCLUDED.last_sync_version),
  last_sync_at = now(),
  status = 'active'
`

type UpsertSyncStateParams struct {
	NodeID          string      `json:"node_id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	EntityType      string      `json:"entity_type"`
	LastSyncVersion pgtype.Int8 `json:"last_sync_version"`
}

// Used by the edge agent after applying an envelope. GREATEST ensures the
// watermark only moves forward even if an older envelope is re-played.
func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState,
		arg.NodeID,
		arg.TenantID,
		arg.EntityType,
		arg.LastSyncVersion,
	)
	return err
}

const upsertSyncStateAbsolute = `-- name: UpsertSyncStateAbsolute :exec
INSERT INTO sync_state (node_id, tenant_id, entity_type, last_sync_version, last_sync_at, status)
VALUES ($1, $2, $3, $4, now(), 'active')
ON CONFLICT (node_id, entity_type) DO UPDATE SET
  last_sync_version = EXCLUDED.last_sync_version,
  last_sync_at = now()
`

type UpsertSyncStateAbsoluteParams struct {
	NodeID          string      `json:"node_id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	EntityType      string      `json:"entity_type"`
	LastSyncVersion pgtype.Int8 `json:"last_sync_version"`
}

// Variant used by updateSyncState: writes the current MAX(sync_version)
// directly without GREATEST. When the agent probes the local max, that
// value is already the latest, so "forward-only" is guaranteed by the
// caller — using the explicit assignment avoids masking drift.
func (q *Queries) UpsertSyncStateAbsolute(ctx context.Context, arg UpsertSyncStateAbsoluteParams) error {
	_, err := q.db.Exec(ctx, upsertSyncStateAbsolute,
		arg.NodeID,
		arg.TenantID,
		arg.EntityType,
		arg.LastSyncVersion,
	)
	return err
}
