// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE tenant_id = $1
`

func (q *Queries) CountUsers(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id, dept_id, username, display_name, email,
    phone, password_hash, status, source
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
) RETURNING id, tenant_id, dept_id, username, display_name, email, phone, password_hash, status, source, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	DeptID       pgtype.UUID `json:"dept_id"`
	Username     string      `json:"username"`
	DisplayName  string      `json:"display_name"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash string      `json:"password_hash"`
	Status       string      `json:"status"`
	Source       string      `json:"source"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.DeptID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Status,
		arg.Source,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeptID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, dept_id, username, display_name, email, phone, password_hash, status, source, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeptID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, tenant_id, dept_id, username, display_name, email, phone, password_hash, status, source, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeptID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, dept_id, username, display_name, email, phone, password_hash, status, source, created_at, updated_at FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeptID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.Status,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    dept_id       = COALESCE($1, dept_id),
    display_name  = COALESCE($2, display_name),
    email         = COALESCE($3, email),
    phone         = COALESCE($4, phone),
    password_hash = COALESCE($5, password_hash),
    status        = COALESCE($6, status),
    updated_at    = now()
WHERE id = $7
RETURNING id, tenant_id, dept_id, username, display_name, email, phone, password_hash, status, source, created_at, updated_at
`

type UpdateUserParams struct {
	DeptID       pgtype.UUID `json:"dept_id"`
	DisplayName  pgtype.Text `json:"display_name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Status       pgtype.Text `json:"status"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DeptID,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Status,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeptID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
