// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearCurrentUserSessions = `-- name: ClearCurrentUserSessions :exec
UPDATE user_sessions SET is_current = false WHERE user_id = $1
`

// cross-tenant: by user_id. Called on login to mark all existing
// sessions as non-current before inserting the fresh one.
func (q *Queries) ClearCurrentUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCurrentUserSessions, userID)
	return err
}

const deleteOldUserSessions = `-- name: DeleteOldUserSessions :execrows
DELETE FROM user_sessions WHERE created_at < now() - interval '30 days'
`

// cross-tenant by design: hourly cleanup sweep deletes sessions older
// than 30 days regardless of tenant.
func (q *Queries) DeleteOldUserSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldUserSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireIdleUserSessions = `-- name: ExpireIdleUserSessions :execrows
UPDATE user_sessions
SET expired_at = now()
WHERE expired_at IS NULL
  AND last_active_at < now() - interval '7 days'
`

// cross-tenant by design: hourly cleanup sweep marks sessions whose
// last_active_at is older than 7 days as expired.
func (q *Queries) ExpireIdleUserSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireIdleUserSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO user_sessions (user_id, ip_address, user_agent, device_type, browser, is_current)
VALUES ($1, $2, $3, $4, $5, true)
`

type InsertUserSessionParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	DeviceType pgtype.Text `json:"device_type"`
	Browser    pgtype.Text `json:"browser"`
}

// cross-tenant: by user_id. Called on successful login. is_current
// defaults to true for the session just created.
func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceType,
		arg.Browser,
	)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many

SELECT id, ip_address, device_type, browser, created_at, last_active_at, is_current
FROM user_sessions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 20
`

type ListUserSessionsRow struct {
	ID           uuid.UUID   `json:"id"`
	IpAddress    pgtype.Text `json:"ip_address"`
	DeviceType   pgtype.Text `json:"device_type"`
	Browser      pgtype.Text `json:"browser"`
	CreatedAt    time.Time   `json:"created_at"`
	LastActiveAt time.Time   `json:"last_active_at"`
	IsCurrent    bool        `json:"is_current"`
}

// user_sessions: per-user browser/session registry. The table has NO
// tenant_id column — isolation is by user_id (and users themselves are
// tenant-scoped). All queries below are therefore "cross-tenant" in the
// strict TenantScoped sense; callers go through pool.* and own their
// own authorization check before issuing queries.
// cross-tenant: user_sessions has no tenant_id. Handler enforces that
// the caller is either listing their own sessions or is admin.
func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.DeviceType,
			&i.Browser,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimUserSessionsPerUser = `-- name: TrimUserSessionsPerUser :execrows
DELETE FROM user_sessions WHERE id IN (
    SELECT id FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) AS rn
        FROM user_sessions
    ) ranked WHERE rn > 20
)
`

// cross-tenant by design: keeps only the 20 most recent sessions per
// user_id, deleting the excess. Run hourly by the cleanup loop.
func (q *Queries) TrimUserSessionsPerUser(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, trimUserSessionsPerUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
