// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_orders.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkOrders = `-- name: CountWorkOrders :one
SELECT count(*) FROM work_orders
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR asset_id = $3)
`

type CountWorkOrdersParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) CountWorkOrders(ctx context.Context, arg CountWorkOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkOrders, arg.TenantID, arg.Status, arg.AssetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO work_orders (
    tenant_id, code, title, type, status, priority,
    location_id, asset_id, requestor_id, assignee_id,
    description, reason, prediction_id,
    scheduled_start, scheduled_end
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15
) RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at
`

type CreateWorkOrderParams struct {
	TenantID       uuid.UUID          `json:"tenant_id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	LocationID     pgtype.UUID        `json:"location_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	RequestorID    pgtype.UUID        `json:"requestor_id"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	Description    pgtype.Text        `json:"description"`
	Reason         pgtype.Text        `json:"reason"`
	PredictionID   pgtype.UUID        `json:"prediction_id"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd   pgtype.Timestamptz `json:"scheduled_end"`
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.TenantID,
		arg.Code,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.LocationID,
		arg.AssetID,
		arg.RequestorID,
		arg.AssigneeID,
		arg.Description,
		arg.Reason,
		arg.PredictionID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkOrderLog = `-- name: CreateWorkOrderLog :one
INSERT INTO work_order_logs (
    order_id, action, from_status, to_status,
    operator_id, comment
) VALUES (
    $1, $2, $3, $4,
    $5, $6
) RETURNING id, order_id, action, from_status, to_status, operator_id, comment, created_at
`

type CreateWorkOrderLogParams struct {
	OrderID    uuid.UUID   `json:"order_id"`
	Action     string      `json:"action"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   pgtype.Text `json:"to_status"`
	OperatorID pgtype.UUID `json:"operator_id"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CreateWorkOrderLog(ctx context.Context, arg CreateWorkOrderLogParams) (WorkOrderLog, error) {
	row := q.db.QueryRow(ctx, createWorkOrderLog,
		arg.OrderID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.OperatorID,
		arg.Comment,
	)
	var i WorkOrderLog
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.OperatorID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at FROM work_orders WHERE id = $1
`

func (q *Queries) GetWorkOrder(ctx context.Context, id uuid.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkOrderLogs = `-- name: ListWorkOrderLogs :many
SELECT id, order_id, action, from_status, to_status, operator_id, comment, created_at FROM work_order_logs
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) ListWorkOrderLogs(ctx context.Context, orderID uuid.UUID) ([]WorkOrderLog, error) {
	rows, err := q.db.Query(ctx, listWorkOrderLogs, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrderLog{}
	for rows.Next() {
		var i WorkOrderLog
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.OperatorID,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrders = `-- name: ListWorkOrders :many
SELECT id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at FROM work_orders
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR asset_id = $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkOrdersParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   pgtype.Text `json:"status"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) ListWorkOrders(ctx context.Context, arg ListWorkOrdersParams) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listWorkOrders,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AssetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrder{}
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.LocationID,
			&i.AssetID,
			&i.RequestorID,
			&i.AssigneeID,
			&i.Description,
			&i.Reason,
			&i.PredictionID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkOrder = `-- name: UpdateWorkOrder :one
UPDATE work_orders SET
    title           = COALESCE($1, title),
    description     = COALESCE($2, description),
    priority        = COALESCE($3, priority),
    assignee_id     = COALESCE($4, assignee_id),
    scheduled_start = COALESCE($5, scheduled_start),
    scheduled_end   = COALESCE($6, scheduled_end),
    updated_at      = now()
WHERE id = $7
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at
`

type UpdateWorkOrderParams struct {
	Title          pgtype.Text        `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Priority       pgtype.Text        `json:"priority"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd   pgtype.Timestamptz `json:"scheduled_end"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrder,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssigneeID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.ID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE work_orders SET
    status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at
`

type UpdateWorkOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus, arg.ID, arg.Status)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
