// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_order_dedup.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const checkWorkOrderDedup = `-- name: CheckWorkOrderDedup :one

SELECT EXISTS (
    SELECT 1 FROM work_order_dedup
    WHERE tenant_id  = $1
      AND dedup_kind = $2
      AND dedup_key  = $3
) AS exists
`

type CheckWorkOrderDedupParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	DedupKind string    `json:"dedup_kind"`
	DedupKey  string    `json:"dedup_key"`
}

// Phase 2.15: work_order_dedup queries backing the auto-WO dedup
// contract that replaces the old `description LIKE` hack.
// Probe: does a dedup entry already exist for (tenant, kind, key)?
// Used in the per-tenant scan to skip a candidate BEFORE starting a
// transaction. The authoritative uniqueness check is the ON CONFLICT
// on InsertWorkOrderDedup — this probe is only a fast pre-filter.
func (q *Queries) CheckWorkOrderDedup(ctx context.Context, arg CheckWorkOrderDedupParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkOrderDedup, arg.TenantID, arg.DedupKind, arg.DedupKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWorkOrderDedup = `-- name: InsertWorkOrderDedup :execrows
INSERT INTO work_order_dedup (
    tenant_id, work_order_id, dedup_kind, dedup_key
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (tenant_id, dedup_kind, dedup_key) DO NOTHING
`

type InsertWorkOrderDedupParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	WorkOrderID uuid.UUID `json:"work_order_id"`
	DedupKind   string    `json:"dedup_kind"`
	DedupKey    string    `json:"dedup_key"`
}

// Race-safe insert. Returns 0 rows if (tenant, kind, key) already exists
// — the caller rolls back the surrounding transaction so the orphan WO
// is never persisted. ON CONFLICT DO NOTHING means a lost race just
// produces a no-op, never an error.
func (q *Queries) InsertWorkOrderDedup(ctx context.Context, arg InsertWorkOrderDedupParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWorkOrderDedup,
		arg.TenantID,
		arg.WorkOrderID,
		arg.DedupKind,
		arg.DedupKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
