// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_orders.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const breachSLAWorkOrders = `-- name: BreachSLAWorkOrders :many
UPDATE work_orders
SET sla_breached = true, updated_at = now()
WHERE tenant_id IS NOT NULL
  AND status IN ('approved', 'in_progress')
  AND sla_deadline IS NOT NULL
  AND sla_deadline < now()
  AND NOT sla_breached
  AND deleted_at IS NULL
RETURNING id, tenant_id, code, assignee_id
`

type BreachSLAWorkOrdersRow struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	Code       string      `json:"code"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

// Atomic cross-tenant SLA breach sweep: flips sla_breached=true and
// RETURNs every row that transitioned, in one round-trip. The
// `NOT sla_breached` guard inside the UPDATE is what makes this
// TOCTOU-safe: a second concurrent caller finds the already-flipped
// flag and gets zero rows back. Called by the scheduler only; has no
// tenant filter by design (see workflows/sla.go).
func (q *Queries) BreachSLAWorkOrders(ctx context.Context) ([]BreachSLAWorkOrdersRow, error) {
	rows, err := q.db.Query(ctx, breachSLAWorkOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreachSLAWorkOrdersRow{}
	for rows.Next() {
		var i BreachSLAWorkOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.AssigneeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkOrders = `-- name: CountWorkOrders :one
SELECT count(*) FROM work_orders
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR asset_id = $3)
  AND ($4::uuid IS NULL OR location_id = $4)
`

type CountWorkOrdersParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Status     pgtype.Text `json:"status"`
	AssetID    pgtype.UUID `json:"asset_id"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) CountWorkOrders(ctx context.Context, arg CountWorkOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkOrders,
		arg.TenantID,
		arg.Status,
		arg.AssetID,
		arg.LocationID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO work_orders (
    tenant_id, code, title, type, status, priority,
    location_id, asset_id, requestor_id, assignee_id,
    description, reason, prediction_id,
    scheduled_start, scheduled_end
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15
) RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type CreateWorkOrderParams struct {
	TenantID       uuid.UUID          `json:"tenant_id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	LocationID     pgtype.UUID        `json:"location_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	RequestorID    pgtype.UUID        `json:"requestor_id"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	Description    pgtype.Text        `json:"description"`
	Reason         pgtype.Text        `json:"reason"`
	PredictionID   pgtype.UUID        `json:"prediction_id"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd   pgtype.Timestamptz `json:"scheduled_end"`
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.TenantID,
		arg.Code,
		arg.Title,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.LocationID,
		arg.AssetID,
		arg.RequestorID,
		arg.AssigneeID,
		arg.Description,
		arg.Reason,
		arg.PredictionID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const createWorkOrderLog = `-- name: CreateWorkOrderLog :one
INSERT INTO work_order_logs (
    order_id, action, from_status, to_status,
    operator_id, comment
) VALUES (
    $1, $2, $3, $4,
    $5, $6
) RETURNING id, order_id, action, from_status, to_status, operator_id, comment, created_at
`

type CreateWorkOrderLogParams struct {
	OrderID    uuid.UUID   `json:"order_id"`
	Action     string      `json:"action"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   pgtype.Text `json:"to_status"`
	OperatorID pgtype.UUID `json:"operator_id"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CreateWorkOrderLog(ctx context.Context, arg CreateWorkOrderLogParams) (WorkOrderLog, error) {
	row := q.db.QueryRow(ctx, createWorkOrderLog,
		arg.OrderID,
		arg.Action,
		arg.FromStatus,
		arg.ToStatus,
		arg.OperatorID,
		arg.Comment,
	)
	var i WorkOrderLog
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Action,
		&i.FromStatus,
		&i.ToStatus,
		&i.OperatorID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status FROM work_orders WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetWorkOrderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetWorkOrder(ctx context.Context, arg GetWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, arg.ID, arg.TenantID)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const listOverdueSLAOrders = `-- name: ListOverdueSLAOrders :many
SELECT id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status FROM work_orders
WHERE tenant_id = $1
  AND status IN ('approved', 'in_progress')
  AND sla_deadline IS NOT NULL
  AND sla_deadline < now()
  AND sla_breached = false
  AND deleted_at IS NULL
`

func (q *Queries) ListOverdueSLAOrders(ctx context.Context, tenantID uuid.UUID) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listOverdueSLAOrders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrder{}
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.LocationID,
			&i.AssetID,
			&i.RequestorID,
			&i.AssigneeID,
			&i.Description,
			&i.Reason,
			&i.PredictionID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.SlaDeadline,
			&i.SlaWarningSent,
			&i.SlaBreached,
			&i.SyncVersion,
			&i.ExecutionStatus,
			&i.GovernanceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLAWarningOrders = `-- name: ListSLAWarningOrders :many
SELECT id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status FROM work_orders
WHERE tenant_id = $1
  AND status IN ('approved', 'in_progress')
  AND sla_deadline IS NOT NULL
  AND sla_warning_sent = false
  AND approved_at IS NOT NULL
  AND sla_deadline - (sla_deadline - approved_at) * 0.25 < now()
  AND deleted_at IS NULL
`

func (q *Queries) ListSLAWarningOrders(ctx context.Context, tenantID uuid.UUID) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listSLAWarningOrders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrder{}
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.LocationID,
			&i.AssetID,
			&i.RequestorID,
			&i.AssigneeID,
			&i.Description,
			&i.Reason,
			&i.PredictionID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.SlaDeadline,
			&i.SlaWarningSent,
			&i.SlaBreached,
			&i.SyncVersion,
			&i.ExecutionStatus,
			&i.GovernanceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderLogs = `-- name: ListWorkOrderLogs :many
SELECT id, order_id, action, from_status, to_status, operator_id, comment, created_at FROM work_order_logs
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) ListWorkOrderLogs(ctx context.Context, orderID uuid.UUID) ([]WorkOrderLog, error) {
	rows, err := q.db.Query(ctx, listWorkOrderLogs, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrderLog{}
	for rows.Next() {
		var i WorkOrderLog
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Action,
			&i.FromStatus,
			&i.ToStatus,
			&i.OperatorID,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrders = `-- name: ListWorkOrders :many
SELECT id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status FROM work_orders
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR asset_id = $5)
  AND ($6::uuid IS NULL OR location_id = $6)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkOrdersParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     pgtype.Text `json:"status"`
	AssetID    pgtype.UUID `json:"asset_id"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) ListWorkOrders(ctx context.Context, arg ListWorkOrdersParams) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listWorkOrders,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AssetID,
		arg.LocationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrder{}
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Title,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.LocationID,
			&i.AssetID,
			&i.RequestorID,
			&i.AssigneeID,
			&i.Description,
			&i.Reason,
			&i.PredictionID,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.ActualStart,
			&i.ActualEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.SlaDeadline,
			&i.SlaWarningSent,
			&i.SlaBreached,
			&i.SyncVersion,
			&i.ExecutionStatus,
			&i.GovernanceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSLABreached = `-- name: MarkSLABreached :exec
UPDATE work_orders SET sla_breached = true WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type MarkSLABreachedParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkSLABreached(ctx context.Context, arg MarkSLABreachedParams) error {
	_, err := q.db.Exec(ctx, markSLABreached, arg.ID, arg.TenantID)
	return err
}

const markSLAWarning = `-- name: MarkSLAWarning :exec
UPDATE work_orders SET sla_warning_sent = true WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type MarkSLAWarningParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkSLAWarning(ctx context.Context, arg MarkSLAWarningParams) error {
	_, err := q.db.Exec(ctx, markSLAWarning, arg.ID, arg.TenantID)
	return err
}

const softDeleteWorkOrder = `-- name: SoftDeleteWorkOrder :exec
UPDATE work_orders
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWorkOrderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) SoftDeleteWorkOrder(ctx context.Context, arg SoftDeleteWorkOrderParams) error {
	_, err := q.db.Exec(ctx, softDeleteWorkOrder, arg.ID, arg.TenantID)
	return err
}

const stampWorkOrderApproval = `-- name: StampWorkOrderApproval :one
UPDATE work_orders SET
    approved_at       = now(),
    approved_by       = $2,
    sla_deadline      = $3,
    status            = 'approved',
    governance_status = 'approved',
    updated_at        = now()
WHERE id = $1 AND tenant_id = $4 AND governance_status = 'submitted' AND deleted_at IS NULL
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type StampWorkOrderApprovalParams struct {
	ID          uuid.UUID          `json:"id"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	SlaDeadline pgtype.Timestamptz `json:"sla_deadline"`
	TenantID    uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) StampWorkOrderApproval(ctx context.Context, arg StampWorkOrderApprovalParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, stampWorkOrderApproval,
		arg.ID,
		arg.ApprovedBy,
		arg.SlaDeadline,
		arg.TenantID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const transitionEmergencyWorkOrder = `-- name: TransitionEmergencyWorkOrder :one
UPDATE work_orders SET
    governance_status = 'approved',
    execution_status  = 'working',
    status            = 'in_progress',
    approved_at       = now(),
    approved_by       = $3,
    sla_deadline      = $4,
    updated_at        = now()
WHERE id = $1
  AND tenant_id = $2
  AND type = 'emergency'
  AND governance_status = 'submitted'
  AND execution_status = 'pending'
  AND deleted_at IS NULL
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type TransitionEmergencyWorkOrderParams struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	SlaDeadline pgtype.Timestamptz `json:"sla_deadline"`
}

// Atomically approves-and-starts an emergency work order in a single UPDATE.
// Replaces the previous two-step flow (approve, then in_progress) which could
// strand a WO half-approved if the process crashed, timed out, or retried
// between the two statements.
//
// Guards (all required, all enforced by the WHERE clause):
//   - tenant_id: defense-in-depth isolation
//   - type = 'emergency': only emergency orders skip the approval queue
//   - governance_status = 'submitted': idempotent; a second caller gets 0 rows
//   - execution_status = 'pending': prevents double-start
//   - deleted_at IS NULL: don't resurrect tombstoned rows
//
// 0 rows returned = idempotent success (already transitioned, stale retry, or
// wrong type/tenant). The caller treats pgx.ErrNoRows as (nil, nil).
func (q *Queries) TransitionEmergencyWorkOrder(ctx context.Context, arg TransitionEmergencyWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, transitionEmergencyWorkOrder,
		arg.ID,
		arg.TenantID,
		arg.ApprovedBy,
		arg.SlaDeadline,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE work_orders SET
    execution_status = $2,
    status           = $3,
    updated_at       = now()
WHERE id = $1 AND tenant_id = $4 AND execution_status = $5 AND deleted_at IS NULL
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type UpdateExecutionStatusParams struct {
	ID                uuid.UUID `json:"id"`
	ExecutionStatus   string    `json:"execution_status"`
	Status            string    `json:"status"`
	TenantID          uuid.UUID `json:"tenant_id"`
	ExecutionStatus_2 string    `json:"execution_status_2"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateExecutionStatus,
		arg.ID,
		arg.ExecutionStatus,
		arg.Status,
		arg.TenantID,
		arg.ExecutionStatus_2,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const updateGovernanceStatus = `-- name: UpdateGovernanceStatus :one
UPDATE work_orders SET
    governance_status = $2,
    status            = $3,
    updated_at        = now()
WHERE id = $1 AND tenant_id = $4 AND governance_status = $5 AND deleted_at IS NULL
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type UpdateGovernanceStatusParams struct {
	ID                 uuid.UUID `json:"id"`
	GovernanceStatus   string    `json:"governance_status"`
	Status             string    `json:"status"`
	TenantID           uuid.UUID `json:"tenant_id"`
	GovernanceStatus_2 string    `json:"governance_status_2"`
}

func (q *Queries) UpdateGovernanceStatus(ctx context.Context, arg UpdateGovernanceStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateGovernanceStatus,
		arg.ID,
		arg.GovernanceStatus,
		arg.Status,
		arg.TenantID,
		arg.GovernanceStatus_2,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const updateWorkOrder = `-- name: UpdateWorkOrder :one
UPDATE work_orders SET
    title           = COALESCE($1, title),
    description     = COALESCE($2, description),
    priority        = COALESCE($3, priority),
    assignee_id     = COALESCE($4, assignee_id),
    scheduled_start = COALESCE($5, scheduled_start),
    scheduled_end   = COALESCE($6, scheduled_end),
    updated_at      = now()
WHERE id = $7 AND tenant_id = $8 AND deleted_at IS NULL
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type UpdateWorkOrderParams struct {
	Title          pgtype.Text        `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Priority       pgtype.Text        `json:"priority"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ScheduledEnd   pgtype.Timestamptz `json:"scheduled_end"`
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrder,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssigneeID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.ID,
		arg.TenantID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE work_orders SET
    status     = $2,
    updated_at = now()
WHERE id = $1 AND tenant_id = $3 AND status = $4 AND deleted_at IS NULL
RETURNING id, tenant_id, code, title, type, status, priority, location_id, asset_id, requestor_id, assignee_id, description, reason, prediction_id, scheduled_start, scheduled_end, actual_start, actual_end, created_at, updated_at, deleted_at, approved_at, approved_by, sla_deadline, sla_warning_sent, sla_breached, sync_version, execution_status, governance_status
`

type UpdateWorkOrderStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status_2 string    `json:"status_2"`
}

func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus,
		arg.ID,
		arg.Status,
		arg.TenantID,
		arg.Status_2,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.LocationID,
		&i.AssetID,
		&i.RequestorID,
		&i.AssigneeID,
		&i.Description,
		&i.Reason,
		&i.PredictionID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.ActualStart,
		&i.ActualEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.SlaDeadline,
		&i.SlaWarningSent,
		&i.SlaBreached,
		&i.SyncVersion,
		&i.ExecutionStatus,
		&i.GovernanceStatus,
	)
	return i, err
}
